#!/bin/bash

./render
echo 'profiling with GJS'
echo 'unminified'
gjs caterwaul.all-profiled.js >& log-gjs-u

echo 'minified'
gjs caterwaul.all-profiled.min.js >& log-gjs-m

echo 'profiled core'
gjs caterwaul.profiled-core.js >& log-gjs-c
