$(caterwaul.clone('std seq continuation')(function () {
  $('body').append(shell());
  setTimeout(fn_[$('.prompt .input').focus()], 10);

  adjust_sizing(), $(window).resize(),
  where*[adjust_sizing() = $('body').css({height: $(window).height()})];
}));
// Generated by SDoc 
