// Tests for composition via the after() method.

test('after', function () {
  caterwaul.clone('std')(function (eq) {
    var c1 = caterwaul.clone('std macro'), c2 = caterwaul.clone('std macro');

    eq(c1.after.constructor, Function); c1.rmacro(qs[_ + _], fn[x, y][qs[_x * _y].replace({_x: x, _y: y})]);
    eq(c2.after.constructor, Function); c2.rmacro(qs[_ * _], fn[x, y][qs[_x + _y].replace({_x: x, _y: y})]);

    var c12 = c1.clone();
    eq(c12.after(c2), c12);
    eq(c12.after().length, 1);
    eq(c12.after()[0], c2);
    eq(c12(qs[x + y]).data, '+');
    eq(c12(qs[x * y]).data, '+');

    var c21 = c2.clone();
    eq(c21.after(c1), c21);
    eq(c21.after().length, 1);
    eq(c21.after()[0], c1);
    eq(c21(qs[x + y]).data, '*');
    eq(c21(qs[x * y]).data, '*');
  })(eq);
});
// Generated by SDoc 
