// Tests for composition via the after() method.

test('after', function () {
  caterwaul.clone('std')(function (eq) {
    var c1 = caterwaul.clone('std'), c2 = caterwaul.clone('std');

    eq(c1.after.constructor, Function); literal[c1(function () {defsubst[_x + _y][_x * _y]})];
    eq(c2.after.constructor, Function); literal[c2(function () {defsubst[_x * _y][_x + _y]})];

    var c12 = c1.after(c2);
    eq(c12(qs[x + y]).data, '+');
    eq(c12(qs[x * y]).data, '+');

    var c21 = c2.after(c1);
    eq(c21(qs[x + y]).data, '*');
    eq(c21(qs[x * y]).data, '*');
  })(eq);
});
// Generated by SDoc 
