// Caterwaul local standard library tests

test(function () {
  var fn = caterwaul.clone('std.local');

  fn(function (eq) {
    eq(local['std.fn'][fn[x][x + 1]](6), 7);
    eq(local['std.fn'][fn[x, y][x + y](6, 7)], 13);
    eq(local['std.fn'][fn_[10]](), 10);

    eq(local['std.bind'][let[y = 5] in y + 1], 6);
    eq(local['std.bind'][let[y = 5, a = 6] in y + a], 11);

    eq(local['std.bind'][let*[x = 4, y = x] in x + y], 8);
    eq(local['std.bind std.fn'][let*[fact = fn[n][n > 1 ? n * fact(n - 1) : 1]] in fact(5)], 120);

    eq(local['std.bind'][z + 1, where[z = 5]], 6);
    eq(local['std.bind'][q + w, where[q = 10, w = 100]], 110);

    eq(local['std.bind'][x + y, where*[x = 4, y = x]], 8);
    eq(local['std.bind std.fn'][fact(5), where*[fact = fn[n][n > 1 ? n * fact(n - 1) : 1]]], 120);

    eq(local['std.cond'][5, when[true]], 5);
    eq(local['std.cond'][5, when[false]], false);

    eq(local['std.cond'][5, unless[true]], false);
    eq(local['std.cond'][5, unless[false]], 5);
  }) (eq);
});

// Generated by SDoc 
