statement=function(input_,start_,end_) {;
return this.constructor===statement? (this.input_=input_,this.start_=start_,this.end_=end_,this) :statement.parse(arguments[0] ,arguments[1] ||0) } ,statement.parse=function(s,i) {var ii=i;
if(ii> -1) {var _2_vPZqNwk$K_RP34tFHstFKC=ii;
if(_2_vPZqNwk$K_RP34tFHstFKC> -1) {if(_2_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_2_vPZqNwk$K_RP34tFHstFKC,_2_vPZqNwk$K_RP34tFHstFKC+=5) !== "block" )_2_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_2_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_2_vPZqNwk$K_RP34tFHstFKC,_2_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_2_vPZqNwk$K_RP34tFHstFKC= -1} } ;
if(_2_vPZqNwk$K_RP34tFHstFKC> -1)ii=_2_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {var _3_vPZqNwk$K_RP34tFHstFKC=ii;
if(_3_vPZqNwk$K_RP34tFHstFKC> -1) {if(_3_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_3_vPZqNwk$K_RP34tFHstFKC,_3_vPZqNwk$K_RP34tFHstFKC+=9) !== "with_semi" )_3_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_3_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_3_vPZqNwk$K_RP34tFHstFKC,_3_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_3_vPZqNwk$K_RP34tFHstFKC= -1} } ;
if(_3_vPZqNwk$K_RP34tFHstFKC> -1)ii=_3_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {var _4_vPZqNwk$K_RP34tFHstFKC=ii;
if(_4_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_4_vPZqNwk$K_RP34tFHstFKC,_4_vPZqNwk$K_RP34tFHstFKC+=1) !== ";" )_4_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_4_vPZqNwk$K_RP34tFHstFKC> -1)ii=_4_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=10) !== "statement_" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } } } } ;
if(ii> -1)return new statement(s,i,ii) } ,statement.prototype= {map:function(f) {var r=f(this) ;
return r===true|| !r?this:r} ,start:function() {;
return this.start_} ,end:function() {;
return this.end_} ,length:0,toString:function() {;
return this.input_.substring(this.start_,this.end_) } } ,statement.prototype.constructor=statement,block=function(input_,start_,end_) {;
return this.constructor===block? (this.input_=input_,this.start_=start_,this.end_=end_,this) :block.parse(arguments[0] ,arguments[1] ||0) } ,block.parse=function(s,i) {var ii=i;
if(ii> -1) {if(ii> -1) {if( ! /\{/ .test(s.charAt(ii++ ) ) )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=10) !== "statements" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} ;
if(ii> -1) {if( ! /\}/ .test(s.charAt(ii++ ) ) )ii= -1} } } } ;
if(ii> -1)return new block(s,i,ii) } ,block.prototype= {map:function(f) {var r=f(this) ;
return r===true|| !r?this:r} ,start:function() {;
return this.start_} ,end:function() {;
return this.end_} ,length:0,toString:function() {;
return this.input_.substring(this.start_,this.end_) } } ,block.prototype.constructor=block,with_semi=function(input_,start_,end_) {;
return this.constructor===with_semi? (this.input_=input_,this.start_=start_,this.end_=end_,this) :with_semi.parse(arguments[0] ,arguments[1] ||0) } ,with_semi.parse=function(s,i) {var ii=i;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== "s" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=10) !== "statement_" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== ";" )ii= -1} } ;
if(ii> -1)return new with_semi(s,i,ii) } ,with_semi.prototype= {map:function(f) {var r=f(this) ;
return r===true|| !r?this:r} ,start:function() {;
return this.start_} ,end:function() {;
return this.end_} ,length:0,toString:function() {;
return this.input_.substring(this.start_,this.end_) } } ,with_semi.prototype.constructor=with_semi,statement_=function(input_,start_,end_) {;
return this.constructor===statement_? (this.input_=input_,this.start_=start_,this.end_=end_,this) :statement_.parse(arguments[0] ,arguments[1] ||0) } ,statement_.parse=function(s,i) {var ii=i;
if(ii> -1) {var _5_vPZqNwk$K_RP34tFHstFKC=ii;
if(_5_vPZqNwk$K_RP34tFHstFKC> -1) {if(_5_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_5_vPZqNwk$K_RP34tFHstFKC,_5_vPZqNwk$K_RP34tFHstFKC+=3) !== "if_" )_5_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_5_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_5_vPZqNwk$K_RP34tFHstFKC,_5_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_5_vPZqNwk$K_RP34tFHstFKC= -1} } ;
if(_5_vPZqNwk$K_RP34tFHstFKC> -1)ii=_5_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {var _6_vPZqNwk$K_RP34tFHstFKC=ii;
if(_6_vPZqNwk$K_RP34tFHstFKC> -1) {if(_6_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_6_vPZqNwk$K_RP34tFHstFKC,_6_vPZqNwk$K_RP34tFHstFKC+=12) !== "for_iterator" )_6_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_6_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_6_vPZqNwk$K_RP34tFHstFKC,_6_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_6_vPZqNwk$K_RP34tFHstFKC= -1} } ;
if(_6_vPZqNwk$K_RP34tFHstFKC> -1)ii=_6_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {var _7_vPZqNwk$K_RP34tFHstFKC=ii;
if(_7_vPZqNwk$K_RP34tFHstFKC> -1) {if(_7_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_7_vPZqNwk$K_RP34tFHstFKC,_7_vPZqNwk$K_RP34tFHstFKC+=6) !== "for_in" )_7_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_7_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_7_vPZqNwk$K_RP34tFHstFKC,_7_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_7_vPZqNwk$K_RP34tFHstFKC= -1} } ;
if(_7_vPZqNwk$K_RP34tFHstFKC> -1)ii=_7_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {var _8_vPZqNwk$K_RP34tFHstFKC=ii;
if(_8_vPZqNwk$K_RP34tFHstFKC> -1) {if(_8_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_8_vPZqNwk$K_RP34tFHstFKC,_8_vPZqNwk$K_RP34tFHstFKC+=6) !== "while_" )_8_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_8_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_8_vPZqNwk$K_RP34tFHstFKC,_8_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_8_vPZqNwk$K_RP34tFHstFKC= -1} } ;
if(_8_vPZqNwk$K_RP34tFHstFKC> -1)ii=_8_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {var _9_vPZqNwk$K_RP34tFHstFKC=ii;
if(_9_vPZqNwk$K_RP34tFHstFKC> -1) {if(_9_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_9_vPZqNwk$K_RP34tFHstFKC,_9_vPZqNwk$K_RP34tFHstFKC+=3) !== "do_" )_9_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_9_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_9_vPZqNwk$K_RP34tFHstFKC,_9_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_9_vPZqNwk$K_RP34tFHstFKC= -1} } ;
if(_9_vPZqNwk$K_RP34tFHstFKC> -1)ii=_9_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {var _a_vPZqNwk$K_RP34tFHstFKC=ii;
if(_a_vPZqNwk$K_RP34tFHstFKC> -1) {if(_a_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_a_vPZqNwk$K_RP34tFHstFKC,_a_vPZqNwk$K_RP34tFHstFKC+=7) !== "switch_" )_a_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_a_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_a_vPZqNwk$K_RP34tFHstFKC,_a_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_a_vPZqNwk$K_RP34tFHstFKC= -1} } ;
if(_a_vPZqNwk$K_RP34tFHstFKC> -1)ii=_a_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {var _b_vPZqNwk$K_RP34tFHstFKC=ii;
if(_b_vPZqNwk$K_RP34tFHstFKC> -1) {if(_b_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_b_vPZqNwk$K_RP34tFHstFKC,_b_vPZqNwk$K_RP34tFHstFKC+=6) !== "throw_" )_b_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_b_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_b_vPZqNwk$K_RP34tFHstFKC,_b_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_b_vPZqNwk$K_RP34tFHstFKC= -1} } ;
if(_b_vPZqNwk$K_RP34tFHstFKC> -1)ii=_b_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {var _c_vPZqNwk$K_RP34tFHstFKC=ii;
if(_c_vPZqNwk$K_RP34tFHstFKC> -1) {if(_c_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_c_vPZqNwk$K_RP34tFHstFKC,_c_vPZqNwk$K_RP34tFHstFKC+=4) !== "try_" )_c_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_c_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_c_vPZqNwk$K_RP34tFHstFKC,_c_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_c_vPZqNwk$K_RP34tFHstFKC= -1} } ;
if(_c_vPZqNwk$K_RP34tFHstFKC> -1)ii=_c_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=10) !== "expression" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } } } } } } } } } } } } } } ;
if(ii> -1)return new statement_(s,i,ii) } ,statement_.prototype= {map:function(f) {var r=f(this) ;
return r===true|| !r?this:r} ,start:function() {;
return this.start_} ,end:function() {;
return this.end_} ,length:0,toString:function() {;
return this.input_.substring(this.start_,this.end_) } } ,statement_.prototype.constructor=statement_,if_=function(input_,start_,end_) {;
return this.constructor===if_? (this.input_=input_,this.start_=start_,this.end_=end_,this) :if_.parse(arguments[0] ,arguments[1] ||0) } ,if_.parse=function(s,i) {var ii=i;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=2) !== "if" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=3) !== "pre" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=2) !== "ws" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if(ii> -1) {if( ! /\(/ .test(s.charAt(ii++ ) ) )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=4) !== "cond" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=10) !== "expression" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if(ii> -1) {if( ! /\)/ .test(s.charAt(ii++ ) ) )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=3) !== "lhs" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=9) !== "statement" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=3) !== "rhs" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=5) !== "else_" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } } } } } } } ;
if(ii> -1)return new if_(s,i,ii) } ,if_.prototype= {map:function(f) {var r=f(this) ;
return r===true|| !r?this:r} ,start:function() {;
return this.start_} ,end:function() {;
return this.end_} ,length:0,toString:function() {;
return this.input_.substring(this.start_,this.end_) } } ,if_.prototype.constructor=if_,else_=function(input_,start_,end_) {;
return this.constructor===else_? (this.input_=input_,this.start_=start_,this.end_=end_,this) :else_.parse(arguments[0] ,arguments[1] ||0) } ,else_.parse=function(s,i) {var ii=i;
if(ii> -1) {var _d_vPZqNwk$K_RP34tFHstFKC=ii;
if(_d_vPZqNwk$K_RP34tFHstFKC> -1) {if(_d_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_d_vPZqNwk$K_RP34tFHstFKC,_d_vPZqNwk$K_RP34tFHstFKC+=4) !== "else" )_d_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_d_vPZqNwk$K_RP34tFHstFKC> -1) {if(_d_vPZqNwk$K_RP34tFHstFKC> -1) {if(_d_vPZqNwk$K_RP34tFHstFKC> -1) {if(_d_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_d_vPZqNwk$K_RP34tFHstFKC,_d_vPZqNwk$K_RP34tFHstFKC+=3) !== "pre" )_d_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_d_vPZqNwk$K_RP34tFHstFKC> -1) {if(_d_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_d_vPZqNwk$K_RP34tFHstFKC,_d_vPZqNwk$K_RP34tFHstFKC+=1) !== ":" )_d_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_d_vPZqNwk$K_RP34tFHstFKC> -1) {if(_d_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_d_vPZqNwk$K_RP34tFHstFKC,_d_vPZqNwk$K_RP34tFHstFKC+=2) !== "ws" )_d_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_d_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_d_vPZqNwk$K_RP34tFHstFKC,_d_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_d_vPZqNwk$K_RP34tFHstFKC= -1} } } } } ;
if(_d_vPZqNwk$K_RP34tFHstFKC> -1) {if(_d_vPZqNwk$K_RP34tFHstFKC> -1) {if(_d_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_d_vPZqNwk$K_RP34tFHstFKC,_d_vPZqNwk$K_RP34tFHstFKC+=3) !== "lhs" )_d_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_d_vPZqNwk$K_RP34tFHstFKC> -1) {if(_d_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_d_vPZqNwk$K_RP34tFHstFKC,_d_vPZqNwk$K_RP34tFHstFKC+=1) !== ":" )_d_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_d_vPZqNwk$K_RP34tFHstFKC> -1) {if(_d_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_d_vPZqNwk$K_RP34tFHstFKC,_d_vPZqNwk$K_RP34tFHstFKC+=9) !== "statement" )_d_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_d_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_d_vPZqNwk$K_RP34tFHstFKC,_d_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_d_vPZqNwk$K_RP34tFHstFKC= -1} } } } } } } ;
if(_d_vPZqNwk$K_RP34tFHstFKC> -1)ii=_d_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=2) !== "ws" )ii= -1} } } } ;
if(ii> -1)return new else_(s,i,ii) } ,else_.prototype= {map:function(f) {var r=f(this) ;
return r===true|| !r?this:r} ,start:function() {;
return this.start_} ,end:function() {;
return this.end_} ,length:0,toString:function() {;
return this.input_.substring(this.start_,this.end_) } } ,else_.prototype.constructor=else_,for_iterator=function(input_,start_,end_) {;
return this.constructor===for_iterator? (this.input_=input_,this.start_=start_,this.end_=end_,this) :for_iterator.parse(arguments[0] ,arguments[1] ||0) } ,for_iterator.parse=function(s,i) {var ii=i;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=3) !== "for" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=3) !== "pre" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=2) !== "ws" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if(ii> -1) {if( ! /\(/ .test(s.charAt(ii++ ) ) )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=4) !== "init" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=9) !== "statement" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=4) !== "cond" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=10) !== "expression" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=9) !== "post_cond" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=2) !== "ws" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ";" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=3) !== "inc" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=10) !== "expression" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if(ii> -1) {if( ! /\)/ .test(s.charAt(ii++ ) ) )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=3) !== "lhs" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=9) !== "statement" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } } } } } } } } } } ;
if(ii> -1)return new for_iterator(s,i,ii) } ,for_iterator.prototype= {map:function(f) {var r=f(this) ;
return r===true|| !r?this:r} ,start:function() {;
return this.start_} ,end:function() {;
return this.end_} ,length:0,toString:function() {;
return this.input_.substring(this.start_,this.end_) } } ,for_iterator.prototype.constructor=for_iterator,for_in=function(input_,start_,end_) {;
return this.constructor===for_in? (this.input_=input_,this.start_=start_,this.end_=end_,this) :for_in.parse(arguments[0] ,arguments[1] ||0) } ,for_in.parse=function(s,i) {var ii=i;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=3) !== "for" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=3) !== "pre" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=2) !== "ws" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if(ii> -1) {if( ! /\(/ .test(s.charAt(ii++ ) ) )ii= -1} ;
if(ii> -1) {if(ii> -1) {var _e_vPZqNwk$K_RP34tFHstFKC=ii,_f_vPZqNwk$K_RP34tFHstFKC=0;
if(_e_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_e_vPZqNwk$K_RP34tFHstFKC,_e_vPZqNwk$K_RP34tFHstFKC+=3) !== "var" )_e_vPZqNwk$K_RP34tFHstFKC= -1} ;
while(_e_vPZqNwk$K_RP34tFHstFKC> -1&& ++_f_vPZqNwk$K_RP34tFHstFKC<=1)ii=_e_vPZqNwk$K_RP34tFHstFKC, (if(_e_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_e_vPZqNwk$K_RP34tFHstFKC,_e_vPZqNwk$K_RP34tFHstFKC+=3) !== "var" )_e_vPZqNwk$K_RP34tFHstFKC= -1} ) ;
if(_f_vPZqNwk$K_RP34tFHstFKC<0)ii= -1} ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=8) !== "variable" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=10) !== "identifier" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=13) !== "post_variable" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=2) !== "ws" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=2) !== "in" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=4) !== "cond" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=10) !== "expression" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if(ii> -1) {if( ! /\)/ .test(s.charAt(ii++ ) ) )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=3) !== "lhs" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=9) !== "statement" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } } } } } } } } } } ;
if(ii> -1)return new for_in(s,i,ii) } ,for_in.prototype= {map:function(f) {var r=f(this) ;
return r===true|| !r?this:r} ,start:function() {;
return this.start_} ,end:function() {;
return this.end_} ,length:0,toString:function() {;
return this.input_.substring(this.start_,this.end_) } } ,for_in.prototype.constructor=for_in,while_=function(input_,start_,end_) {;
return this.constructor===while_? (this.input_=input_,this.start_=start_,this.end_=end_,this) :while_.parse(arguments[0] ,arguments[1] ||0) } ,while_.parse=function(s,i) {var ii=i;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=5) !== "while" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=3) !== "pre" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=2) !== "ws" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if(ii> -1) {if( ! /\(/ .test(s.charAt(ii++ ) ) )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=4) !== "cond" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=10) !== "expression" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if(ii> -1) {if( ! /\)/ .test(s.charAt(ii++ ) ) )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=3) !== "lhs" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=9) !== "statement" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } } } } } } ;
if(ii> -1)return new while_(s,i,ii) } ,while_.prototype= {map:function(f) {var r=f(this) ;
return r===true|| !r?this:r} ,start:function() {;
return this.start_} ,end:function() {;
return this.end_} ,length:0,toString:function() {;
return this.input_.substring(this.start_,this.end_) } } ,while_.prototype.constructor=while_,do_=function(input_,start_,end_) {;
return this.constructor===do_? (this.input_=input_,this.start_=start_,this.end_=end_,this) :do_.parse(arguments[0] ,arguments[1] ||0) } ,do_.parse=function(s,i) {var ii=i;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=2) !== "do" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=3) !== "lhs" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=9) !== "statement" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=5) !== "while" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=3) !== "pre" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=2) !== "ws" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if(ii> -1) {if( ! /\(/ .test(s.charAt(ii++ ) ) )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=4) !== "cond" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=10) !== "expression" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if( ! /\)/ .test(s.charAt(ii++ ) ) )ii= -1} } } } } } } ;
if(ii> -1)return new do_(s,i,ii) } ,do_.prototype= {map:function(f) {var r=f(this) ;
return r===true|| !r?this:r} ,start:function() {;
return this.start_} ,end:function() {;
return this.end_} ,length:0,toString:function() {;
return this.input_.substring(this.start_,this.end_) } } ,do_.prototype.constructor=do_,switch_=function(input_,start_,end_) {;
return this.constructor===switch_? (this.input_=input_,this.start_=start_,this.end_=end_,this) :switch_.parse(arguments[0] ,arguments[1] ||0) } ,switch_.parse=function(s,i) {var ii=i;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=6) !== "switch" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=3) !== "pre" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=2) !== "ws" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if(ii> -1) {if( ! /\(/ .test(s.charAt(ii++ ) ) )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=4) !== "cond" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=10) !== "expression" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if(ii> -1) {if( ! /\)/ .test(s.charAt(ii++ ) ) )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=4) !== "post" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=2) !== "ws" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if(ii> -1) {if( ! /\{/ .test(s.charAt(ii++ ) ) )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=5) !== "cases" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=5) !== "cases" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if( ! /\}/ .test(s.charAt(ii++ ) ) )ii= -1} } } } } } } } } ;
if(ii> -1)return new switch_(s,i,ii) } ,switch_.prototype= {map:function(f) {var r=f(this) ;
return r===true|| !r?this:r} ,start:function() {;
return this.start_} ,end:function() {;
return this.end_} ,length:0,toString:function() {;
return this.input_.substring(this.start_,this.end_) } } ,switch_.prototype.constructor=switch_,cases=function(input_,start_,end_) {;
return this.constructor===cases? (this.input_=input_,this.start_=start_,this.end_=end_,this) :cases.parse(arguments[0] ,arguments[1] ||0) } ,cases.parse=function(s,i) {var ii=i;
if(ii> -1) {var _g_vPZqNwk$K_RP34tFHstFKC=ii;
if(_g_vPZqNwk$K_RP34tFHstFKC> -1) {if(_g_vPZqNwk$K_RP34tFHstFKC> -1) {if(_g_vPZqNwk$K_RP34tFHstFKC> -1) {if(_g_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_g_vPZqNwk$K_RP34tFHstFKC,_g_vPZqNwk$K_RP34tFHstFKC+=3) !== "lhs" )_g_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_g_vPZqNwk$K_RP34tFHstFKC> -1) {if(_g_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_g_vPZqNwk$K_RP34tFHstFKC,_g_vPZqNwk$K_RP34tFHstFKC+=1) !== ":" )_g_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_g_vPZqNwk$K_RP34tFHstFKC> -1) {if(_g_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_g_vPZqNwk$K_RP34tFHstFKC,_g_vPZqNwk$K_RP34tFHstFKC+=5) !== "case_" )_g_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_g_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_g_vPZqNwk$K_RP34tFHstFKC,_g_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_g_vPZqNwk$K_RP34tFHstFKC= -1} } } } } ;
if(_g_vPZqNwk$K_RP34tFHstFKC> -1) {if(_g_vPZqNwk$K_RP34tFHstFKC> -1) {if(_g_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_g_vPZqNwk$K_RP34tFHstFKC,_g_vPZqNwk$K_RP34tFHstFKC+=3) !== "rhs" )_g_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_g_vPZqNwk$K_RP34tFHstFKC> -1) {if(_g_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_g_vPZqNwk$K_RP34tFHstFKC,_g_vPZqNwk$K_RP34tFHstFKC+=1) !== ":" )_g_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_g_vPZqNwk$K_RP34tFHstFKC> -1) {if(_g_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_g_vPZqNwk$K_RP34tFHstFKC,_g_vPZqNwk$K_RP34tFHstFKC+=5) !== "cases" )_g_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_g_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_g_vPZqNwk$K_RP34tFHstFKC,_g_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_g_vPZqNwk$K_RP34tFHstFKC= -1} } } } } } ;
if(_g_vPZqNwk$K_RP34tFHstFKC> -1)ii=_g_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {var _h_vPZqNwk$K_RP34tFHstFKC=ii;
if(_h_vPZqNwk$K_RP34tFHstFKC> -1) {if(_h_vPZqNwk$K_RP34tFHstFKC> -1) {if(_h_vPZqNwk$K_RP34tFHstFKC> -1) {if(_h_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_h_vPZqNwk$K_RP34tFHstFKC,_h_vPZqNwk$K_RP34tFHstFKC+=3) !== "lhs" )_h_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_h_vPZqNwk$K_RP34tFHstFKC> -1) {if(_h_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_h_vPZqNwk$K_RP34tFHstFKC,_h_vPZqNwk$K_RP34tFHstFKC+=1) !== ":" )_h_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_h_vPZqNwk$K_RP34tFHstFKC> -1) {if(_h_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_h_vPZqNwk$K_RP34tFHstFKC,_h_vPZqNwk$K_RP34tFHstFKC+=8) !== "default_" )_h_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_h_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_h_vPZqNwk$K_RP34tFHstFKC,_h_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_h_vPZqNwk$K_RP34tFHstFKC= -1} } } } } ;
if(_h_vPZqNwk$K_RP34tFHstFKC> -1) {if(_h_vPZqNwk$K_RP34tFHstFKC> -1) {if(_h_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_h_vPZqNwk$K_RP34tFHstFKC,_h_vPZqNwk$K_RP34tFHstFKC+=3) !== "rhs" )_h_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_h_vPZqNwk$K_RP34tFHstFKC> -1) {if(_h_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_h_vPZqNwk$K_RP34tFHstFKC,_h_vPZqNwk$K_RP34tFHstFKC+=1) !== ":" )_h_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_h_vPZqNwk$K_RP34tFHstFKC> -1) {if(_h_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_h_vPZqNwk$K_RP34tFHstFKC,_h_vPZqNwk$K_RP34tFHstFKC+=5) !== "cases" )_h_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_h_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_h_vPZqNwk$K_RP34tFHstFKC,_h_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_h_vPZqNwk$K_RP34tFHstFKC= -1} } } } } } ;
if(_h_vPZqNwk$K_RP34tFHstFKC> -1)ii=_h_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=10) !== "statements" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } } ;
if(ii> -1)return new cases(s,i,ii) } ,cases.prototype= {map:function(f) {var r=f(this) ;
return r===true|| !r?this:r} ,start:function() {;
return this.start_} ,end:function() {;
return this.end_} ,length:0,toString:function() {;
return this.input_.substring(this.start_,this.end_) } } ,cases.prototype.constructor=cases,case_=function(input_,start_,end_) {;
return this.constructor===case_? (this.input_=input_,this.start_=start_,this.end_=end_,this) :case_.parse(arguments[0] ,arguments[1] ||0) } ,case_.parse=function(s,i) {var ii=i;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=3) !== "pre" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=2) !== "ws" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=4) !== "case" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=4) !== "cond" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=10) !== "expression" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if( ! /[:]/ .test(s.charAt(ii++ ) ) )ii= -1} } } } ;
if(ii> -1)return new case_(s,i,ii) } ,case_.prototype= {map:function(f) {var r=f(this) ;
return r===true|| !r?this:r} ,start:function() {;
return this.start_} ,end:function() {;
return this.end_} ,length:0,toString:function() {;
return this.input_.substring(this.start_,this.end_) } } ,case_.prototype.constructor=case_,default_=function(input_,start_,end_) {;
return this.constructor===default_? (this.input_=input_,this.start_=start_,this.end_=end_,this) :default_.parse(arguments[0] ,arguments[1] ||0) } ,default_.parse=function(s,i) {var ii=i;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=3) !== "pre" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=2) !== "ws" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=7) !== "default" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=4) !== "post" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=2) !== "ws" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if( ! /[:]/ .test(s.charAt(ii++ ) ) )ii= -1} } } } ;
if(ii> -1)return new default_(s,i,ii) } ,default_.prototype= {map:function(f) {var r=f(this) ;
return r===true|| !r?this:r} ,start:function() {;
return this.start_} ,end:function() {;
return this.end_} ,length:0,toString:function() {;
return this.input_.substring(this.start_,this.end_) } } ,default_.prototype.constructor=default_,throw_=function(input_,start_,end_) {;
return this.constructor===throw_? (this.input_=input_,this.start_=start_,this.end_=end_,this) :throw_.parse(arguments[0] ,arguments[1] ||0) } ,throw_.parse=function(s,i) {var ii=i;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=5) !== "throw" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=3) !== "lhs" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=10) !== "expression" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } } ;
if(ii> -1)return new throw_(s,i,ii) } ,throw_.prototype= {map:function(f) {var r=f(this) ;
return r===true|| !r?this:r} ,start:function() {;
return this.start_} ,end:function() {;
return this.end_} ,length:0,toString:function() {;
return this.input_.substring(this.start_,this.end_) } } ,throw_.prototype.constructor=throw_,try_=function(input_,start_,end_) {;
return this.constructor===try_? (this.input_=input_,this.start_=start_,this.end_=end_,this) :try_.parse(arguments[0] ,arguments[1] ||0) } ,try_.parse=function(s,i) {var ii=i;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=3) !== "try" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=3) !== "lhs" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=10) !== "statements" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=3) !== "rhs" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {var _i_vPZqNwk$K_RP34tFHstFKC=ii;
if(_i_vPZqNwk$K_RP34tFHstFKC> -1) {if(_i_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_i_vPZqNwk$K_RP34tFHstFKC,_i_vPZqNwk$K_RP34tFHstFKC+=6) !== "catch_" )_i_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_i_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_i_vPZqNwk$K_RP34tFHstFKC,_i_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_i_vPZqNwk$K_RP34tFHstFKC= -1} } ;
if(_i_vPZqNwk$K_RP34tFHstFKC> -1)ii=_i_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=8) !== "finally_" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } } } } } } ;
if(ii> -1)return new try_(s,i,ii) } ,try_.prototype= {map:function(f) {var r=f(this) ;
return r===true|| !r?this:r} ,start:function() {;
return this.start_} ,end:function() {;
return this.end_} ,length:0,toString:function() {;
return this.input_.substring(this.start_,this.end_) } } ,try_.prototype.constructor=try_,catch_=function(input_,start_,end_) {;
return this.constructor===catch_? (this.input_=input_,this.start_=start_,this.end_=end_,this) :catch_.parse(arguments[0] ,arguments[1] ||0) } ,catch_.parse=function(s,i) {var ii=i;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=5) !== "catch" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=3) !== "pre" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=2) !== "ws" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if(ii> -1) {if( ! /\(/ .test(s.charAt(ii++ ) ) )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=4) !== "cond" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=10) !== "expression" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if(ii> -1) {if( ! /\)/ .test(s.charAt(ii++ ) ) )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=3) !== "rhs" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=8) !== "finally_" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } } } } } } ;
if(ii> -1)return new catch_(s,i,ii) } ,catch_.prototype= {map:function(f) {var r=f(this) ;
return r===true|| !r?this:r} ,start:function() {;
return this.start_} ,end:function() {;
return this.end_} ,length:0,toString:function() {;
return this.input_.substring(this.start_,this.end_) } } ,catch_.prototype.constructor=catch_,finally_=function(input_,start_,end_) {;
return this.constructor===finally_? (this.input_=input_,this.start_=start_,this.end_=end_,this) :finally_.parse(arguments[0] ,arguments[1] ||0) } ,finally_.parse=function(s,i) {var ii=i;
if(ii> -1) {var _j_vPZqNwk$K_RP34tFHstFKC=ii;
if(_j_vPZqNwk$K_RP34tFHstFKC> -1) {if(_j_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_j_vPZqNwk$K_RP34tFHstFKC,_j_vPZqNwk$K_RP34tFHstFKC+=7) !== "finally" )_j_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_j_vPZqNwk$K_RP34tFHstFKC> -1) {if(_j_vPZqNwk$K_RP34tFHstFKC> -1) {if(_j_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_j_vPZqNwk$K_RP34tFHstFKC,_j_vPZqNwk$K_RP34tFHstFKC+=3) !== "lhs" )_j_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_j_vPZqNwk$K_RP34tFHstFKC> -1) {if(_j_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_j_vPZqNwk$K_RP34tFHstFKC,_j_vPZqNwk$K_RP34tFHstFKC+=1) !== ":" )_j_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_j_vPZqNwk$K_RP34tFHstFKC> -1) {if(_j_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_j_vPZqNwk$K_RP34tFHstFKC,_j_vPZqNwk$K_RP34tFHstFKC+=10) !== "statements" )_j_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_j_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_j_vPZqNwk$K_RP34tFHstFKC,_j_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_j_vPZqNwk$K_RP34tFHstFKC= -1} } } } } } ;
if(_j_vPZqNwk$K_RP34tFHstFKC> -1)ii=_j_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=2) !== "ws" )ii= -1} } } } ;
if(ii> -1)return new finally_(s,i,ii) } ,finally_.prototype= {map:function(f) {var r=f(this) ;
return r===true|| !r?this:r} ,start:function() {;
return this.start_} ,end:function() {;
return this.end_} ,length:0,toString:function() {;
return this.input_.substring(this.start_,this.end_) } } ,finally_.prototype.constructor=finally_,ws=function(input_,start_,end_) {;
return this.constructor===ws? (this.input_=input_,this.start_=start_,this.end_=end_,this) :ws.parse(arguments[0] ,arguments[1] ||0) } ,ws.parse=function(s,i) {var ii=i;
if(ii> -1) {var _k_vPZqNwk$K_RP34tFHstFKC=ii;
if(_k_vPZqNwk$K_RP34tFHstFKC> -1) {if(_k_vPZqNwk$K_RP34tFHstFKC> -1) {if(_k_vPZqNwk$K_RP34tFHstFKC> -1) {if(_k_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_k_vPZqNwk$K_RP34tFHstFKC,_k_vPZqNwk$K_RP34tFHstFKC+=7) !== "spacing" )_k_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_k_vPZqNwk$K_RP34tFHstFKC> -1) {if(_k_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_k_vPZqNwk$K_RP34tFHstFKC,_k_vPZqNwk$K_RP34tFHstFKC+=1) !== ":" )_k_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_k_vPZqNwk$K_RP34tFHstFKC> -1) {var _l_vPZqNwk$K_RP34tFHstFKC=_k_vPZqNwk$K_RP34tFHstFKC,_m_vPZqNwk$K_RP34tFHstFKC=0;
if(_l_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[\s]/ .test(s.charAt(_l_vPZqNwk$K_RP34tFHstFKC++ ) ) )_l_vPZqNwk$K_RP34tFHstFKC= -1} ;
while(_l_vPZqNwk$K_RP34tFHstFKC> -1&& ++_m_vPZqNwk$K_RP34tFHstFKC<=Infinity)_k_vPZqNwk$K_RP34tFHstFKC=_l_vPZqNwk$K_RP34tFHstFKC, (if(_l_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[\s]/ .test(s.charAt(_l_vPZqNwk$K_RP34tFHstFKC++ ) ) )_l_vPZqNwk$K_RP34tFHstFKC= -1} ) ;
if(_m_vPZqNwk$K_RP34tFHstFKC<1)_k_vPZqNwk$K_RP34tFHstFKC= -1} } } } ;
if(_k_vPZqNwk$K_RP34tFHstFKC> -1) {if(_k_vPZqNwk$K_RP34tFHstFKC> -1) {if(_k_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_k_vPZqNwk$K_RP34tFHstFKC,_k_vPZqNwk$K_RP34tFHstFKC+=4) !== "rest" )_k_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_k_vPZqNwk$K_RP34tFHstFKC> -1) {if(_k_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_k_vPZqNwk$K_RP34tFHstFKC,_k_vPZqNwk$K_RP34tFHstFKC+=1) !== ":" )_k_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_k_vPZqNwk$K_RP34tFHstFKC> -1) {if(_k_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_k_vPZqNwk$K_RP34tFHstFKC,_k_vPZqNwk$K_RP34tFHstFKC+=2) !== "ws" )_k_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_k_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_k_vPZqNwk$K_RP34tFHstFKC,_k_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_k_vPZqNwk$K_RP34tFHstFKC= -1} } } } } } ;
if(_k_vPZqNwk$K_RP34tFHstFKC> -1)ii=_k_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {var _n_vPZqNwk$K_RP34tFHstFKC=ii;
if(_n_vPZqNwk$K_RP34tFHstFKC> -1) {if(_n_vPZqNwk$K_RP34tFHstFKC> -1) {if(_n_vPZqNwk$K_RP34tFHstFKC> -1) {if(_n_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_n_vPZqNwk$K_RP34tFHstFKC,_n_vPZqNwk$K_RP34tFHstFKC+=7) !== "comment" )_n_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_n_vPZqNwk$K_RP34tFHstFKC> -1) {if(_n_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_n_vPZqNwk$K_RP34tFHstFKC,_n_vPZqNwk$K_RP34tFHstFKC+=1) !== ":" )_n_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_n_vPZqNwk$K_RP34tFHstFKC> -1) {if(_n_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_n_vPZqNwk$K_RP34tFHstFKC,_n_vPZqNwk$K_RP34tFHstFKC+=12) !== "line_comment" )_n_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_n_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_n_vPZqNwk$K_RP34tFHstFKC,_n_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_n_vPZqNwk$K_RP34tFHstFKC= -1} } } } } ;
if(_n_vPZqNwk$K_RP34tFHstFKC> -1) {if(_n_vPZqNwk$K_RP34tFHstFKC> -1) {if(_n_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_n_vPZqNwk$K_RP34tFHstFKC,_n_vPZqNwk$K_RP34tFHstFKC+=4) !== "rest" )_n_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_n_vPZqNwk$K_RP34tFHstFKC> -1) {if(_n_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_n_vPZqNwk$K_RP34tFHstFKC,_n_vPZqNwk$K_RP34tFHstFKC+=1) !== ":" )_n_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_n_vPZqNwk$K_RP34tFHstFKC> -1) {if(_n_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_n_vPZqNwk$K_RP34tFHstFKC,_n_vPZqNwk$K_RP34tFHstFKC+=2) !== "ws" )_n_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_n_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_n_vPZqNwk$K_RP34tFHstFKC,_n_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_n_vPZqNwk$K_RP34tFHstFKC= -1} } } } } } ;
if(_n_vPZqNwk$K_RP34tFHstFKC> -1)ii=_n_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {var _o_vPZqNwk$K_RP34tFHstFKC=ii;
if(_o_vPZqNwk$K_RP34tFHstFKC> -1) {if(_o_vPZqNwk$K_RP34tFHstFKC> -1) {if(_o_vPZqNwk$K_RP34tFHstFKC> -1) {if(_o_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_o_vPZqNwk$K_RP34tFHstFKC,_o_vPZqNwk$K_RP34tFHstFKC+=7) !== "comment" )_o_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_o_vPZqNwk$K_RP34tFHstFKC> -1) {if(_o_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_o_vPZqNwk$K_RP34tFHstFKC,_o_vPZqNwk$K_RP34tFHstFKC+=1) !== ":" )_o_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_o_vPZqNwk$K_RP34tFHstFKC> -1) {if(_o_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_o_vPZqNwk$K_RP34tFHstFKC,_o_vPZqNwk$K_RP34tFHstFKC+=13) !== "block_comment" )_o_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_o_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_o_vPZqNwk$K_RP34tFHstFKC,_o_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_o_vPZqNwk$K_RP34tFHstFKC= -1} } } } } ;
if(_o_vPZqNwk$K_RP34tFHstFKC> -1) {if(_o_vPZqNwk$K_RP34tFHstFKC> -1) {if(_o_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_o_vPZqNwk$K_RP34tFHstFKC,_o_vPZqNwk$K_RP34tFHstFKC+=4) !== "rest" )_o_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_o_vPZqNwk$K_RP34tFHstFKC> -1) {if(_o_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_o_vPZqNwk$K_RP34tFHstFKC,_o_vPZqNwk$K_RP34tFHstFKC+=1) !== ":" )_o_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_o_vPZqNwk$K_RP34tFHstFKC> -1) {if(_o_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_o_vPZqNwk$K_RP34tFHstFKC,_o_vPZqNwk$K_RP34tFHstFKC+=2) !== "ws" )_o_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_o_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_o_vPZqNwk$K_RP34tFHstFKC,_o_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_o_vPZqNwk$K_RP34tFHstFKC= -1} } } } } } ;
if(_o_vPZqNwk$K_RP34tFHstFKC> -1)ii=_o_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {var _p_vPZqNwk$K_RP34tFHstFKC=ii,_q_vPZqNwk$K_RP34tFHstFKC=0;
if(_p_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[\s]/ .test(s.charAt(_p_vPZqNwk$K_RP34tFHstFKC++ ) ) )_p_vPZqNwk$K_RP34tFHstFKC= -1} ;
while(_p_vPZqNwk$K_RP34tFHstFKC> -1&& ++_q_vPZqNwk$K_RP34tFHstFKC<=Infinity)ii=_p_vPZqNwk$K_RP34tFHstFKC, (if(_p_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[\s]/ .test(s.charAt(_p_vPZqNwk$K_RP34tFHstFKC++ ) ) )_p_vPZqNwk$K_RP34tFHstFKC= -1} ) ;
if(_q_vPZqNwk$K_RP34tFHstFKC<0)ii= -1} } } } } } } ;
if(ii> -1)return new ws(s,i,ii) } ,ws.prototype= {map:function(f) {var r=f(this) ;
return r===true|| !r?this:r} ,start:function() {;
return this.start_} ,end:function() {;
return this.end_} ,length:0,toString:function() {;
return this.input_.substring(this.start_,this.end_) } } ,ws.prototype.constructor=ws,line_comment=function(input_,start_,end_) {;
return this.constructor===line_comment? (this.input_=input_,this.start_=start_,this.end_=end_,this) :line_comment.parse(arguments[0] ,arguments[1] ||0) } ,line_comment.parse=function(s,i) {var ii=i;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== "/" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== "/" )ii= -1} ;
if(ii> -1) {var _r_vPZqNwk$K_RP34tFHstFKC=ii,_s_vPZqNwk$K_RP34tFHstFKC=0;
if(_r_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /./ .test(s.charAt(_r_vPZqNwk$K_RP34tFHstFKC++ ) ) )_r_vPZqNwk$K_RP34tFHstFKC= -1} ;
while(_r_vPZqNwk$K_RP34tFHstFKC> -1&& ++_s_vPZqNwk$K_RP34tFHstFKC<=Infinity)ii=_r_vPZqNwk$K_RP34tFHstFKC, (if(_r_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /./ .test(s.charAt(_r_vPZqNwk$K_RP34tFHstFKC++ ) ) )_r_vPZqNwk$K_RP34tFHstFKC= -1} ) ;
if(_s_vPZqNwk$K_RP34tFHstFKC<0)ii= -1} } } ;
if(ii> -1)return new line_comment(s,i,ii) } ,line_comment.prototype= {map:function(f) {var r=f(this) ;
return r===true|| !r?this:r} ,start:function() {;
return this.start_} ,end:function() {;
return this.end_} ,length:0,toString:function() {;
return this.input_.substring(this.start_,this.end_) } } ,line_comment.prototype.constructor=line_comment,block_comment=function(input_,start_,end_) {;
return this.constructor===block_comment? (this.input_=input_,this.start_=start_,this.end_=end_,this) :block_comment.parse(arguments[0] ,arguments[1] ||0) } ,block_comment.parse=function(s,i) {var ii=i;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== "/" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if( ! /\*/ .test(s.charAt(ii++ ) ) )ii= -1} ;
if(ii> -1) {if(ii> -1) {var _t_vPZqNwk$K_RP34tFHstFKC=ii,_u_vPZqNwk$K_RP34tFHstFKC=0;
if(_t_vPZqNwk$K_RP34tFHstFKC> -1) {if(_t_vPZqNwk$K_RP34tFHstFKC> -1) {var _v_vPZqNwk$K_RP34tFHstFKC=_t_vPZqNwk$K_RP34tFHstFKC;
if(_v_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[^*]/ .test(s.charAt(_v_vPZqNwk$K_RP34tFHstFKC++ ) ) )_v_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_v_vPZqNwk$K_RP34tFHstFKC> -1)_t_vPZqNwk$K_RP34tFHstFKC=_v_vPZqNwk$K_RP34tFHstFKC;
else{if(_t_vPZqNwk$K_RP34tFHstFKC> -1) {if(_t_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /\*/ .test(s.charAt(_t_vPZqNwk$K_RP34tFHstFKC++ ) ) )_t_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_t_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[^\/]/ .test(s.charAt(_t_vPZqNwk$K_RP34tFHstFKC++ ) ) )_t_vPZqNwk$K_RP34tFHstFKC= -1} } } } } ;
while(_t_vPZqNwk$K_RP34tFHstFKC> -1&& ++_u_vPZqNwk$K_RP34tFHstFKC<=Infinity)ii=_t_vPZqNwk$K_RP34tFHstFKC, (if(_t_vPZqNwk$K_RP34tFHstFKC> -1) {if(_t_vPZqNwk$K_RP34tFHstFKC> -1) {var _v_vPZqNwk$K_RP34tFHstFKC=_t_vPZqNwk$K_RP34tFHstFKC;
if(_v_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[^*]/ .test(s.charAt(_v_vPZqNwk$K_RP34tFHstFKC++ ) ) )_v_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_v_vPZqNwk$K_RP34tFHstFKC> -1)_t_vPZqNwk$K_RP34tFHstFKC=_v_vPZqNwk$K_RP34tFHstFKC;
else{if(_t_vPZqNwk$K_RP34tFHstFKC> -1) {if(_t_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /\*/ .test(s.charAt(_t_vPZqNwk$K_RP34tFHstFKC++ ) ) )_t_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_t_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[^\/]/ .test(s.charAt(_t_vPZqNwk$K_RP34tFHstFKC++ ) ) )_t_vPZqNwk$K_RP34tFHstFKC= -1} } } } } ) ;
if(_u_vPZqNwk$K_RP34tFHstFKC<0)ii= -1} ;
if(ii> -1) {if(ii> -1) {if( ! /\*/ .test(s.charAt(ii++ ) ) )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "/" )ii= -1} } } } } ;
if(ii> -1)return new block_comment(s,i,ii) } ,block_comment.prototype= {map:function(f) {var r=f(this) ;
return r===true|| !r?this:r} ,start:function() {;
return this.start_} ,end:function() {;
return this.end_} ,length:0,toString:function() {;
return this.input_.substring(this.start_,this.end_) } } ,block_comment.prototype.constructor=block_comment,expressions=function(input_,start_,end_) {;
return this.constructor===expressions? (this.input_=input_,this.start_=start_,this.end_=end_,this) :expressions.parse(arguments[0] ,arguments[1] ||0) } ,expressions.parse=function(s,i) {var ii=i;
if(ii> -1) {var _w_vPZqNwk$K_RP34tFHstFKC=ii;
if(_w_vPZqNwk$K_RP34tFHstFKC> -1) {if(_w_vPZqNwk$K_RP34tFHstFKC> -1) {if(_w_vPZqNwk$K_RP34tFHstFKC> -1) {if(_w_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_w_vPZqNwk$K_RP34tFHstFKC,_w_vPZqNwk$K_RP34tFHstFKC+=3) !== "lhs" )_w_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_w_vPZqNwk$K_RP34tFHstFKC> -1) {if(_w_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_w_vPZqNwk$K_RP34tFHstFKC,_w_vPZqNwk$K_RP34tFHstFKC+=1) !== ":" )_w_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_w_vPZqNwk$K_RP34tFHstFKC> -1) {if(_w_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_w_vPZqNwk$K_RP34tFHstFKC,_w_vPZqNwk$K_RP34tFHstFKC+=10) !== "expression" )_w_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_w_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_w_vPZqNwk$K_RP34tFHstFKC,_w_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_w_vPZqNwk$K_RP34tFHstFKC= -1} } } } } ;
if(_w_vPZqNwk$K_RP34tFHstFKC> -1) {if(_w_vPZqNwk$K_RP34tFHstFKC> -1) {if(_w_vPZqNwk$K_RP34tFHstFKC> -1) {if(_w_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_w_vPZqNwk$K_RP34tFHstFKC,_w_vPZqNwk$K_RP34tFHstFKC+=2) !== "op" )_w_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_w_vPZqNwk$K_RP34tFHstFKC> -1) {if(_w_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_w_vPZqNwk$K_RP34tFHstFKC,_w_vPZqNwk$K_RP34tFHstFKC+=1) !== ":" )_w_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_w_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_w_vPZqNwk$K_RP34tFHstFKC,_w_vPZqNwk$K_RP34tFHstFKC+=1) !== "," )_w_vPZqNwk$K_RP34tFHstFKC= -1} } } } ;
if(_w_vPZqNwk$K_RP34tFHstFKC> -1) {if(_w_vPZqNwk$K_RP34tFHstFKC> -1) {if(_w_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_w_vPZqNwk$K_RP34tFHstFKC,_w_vPZqNwk$K_RP34tFHstFKC+=3) !== "rhs" )_w_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_w_vPZqNwk$K_RP34tFHstFKC> -1) {if(_w_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_w_vPZqNwk$K_RP34tFHstFKC,_w_vPZqNwk$K_RP34tFHstFKC+=1) !== ":" )_w_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_w_vPZqNwk$K_RP34tFHstFKC> -1) {if(_w_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_w_vPZqNwk$K_RP34tFHstFKC,_w_vPZqNwk$K_RP34tFHstFKC+=11) !== "expressions" )_w_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_w_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_w_vPZqNwk$K_RP34tFHstFKC,_w_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_w_vPZqNwk$K_RP34tFHstFKC= -1} } } } } } } ;
if(_w_vPZqNwk$K_RP34tFHstFKC> -1)ii=_w_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=10) !== "expression" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } ;
if(ii> -1)return new expressions(s,i,ii) } ,expressions.prototype= {map:function(f) {var r=f(this) ;
return r===true|| !r?this:r} ,start:function() {;
return this.start_} ,end:function() {;
return this.end_} ,length:0,toString:function() {;
return this.input_.substring(this.start_,this.end_) } } ,expressions.prototype.constructor=expressions,expression=function(input_,start_,end_) {;
return this.constructor===expression? (this.input_=input_,this.start_=start_,this.end_=end_,this) :expression.parse(arguments[0] ,arguments[1] ||0) } ,expression.parse=function(s,i) {var ii=i;
if(ii> -1) {var _x_vPZqNwk$K_RP34tFHstFKC=ii;
if(_x_vPZqNwk$K_RP34tFHstFKC> -1) {if(_x_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_x_vPZqNwk$K_RP34tFHstFKC,_x_vPZqNwk$K_RP34tFHstFKC+=7) !== "literal" )_x_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_x_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_x_vPZqNwk$K_RP34tFHstFKC,_x_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_x_vPZqNwk$K_RP34tFHstFKC= -1} } ;
if(_x_vPZqNwk$K_RP34tFHstFKC> -1)ii=_x_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {var _y_vPZqNwk$K_RP34tFHstFKC=ii;
if(_y_vPZqNwk$K_RP34tFHstFKC> -1) {if(_y_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_y_vPZqNwk$K_RP34tFHstFKC,_y_vPZqNwk$K_RP34tFHstFKC+=10) !== "identifier" )_y_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_y_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_y_vPZqNwk$K_RP34tFHstFKC,_y_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_y_vPZqNwk$K_RP34tFHstFKC= -1} } ;
if(_y_vPZqNwk$K_RP34tFHstFKC> -1)ii=_y_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {var _z_vPZqNwk$K_RP34tFHstFKC=ii;
if(_z_vPZqNwk$K_RP34tFHstFKC> -1) {if(_z_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_z_vPZqNwk$K_RP34tFHstFKC,_z_vPZqNwk$K_RP34tFHstFKC+=5) !== "group" )_z_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_z_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_z_vPZqNwk$K_RP34tFHstFKC,_z_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_z_vPZqNwk$K_RP34tFHstFKC= -1} } ;
if(_z_vPZqNwk$K_RP34tFHstFKC> -1)ii=_z_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {var _10_vPZqNwk$K_RP34tFHstFKC=ii;
if(_10_vPZqNwk$K_RP34tFHstFKC> -1) {if(_10_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_10_vPZqNwk$K_RP34tFHstFKC,_10_vPZqNwk$K_RP34tFHstFKC+=5) !== "unary" )_10_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_10_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_10_vPZqNwk$K_RP34tFHstFKC,_10_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_10_vPZqNwk$K_RP34tFHstFKC= -1} } ;
if(_10_vPZqNwk$K_RP34tFHstFKC> -1)ii=_10_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=6) !== "binary" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } } } } } } ;
if(ii> -1)return new expression(s,i,ii) } ,expression.prototype= {map:function(f) {var r=f(this) ;
return r===true|| !r?this:r} ,start:function() {;
return this.start_} ,end:function() {;
return this.end_} ,length:0,toString:function() {;
return this.input_.substring(this.start_,this.end_) } } ,expression.prototype.constructor=expression,literal=function(input_,start_,end_) {;
return this.constructor===literal? (this.input_=input_,this.start_=start_,this.end_=end_,this) :literal.parse(arguments[0] ,arguments[1] ||0) } ,literal.parse=function(s,i) {var ii=i;
if(ii> -1) {var _11_vPZqNwk$K_RP34tFHstFKC=ii;
if(_11_vPZqNwk$K_RP34tFHstFKC> -1) {if(_11_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_11_vPZqNwk$K_RP34tFHstFKC,_11_vPZqNwk$K_RP34tFHstFKC+=7) !== "dstring" )_11_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_11_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_11_vPZqNwk$K_RP34tFHstFKC,_11_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_11_vPZqNwk$K_RP34tFHstFKC= -1} } ;
if(_11_vPZqNwk$K_RP34tFHstFKC> -1)ii=_11_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {var _12_vPZqNwk$K_RP34tFHstFKC=ii;
if(_12_vPZqNwk$K_RP34tFHstFKC> -1) {if(_12_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_12_vPZqNwk$K_RP34tFHstFKC,_12_vPZqNwk$K_RP34tFHstFKC+=7) !== "sstring" )_12_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_12_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_12_vPZqNwk$K_RP34tFHstFKC,_12_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_12_vPZqNwk$K_RP34tFHstFKC= -1} } ;
if(_12_vPZqNwk$K_RP34tFHstFKC> -1)ii=_12_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {var _13_vPZqNwk$K_RP34tFHstFKC=ii;
if(_13_vPZqNwk$K_RP34tFHstFKC> -1) {if(_13_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_13_vPZqNwk$K_RP34tFHstFKC,_13_vPZqNwk$K_RP34tFHstFKC+=6) !== "number" )_13_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_13_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_13_vPZqNwk$K_RP34tFHstFKC,_13_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_13_vPZqNwk$K_RP34tFHstFKC= -1} } ;
if(_13_vPZqNwk$K_RP34tFHstFKC> -1)ii=_13_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {var _14_vPZqNwk$K_RP34tFHstFKC=ii;
if(_14_vPZqNwk$K_RP34tFHstFKC> -1) {if(_14_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_14_vPZqNwk$K_RP34tFHstFKC,_14_vPZqNwk$K_RP34tFHstFKC+=6) !== "regexp" )_14_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_14_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_14_vPZqNwk$K_RP34tFHstFKC,_14_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_14_vPZqNwk$K_RP34tFHstFKC= -1} } ;
if(_14_vPZqNwk$K_RP34tFHstFKC> -1)ii=_14_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {var _15_vPZqNwk$K_RP34tFHstFKC=ii;
if(_15_vPZqNwk$K_RP34tFHstFKC> -1) {if(_15_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_15_vPZqNwk$K_RP34tFHstFKC,_15_vPZqNwk$K_RP34tFHstFKC+=5) !== "array" )_15_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_15_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_15_vPZqNwk$K_RP34tFHstFKC,_15_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_15_vPZqNwk$K_RP34tFHstFKC= -1} } ;
if(_15_vPZqNwk$K_RP34tFHstFKC> -1)ii=_15_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=6) !== "object" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } } } } } } } } ;
if(ii> -1)return new literal(s,i,ii) } ,literal.prototype= {map:function(f) {var r=f(this) ;
return r===true|| !r?this:r} ,start:function() {;
return this.start_} ,end:function() {;
return this.end_} ,length:0,toString:function() {;
return this.input_.substring(this.start_,this.end_) } } ,literal.prototype.constructor=literal,dstring=function(input_,start_,end_) {;
return this.constructor===dstring? (this.input_=input_,this.start_=start_,this.end_=end_,this) :dstring.parse(arguments[0] ,arguments[1] ||0) } ,dstring.parse=function(s,i) {var ii=i;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== "\"" )ii= -1} ;
if(ii> -1) {if(ii> -1) {var _16_vPZqNwk$K_RP34tFHstFKC=ii,_17_vPZqNwk$K_RP34tFHstFKC=0;
if(_16_vPZqNwk$K_RP34tFHstFKC> -1) {if(_16_vPZqNwk$K_RP34tFHstFKC> -1) {var _18_vPZqNwk$K_RP34tFHstFKC=_16_vPZqNwk$K_RP34tFHstFKC;
if(_18_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[^\\"]/ .test(s.charAt(_18_vPZqNwk$K_RP34tFHstFKC++ ) ) )_18_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_18_vPZqNwk$K_RP34tFHstFKC> -1)_16_vPZqNwk$K_RP34tFHstFKC=_18_vPZqNwk$K_RP34tFHstFKC;
else{if(_16_vPZqNwk$K_RP34tFHstFKC> -1) {if(_16_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /\\/ .test(s.charAt(_16_vPZqNwk$K_RP34tFHstFKC++ ) ) )_16_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_16_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /./ .test(s.charAt(_16_vPZqNwk$K_RP34tFHstFKC++ ) ) )_16_vPZqNwk$K_RP34tFHstFKC= -1} } } } } ;
while(_16_vPZqNwk$K_RP34tFHstFKC> -1&& ++_17_vPZqNwk$K_RP34tFHstFKC<=Infinity)ii=_16_vPZqNwk$K_RP34tFHstFKC, (if(_16_vPZqNwk$K_RP34tFHstFKC> -1) {if(_16_vPZqNwk$K_RP34tFHstFKC> -1) {var _18_vPZqNwk$K_RP34tFHstFKC=_16_vPZqNwk$K_RP34tFHstFKC;
if(_18_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[^\\"]/ .test(s.charAt(_18_vPZqNwk$K_RP34tFHstFKC++ ) ) )_18_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_18_vPZqNwk$K_RP34tFHstFKC> -1)_16_vPZqNwk$K_RP34tFHstFKC=_18_vPZqNwk$K_RP34tFHstFKC;
else{if(_16_vPZqNwk$K_RP34tFHstFKC> -1) {if(_16_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /\\/ .test(s.charAt(_16_vPZqNwk$K_RP34tFHstFKC++ ) ) )_16_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_16_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /./ .test(s.charAt(_16_vPZqNwk$K_RP34tFHstFKC++ ) ) )_16_vPZqNwk$K_RP34tFHstFKC= -1} } } } } ) ;
if(_17_vPZqNwk$K_RP34tFHstFKC<0)ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "\"" )ii= -1} } } ;
if(ii> -1)return new dstring(s,i,ii) } ,dstring.prototype= {map:function(f) {var r=f(this) ;
return r===true|| !r?this:r} ,start:function() {;
return this.start_} ,end:function() {;
return this.end_} ,length:0,toString:function() {;
return this.input_.substring(this.start_,this.end_) } } ,dstring.prototype.constructor=dstring,sstring=function(input_,start_,end_) {;
return this.constructor===sstring? (this.input_=input_,this.start_=start_,this.end_=end_,this) :sstring.parse(arguments[0] ,arguments[1] ||0) } ,sstring.parse=function(s,i) {var ii=i;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== "'" )ii= -1} ;
if(ii> -1) {if(ii> -1) {var _19_vPZqNwk$K_RP34tFHstFKC=ii,_1a_vPZqNwk$K_RP34tFHstFKC=0;
if(_19_vPZqNwk$K_RP34tFHstFKC> -1) {if(_19_vPZqNwk$K_RP34tFHstFKC> -1) {var _1b_vPZqNwk$K_RP34tFHstFKC=_19_vPZqNwk$K_RP34tFHstFKC;
if(_1b_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[^\\']/ .test(s.charAt(_1b_vPZqNwk$K_RP34tFHstFKC++ ) ) )_1b_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_1b_vPZqNwk$K_RP34tFHstFKC> -1)_19_vPZqNwk$K_RP34tFHstFKC=_1b_vPZqNwk$K_RP34tFHstFKC;
else{if(_19_vPZqNwk$K_RP34tFHstFKC> -1) {if(_19_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /\\/ .test(s.charAt(_19_vPZqNwk$K_RP34tFHstFKC++ ) ) )_19_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_19_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /./ .test(s.charAt(_19_vPZqNwk$K_RP34tFHstFKC++ ) ) )_19_vPZqNwk$K_RP34tFHstFKC= -1} } } } } ;
while(_19_vPZqNwk$K_RP34tFHstFKC> -1&& ++_1a_vPZqNwk$K_RP34tFHstFKC<=Infinity)ii=_19_vPZqNwk$K_RP34tFHstFKC, (if(_19_vPZqNwk$K_RP34tFHstFKC> -1) {if(_19_vPZqNwk$K_RP34tFHstFKC> -1) {var _1b_vPZqNwk$K_RP34tFHstFKC=_19_vPZqNwk$K_RP34tFHstFKC;
if(_1b_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[^\\']/ .test(s.charAt(_1b_vPZqNwk$K_RP34tFHstFKC++ ) ) )_1b_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_1b_vPZqNwk$K_RP34tFHstFKC> -1)_19_vPZqNwk$K_RP34tFHstFKC=_1b_vPZqNwk$K_RP34tFHstFKC;
else{if(_19_vPZqNwk$K_RP34tFHstFKC> -1) {if(_19_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /\\/ .test(s.charAt(_19_vPZqNwk$K_RP34tFHstFKC++ ) ) )_19_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_19_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /./ .test(s.charAt(_19_vPZqNwk$K_RP34tFHstFKC++ ) ) )_19_vPZqNwk$K_RP34tFHstFKC= -1} } } } } ) ;
if(_1a_vPZqNwk$K_RP34tFHstFKC<0)ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "\"" )ii= -1} } } ;
if(ii> -1)return new sstring(s,i,ii) } ,sstring.prototype= {map:function(f) {var r=f(this) ;
return r===true|| !r?this:r} ,start:function() {;
return this.start_} ,end:function() {;
return this.end_} ,length:0,toString:function() {;
return this.input_.substring(this.start_,this.end_) } } ,sstring.prototype.constructor=sstring,number=function(input_,start_,end_) {;
return this.constructor===number? (this.input_=input_,this.start_=start_,this.end_=end_,this) :number.parse(arguments[0] ,arguments[1] ||0) } ,number.parse=function(s,i) {var ii=i;
if(ii> -1) {var _1c_vPZqNwk$K_RP34tFHstFKC=ii;
if(_1c_vPZqNwk$K_RP34tFHstFKC> -1) {if(_1c_vPZqNwk$K_RP34tFHstFKC> -1) {var _1d_vPZqNwk$K_RP34tFHstFKC=_1c_vPZqNwk$K_RP34tFHstFKC,_1e_vPZqNwk$K_RP34tFHstFKC=0;
if(_1d_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_1d_vPZqNwk$K_RP34tFHstFKC,_1d_vPZqNwk$K_RP34tFHstFKC+=1) !== "-" )_1d_vPZqNwk$K_RP34tFHstFKC= -1} ;
while(_1d_vPZqNwk$K_RP34tFHstFKC> -1&& ++_1e_vPZqNwk$K_RP34tFHstFKC<=1)_1c_vPZqNwk$K_RP34tFHstFKC=_1d_vPZqNwk$K_RP34tFHstFKC, (if(_1d_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_1d_vPZqNwk$K_RP34tFHstFKC,_1d_vPZqNwk$K_RP34tFHstFKC+=1) !== "-" )_1d_vPZqNwk$K_RP34tFHstFKC= -1} ) ;
if(_1e_vPZqNwk$K_RP34tFHstFKC<0)_1c_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_1c_vPZqNwk$K_RP34tFHstFKC> -1) {if(_1c_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_1c_vPZqNwk$K_RP34tFHstFKC,_1c_vPZqNwk$K_RP34tFHstFKC+=2) !== "0x" )_1c_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_1c_vPZqNwk$K_RP34tFHstFKC> -1) {var _1f_vPZqNwk$K_RP34tFHstFKC=_1c_vPZqNwk$K_RP34tFHstFKC,_1g_vPZqNwk$K_RP34tFHstFKC=0;
if(_1f_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[0-9a-fA-F]/ .test(s.charAt(_1f_vPZqNwk$K_RP34tFHstFKC++ ) ) )_1f_vPZqNwk$K_RP34tFHstFKC= -1} ;
while(_1f_vPZqNwk$K_RP34tFHstFKC> -1&& ++_1g_vPZqNwk$K_RP34tFHstFKC<=Infinity)_1c_vPZqNwk$K_RP34tFHstFKC=_1f_vPZqNwk$K_RP34tFHstFKC, (if(_1f_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[0-9a-fA-F]/ .test(s.charAt(_1f_vPZqNwk$K_RP34tFHstFKC++ ) ) )_1f_vPZqNwk$K_RP34tFHstFKC= -1} ) ;
if(_1g_vPZqNwk$K_RP34tFHstFKC<0)_1c_vPZqNwk$K_RP34tFHstFKC= -1} } } ;
if(_1c_vPZqNwk$K_RP34tFHstFKC> -1)ii=_1c_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {var _1h_vPZqNwk$K_RP34tFHstFKC=ii;
if(_1h_vPZqNwk$K_RP34tFHstFKC> -1) {if(_1h_vPZqNwk$K_RP34tFHstFKC> -1) {var _1i_vPZqNwk$K_RP34tFHstFKC=_1h_vPZqNwk$K_RP34tFHstFKC,_1j_vPZqNwk$K_RP34tFHstFKC=0;
if(_1i_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_1i_vPZqNwk$K_RP34tFHstFKC,_1i_vPZqNwk$K_RP34tFHstFKC+=1) !== "-" )_1i_vPZqNwk$K_RP34tFHstFKC= -1} ;
while(_1i_vPZqNwk$K_RP34tFHstFKC> -1&& ++_1j_vPZqNwk$K_RP34tFHstFKC<=1)_1h_vPZqNwk$K_RP34tFHstFKC=_1i_vPZqNwk$K_RP34tFHstFKC, (if(_1i_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_1i_vPZqNwk$K_RP34tFHstFKC,_1i_vPZqNwk$K_RP34tFHstFKC+=1) !== "-" )_1i_vPZqNwk$K_RP34tFHstFKC= -1} ) ;
if(_1j_vPZqNwk$K_RP34tFHstFKC<0)_1h_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_1h_vPZqNwk$K_RP34tFHstFKC> -1) {if(_1h_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_1h_vPZqNwk$K_RP34tFHstFKC,_1h_vPZqNwk$K_RP34tFHstFKC+=1) !== "0" )_1h_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_1h_vPZqNwk$K_RP34tFHstFKC> -1) {var _1k_vPZqNwk$K_RP34tFHstFKC=_1h_vPZqNwk$K_RP34tFHstFKC,_1l_vPZqNwk$K_RP34tFHstFKC=0;
if(_1k_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[0-7]/ .test(s.charAt(_1k_vPZqNwk$K_RP34tFHstFKC++ ) ) )_1k_vPZqNwk$K_RP34tFHstFKC= -1} ;
while(_1k_vPZqNwk$K_RP34tFHstFKC> -1&& ++_1l_vPZqNwk$K_RP34tFHstFKC<=Infinity)_1h_vPZqNwk$K_RP34tFHstFKC=_1k_vPZqNwk$K_RP34tFHstFKC, (if(_1k_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[0-7]/ .test(s.charAt(_1k_vPZqNwk$K_RP34tFHstFKC++ ) ) )_1k_vPZqNwk$K_RP34tFHstFKC= -1} ) ;
if(_1l_vPZqNwk$K_RP34tFHstFKC<0)_1h_vPZqNwk$K_RP34tFHstFKC= -1} } } ;
if(_1h_vPZqNwk$K_RP34tFHstFKC> -1)ii=_1h_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {var _1m_vPZqNwk$K_RP34tFHstFKC=ii;
if(_1m_vPZqNwk$K_RP34tFHstFKC> -1) {if(_1m_vPZqNwk$K_RP34tFHstFKC> -1) {var _1n_vPZqNwk$K_RP34tFHstFKC=_1m_vPZqNwk$K_RP34tFHstFKC,_1o_vPZqNwk$K_RP34tFHstFKC=0;
if(_1n_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_1n_vPZqNwk$K_RP34tFHstFKC,_1n_vPZqNwk$K_RP34tFHstFKC+=1) !== "-" )_1n_vPZqNwk$K_RP34tFHstFKC= -1} ;
while(_1n_vPZqNwk$K_RP34tFHstFKC> -1&& ++_1o_vPZqNwk$K_RP34tFHstFKC<=1)_1m_vPZqNwk$K_RP34tFHstFKC=_1n_vPZqNwk$K_RP34tFHstFKC, (if(_1n_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_1n_vPZqNwk$K_RP34tFHstFKC,_1n_vPZqNwk$K_RP34tFHstFKC+=1) !== "-" )_1n_vPZqNwk$K_RP34tFHstFKC= -1} ) ;
if(_1o_vPZqNwk$K_RP34tFHstFKC<0)_1m_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_1m_vPZqNwk$K_RP34tFHstFKC> -1) {if(_1m_vPZqNwk$K_RP34tFHstFKC> -1) {var _1p_vPZqNwk$K_RP34tFHstFKC=_1m_vPZqNwk$K_RP34tFHstFKC,_1q_vPZqNwk$K_RP34tFHstFKC=0;
if(_1p_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[0-9]/ .test(s.charAt(_1p_vPZqNwk$K_RP34tFHstFKC++ ) ) )_1p_vPZqNwk$K_RP34tFHstFKC= -1} ;
while(_1p_vPZqNwk$K_RP34tFHstFKC> -1&& ++_1q_vPZqNwk$K_RP34tFHstFKC<=Infinity)_1m_vPZqNwk$K_RP34tFHstFKC=_1p_vPZqNwk$K_RP34tFHstFKC, (if(_1p_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[0-9]/ .test(s.charAt(_1p_vPZqNwk$K_RP34tFHstFKC++ ) ) )_1p_vPZqNwk$K_RP34tFHstFKC= -1} ) ;
if(_1q_vPZqNwk$K_RP34tFHstFKC<0)_1m_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_1m_vPZqNwk$K_RP34tFHstFKC> -1) {if(_1m_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /\./ .test(s.charAt(_1m_vPZqNwk$K_RP34tFHstFKC++ ) ) )_1m_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_1m_vPZqNwk$K_RP34tFHstFKC> -1) {if(_1m_vPZqNwk$K_RP34tFHstFKC> -1) {var _1r_vPZqNwk$K_RP34tFHstFKC=_1m_vPZqNwk$K_RP34tFHstFKC,_1s_vPZqNwk$K_RP34tFHstFKC=0;
if(_1r_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[0-9]/ .test(s.charAt(_1r_vPZqNwk$K_RP34tFHstFKC++ ) ) )_1r_vPZqNwk$K_RP34tFHstFKC= -1} ;
while(_1r_vPZqNwk$K_RP34tFHstFKC> -1&& ++_1s_vPZqNwk$K_RP34tFHstFKC<=Infinity)_1m_vPZqNwk$K_RP34tFHstFKC=_1r_vPZqNwk$K_RP34tFHstFKC, (if(_1r_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[0-9]/ .test(s.charAt(_1r_vPZqNwk$K_RP34tFHstFKC++ ) ) )_1r_vPZqNwk$K_RP34tFHstFKC= -1} ) ;
if(_1s_vPZqNwk$K_RP34tFHstFKC<0)_1m_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_1m_vPZqNwk$K_RP34tFHstFKC> -1) {var _1t_vPZqNwk$K_RP34tFHstFKC=_1m_vPZqNwk$K_RP34tFHstFKC,_1u_vPZqNwk$K_RP34tFHstFKC=0;
if(_1t_vPZqNwk$K_RP34tFHstFKC> -1) {if(_1t_vPZqNwk$K_RP34tFHstFKC> -1) {if(_1t_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[eE]/ .test(s.charAt(_1t_vPZqNwk$K_RP34tFHstFKC++ ) ) )_1t_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_1t_vPZqNwk$K_RP34tFHstFKC> -1) {if(_1t_vPZqNwk$K_RP34tFHstFKC> -1) {var _1v_vPZqNwk$K_RP34tFHstFKC=_1t_vPZqNwk$K_RP34tFHstFKC,_1w_vPZqNwk$K_RP34tFHstFKC=0;
if(_1v_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[-+]/ .test(s.charAt(_1v_vPZqNwk$K_RP34tFHstFKC++ ) ) )_1v_vPZqNwk$K_RP34tFHstFKC= -1} ;
while(_1v_vPZqNwk$K_RP34tFHstFKC> -1&& ++_1w_vPZqNwk$K_RP34tFHstFKC<=1)_1t_vPZqNwk$K_RP34tFHstFKC=_1v_vPZqNwk$K_RP34tFHstFKC, (if(_1v_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[-+]/ .test(s.charAt(_1v_vPZqNwk$K_RP34tFHstFKC++ ) ) )_1v_vPZqNwk$K_RP34tFHstFKC= -1} ) ;
if(_1w_vPZqNwk$K_RP34tFHstFKC<0)_1t_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_1t_vPZqNwk$K_RP34tFHstFKC> -1) {var _1x_vPZqNwk$K_RP34tFHstFKC=_1t_vPZqNwk$K_RP34tFHstFKC,_1y_vPZqNwk$K_RP34tFHstFKC=0;
if(_1x_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[0-9]/ .test(s.charAt(_1x_vPZqNwk$K_RP34tFHstFKC++ ) ) )_1x_vPZqNwk$K_RP34tFHstFKC= -1} ;
while(_1x_vPZqNwk$K_RP34tFHstFKC> -1&& ++_1y_vPZqNwk$K_RP34tFHstFKC<=Infinity)_1t_vPZqNwk$K_RP34tFHstFKC=_1x_vPZqNwk$K_RP34tFHstFKC, (if(_1x_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[0-9]/ .test(s.charAt(_1x_vPZqNwk$K_RP34tFHstFKC++ ) ) )_1x_vPZqNwk$K_RP34tFHstFKC= -1} ) ;
if(_1y_vPZqNwk$K_RP34tFHstFKC<1)_1t_vPZqNwk$K_RP34tFHstFKC= -1} } } } ;
while(_1t_vPZqNwk$K_RP34tFHstFKC> -1&& ++_1u_vPZqNwk$K_RP34tFHstFKC<=1)_1m_vPZqNwk$K_RP34tFHstFKC=_1t_vPZqNwk$K_RP34tFHstFKC, (if(_1t_vPZqNwk$K_RP34tFHstFKC> -1) {if(_1t_vPZqNwk$K_RP34tFHstFKC> -1) {if(_1t_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[eE]/ .test(s.charAt(_1t_vPZqNwk$K_RP34tFHstFKC++ ) ) )_1t_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_1t_vPZqNwk$K_RP34tFHstFKC> -1) {if(_1t_vPZqNwk$K_RP34tFHstFKC> -1) {var _1v_vPZqNwk$K_RP34tFHstFKC=_1t_vPZqNwk$K_RP34tFHstFKC,_1w_vPZqNwk$K_RP34tFHstFKC=0;
if(_1v_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[-+]/ .test(s.charAt(_1v_vPZqNwk$K_RP34tFHstFKC++ ) ) )_1v_vPZqNwk$K_RP34tFHstFKC= -1} ;
while(_1v_vPZqNwk$K_RP34tFHstFKC> -1&& ++_1w_vPZqNwk$K_RP34tFHstFKC<=1)_1t_vPZqNwk$K_RP34tFHstFKC=_1v_vPZqNwk$K_RP34tFHstFKC, (if(_1v_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[-+]/ .test(s.charAt(_1v_vPZqNwk$K_RP34tFHstFKC++ ) ) )_1v_vPZqNwk$K_RP34tFHstFKC= -1} ) ;
if(_1w_vPZqNwk$K_RP34tFHstFKC<0)_1t_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_1t_vPZqNwk$K_RP34tFHstFKC> -1) {var _1x_vPZqNwk$K_RP34tFHstFKC=_1t_vPZqNwk$K_RP34tFHstFKC,_1y_vPZqNwk$K_RP34tFHstFKC=0;
if(_1x_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[0-9]/ .test(s.charAt(_1x_vPZqNwk$K_RP34tFHstFKC++ ) ) )_1x_vPZqNwk$K_RP34tFHstFKC= -1} ;
while(_1x_vPZqNwk$K_RP34tFHstFKC> -1&& ++_1y_vPZqNwk$K_RP34tFHstFKC<=Infinity)_1t_vPZqNwk$K_RP34tFHstFKC=_1x_vPZqNwk$K_RP34tFHstFKC, (if(_1x_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[0-9]/ .test(s.charAt(_1x_vPZqNwk$K_RP34tFHstFKC++ ) ) )_1x_vPZqNwk$K_RP34tFHstFKC= -1} ) ;
if(_1y_vPZqNwk$K_RP34tFHstFKC<1)_1t_vPZqNwk$K_RP34tFHstFKC= -1} } } } ) ;
if(_1u_vPZqNwk$K_RP34tFHstFKC<0)_1m_vPZqNwk$K_RP34tFHstFKC= -1} } } } } ;
if(_1m_vPZqNwk$K_RP34tFHstFKC> -1)ii=_1m_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {if(ii> -1) {var _1z_vPZqNwk$K_RP34tFHstFKC=ii,_20_vPZqNwk$K_RP34tFHstFKC=0;
if(_1z_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_1z_vPZqNwk$K_RP34tFHstFKC,_1z_vPZqNwk$K_RP34tFHstFKC+=1) !== "-" )_1z_vPZqNwk$K_RP34tFHstFKC= -1} ;
while(_1z_vPZqNwk$K_RP34tFHstFKC> -1&& ++_20_vPZqNwk$K_RP34tFHstFKC<=1)ii=_1z_vPZqNwk$K_RP34tFHstFKC, (if(_1z_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_1z_vPZqNwk$K_RP34tFHstFKC,_1z_vPZqNwk$K_RP34tFHstFKC+=1) !== "-" )_1z_vPZqNwk$K_RP34tFHstFKC= -1} ) ;
if(_20_vPZqNwk$K_RP34tFHstFKC<0)ii= -1} ;
if(ii> -1) {if(ii> -1) {var _21_vPZqNwk$K_RP34tFHstFKC=ii,_22_vPZqNwk$K_RP34tFHstFKC=0;
if(_21_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[0-9]/ .test(s.charAt(_21_vPZqNwk$K_RP34tFHstFKC++ ) ) )_21_vPZqNwk$K_RP34tFHstFKC= -1} ;
while(_21_vPZqNwk$K_RP34tFHstFKC> -1&& ++_22_vPZqNwk$K_RP34tFHstFKC<=Infinity)ii=_21_vPZqNwk$K_RP34tFHstFKC, (if(_21_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[0-9]/ .test(s.charAt(_21_vPZqNwk$K_RP34tFHstFKC++ ) ) )_21_vPZqNwk$K_RP34tFHstFKC= -1} ) ;
if(_22_vPZqNwk$K_RP34tFHstFKC<1)ii= -1} ;
if(ii> -1) {var _23_vPZqNwk$K_RP34tFHstFKC=ii,_24_vPZqNwk$K_RP34tFHstFKC=0;
if(_23_vPZqNwk$K_RP34tFHstFKC> -1) {if(_23_vPZqNwk$K_RP34tFHstFKC> -1) {if(_23_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /\./ .test(s.charAt(_23_vPZqNwk$K_RP34tFHstFKC++ ) ) )_23_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_23_vPZqNwk$K_RP34tFHstFKC> -1) {if(_23_vPZqNwk$K_RP34tFHstFKC> -1) {var _25_vPZqNwk$K_RP34tFHstFKC=_23_vPZqNwk$K_RP34tFHstFKC,_26_vPZqNwk$K_RP34tFHstFKC=0;
if(_25_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[0-9]/ .test(s.charAt(_25_vPZqNwk$K_RP34tFHstFKC++ ) ) )_25_vPZqNwk$K_RP34tFHstFKC= -1} ;
while(_25_vPZqNwk$K_RP34tFHstFKC> -1&& ++_26_vPZqNwk$K_RP34tFHstFKC<=Infinity)_23_vPZqNwk$K_RP34tFHstFKC=_25_vPZqNwk$K_RP34tFHstFKC, (if(_25_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[0-9]/ .test(s.charAt(_25_vPZqNwk$K_RP34tFHstFKC++ ) ) )_25_vPZqNwk$K_RP34tFHstFKC= -1} ) ;
if(_26_vPZqNwk$K_RP34tFHstFKC<0)_23_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_23_vPZqNwk$K_RP34tFHstFKC> -1) {var _27_vPZqNwk$K_RP34tFHstFKC=_23_vPZqNwk$K_RP34tFHstFKC,_28_vPZqNwk$K_RP34tFHstFKC=0;
if(_27_vPZqNwk$K_RP34tFHstFKC> -1) {if(_27_vPZqNwk$K_RP34tFHstFKC> -1) {if(_27_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[eE]/ .test(s.charAt(_27_vPZqNwk$K_RP34tFHstFKC++ ) ) )_27_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_27_vPZqNwk$K_RP34tFHstFKC> -1) {if(_27_vPZqNwk$K_RP34tFHstFKC> -1) {var _29_vPZqNwk$K_RP34tFHstFKC=_27_vPZqNwk$K_RP34tFHstFKC,_2a_vPZqNwk$K_RP34tFHstFKC=0;
if(_29_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[-+]/ .test(s.charAt(_29_vPZqNwk$K_RP34tFHstFKC++ ) ) )_29_vPZqNwk$K_RP34tFHstFKC= -1} ;
while(_29_vPZqNwk$K_RP34tFHstFKC> -1&& ++_2a_vPZqNwk$K_RP34tFHstFKC<=1)_27_vPZqNwk$K_RP34tFHstFKC=_29_vPZqNwk$K_RP34tFHstFKC, (if(_29_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[-+]/ .test(s.charAt(_29_vPZqNwk$K_RP34tFHstFKC++ ) ) )_29_vPZqNwk$K_RP34tFHstFKC= -1} ) ;
if(_2a_vPZqNwk$K_RP34tFHstFKC<0)_27_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_27_vPZqNwk$K_RP34tFHstFKC> -1) {var _2b_vPZqNwk$K_RP34tFHstFKC=_27_vPZqNwk$K_RP34tFHstFKC,_2c_vPZqNwk$K_RP34tFHstFKC=0;
if(_2b_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[0-9]/ .test(s.charAt(_2b_vPZqNwk$K_RP34tFHstFKC++ ) ) )_2b_vPZqNwk$K_RP34tFHstFKC= -1} ;
while(_2b_vPZqNwk$K_RP34tFHstFKC> -1&& ++_2c_vPZqNwk$K_RP34tFHstFKC<=Infinity)_27_vPZqNwk$K_RP34tFHstFKC=_2b_vPZqNwk$K_RP34tFHstFKC, (if(_2b_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[0-9]/ .test(s.charAt(_2b_vPZqNwk$K_RP34tFHstFKC++ ) ) )_2b_vPZqNwk$K_RP34tFHstFKC= -1} ) ;
if(_2c_vPZqNwk$K_RP34tFHstFKC<1)_27_vPZqNwk$K_RP34tFHstFKC= -1} } } } ;
while(_27_vPZqNwk$K_RP34tFHstFKC> -1&& ++_28_vPZqNwk$K_RP34tFHstFKC<=1)_23_vPZqNwk$K_RP34tFHstFKC=_27_vPZqNwk$K_RP34tFHstFKC, (if(_27_vPZqNwk$K_RP34tFHstFKC> -1) {if(_27_vPZqNwk$K_RP34tFHstFKC> -1) {if(_27_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[eE]/ .test(s.charAt(_27_vPZqNwk$K_RP34tFHstFKC++ ) ) )_27_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_27_vPZqNwk$K_RP34tFHstFKC> -1) {if(_27_vPZqNwk$K_RP34tFHstFKC> -1) {var _29_vPZqNwk$K_RP34tFHstFKC=_27_vPZqNwk$K_RP34tFHstFKC,_2a_vPZqNwk$K_RP34tFHstFKC=0;
if(_29_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[-+]/ .test(s.charAt(_29_vPZqNwk$K_RP34tFHstFKC++ ) ) )_29_vPZqNwk$K_RP34tFHstFKC= -1} ;
while(_29_vPZqNwk$K_RP34tFHstFKC> -1&& ++_2a_vPZqNwk$K_RP34tFHstFKC<=1)_27_vPZqNwk$K_RP34tFHstFKC=_29_vPZqNwk$K_RP34tFHstFKC, (if(_29_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[-+]/ .test(s.charAt(_29_vPZqNwk$K_RP34tFHstFKC++ ) ) )_29_vPZqNwk$K_RP34tFHstFKC= -1} ) ;
if(_2a_vPZqNwk$K_RP34tFHstFKC<0)_27_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_27_vPZqNwk$K_RP34tFHstFKC> -1) {var _2b_vPZqNwk$K_RP34tFHstFKC=_27_vPZqNwk$K_RP34tFHstFKC,_2c_vPZqNwk$K_RP34tFHstFKC=0;
if(_2b_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[0-9]/ .test(s.charAt(_2b_vPZqNwk$K_RP34tFHstFKC++ ) ) )_2b_vPZqNwk$K_RP34tFHstFKC= -1} ;
while(_2b_vPZqNwk$K_RP34tFHstFKC> -1&& ++_2c_vPZqNwk$K_RP34tFHstFKC<=Infinity)_27_vPZqNwk$K_RP34tFHstFKC=_2b_vPZqNwk$K_RP34tFHstFKC, (if(_2b_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[0-9]/ .test(s.charAt(_2b_vPZqNwk$K_RP34tFHstFKC++ ) ) )_2b_vPZqNwk$K_RP34tFHstFKC= -1} ) ;
if(_2c_vPZqNwk$K_RP34tFHstFKC<1)_27_vPZqNwk$K_RP34tFHstFKC= -1} } } } ) ;
if(_28_vPZqNwk$K_RP34tFHstFKC<0)_23_vPZqNwk$K_RP34tFHstFKC= -1} } } } ;
while(_23_vPZqNwk$K_RP34tFHstFKC> -1&& ++_24_vPZqNwk$K_RP34tFHstFKC<=1)ii=_23_vPZqNwk$K_RP34tFHstFKC, (if(_23_vPZqNwk$K_RP34tFHstFKC> -1) {if(_23_vPZqNwk$K_RP34tFHstFKC> -1) {if(_23_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /\./ .test(s.charAt(_23_vPZqNwk$K_RP34tFHstFKC++ ) ) )_23_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_23_vPZqNwk$K_RP34tFHstFKC> -1) {if(_23_vPZqNwk$K_RP34tFHstFKC> -1) {var _25_vPZqNwk$K_RP34tFHstFKC=_23_vPZqNwk$K_RP34tFHstFKC,_26_vPZqNwk$K_RP34tFHstFKC=0;
if(_25_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[0-9]/ .test(s.charAt(_25_vPZqNwk$K_RP34tFHstFKC++ ) ) )_25_vPZqNwk$K_RP34tFHstFKC= -1} ;
while(_25_vPZqNwk$K_RP34tFHstFKC> -1&& ++_26_vPZqNwk$K_RP34tFHstFKC<=Infinity)_23_vPZqNwk$K_RP34tFHstFKC=_25_vPZqNwk$K_RP34tFHstFKC, (if(_25_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[0-9]/ .test(s.charAt(_25_vPZqNwk$K_RP34tFHstFKC++ ) ) )_25_vPZqNwk$K_RP34tFHstFKC= -1} ) ;
if(_26_vPZqNwk$K_RP34tFHstFKC<0)_23_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_23_vPZqNwk$K_RP34tFHstFKC> -1) {var _27_vPZqNwk$K_RP34tFHstFKC=_23_vPZqNwk$K_RP34tFHstFKC,_28_vPZqNwk$K_RP34tFHstFKC=0;
if(_27_vPZqNwk$K_RP34tFHstFKC> -1) {if(_27_vPZqNwk$K_RP34tFHstFKC> -1) {if(_27_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[eE]/ .test(s.charAt(_27_vPZqNwk$K_RP34tFHstFKC++ ) ) )_27_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_27_vPZqNwk$K_RP34tFHstFKC> -1) {if(_27_vPZqNwk$K_RP34tFHstFKC> -1) {var _29_vPZqNwk$K_RP34tFHstFKC=_27_vPZqNwk$K_RP34tFHstFKC,_2a_vPZqNwk$K_RP34tFHstFKC=0;
if(_29_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[-+]/ .test(s.charAt(_29_vPZqNwk$K_RP34tFHstFKC++ ) ) )_29_vPZqNwk$K_RP34tFHstFKC= -1} ;
while(_29_vPZqNwk$K_RP34tFHstFKC> -1&& ++_2a_vPZqNwk$K_RP34tFHstFKC<=1)_27_vPZqNwk$K_RP34tFHstFKC=_29_vPZqNwk$K_RP34tFHstFKC, (if(_29_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[-+]/ .test(s.charAt(_29_vPZqNwk$K_RP34tFHstFKC++ ) ) )_29_vPZqNwk$K_RP34tFHstFKC= -1} ) ;
if(_2a_vPZqNwk$K_RP34tFHstFKC<0)_27_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_27_vPZqNwk$K_RP34tFHstFKC> -1) {var _2b_vPZqNwk$K_RP34tFHstFKC=_27_vPZqNwk$K_RP34tFHstFKC,_2c_vPZqNwk$K_RP34tFHstFKC=0;
if(_2b_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[0-9]/ .test(s.charAt(_2b_vPZqNwk$K_RP34tFHstFKC++ ) ) )_2b_vPZqNwk$K_RP34tFHstFKC= -1} ;
while(_2b_vPZqNwk$K_RP34tFHstFKC> -1&& ++_2c_vPZqNwk$K_RP34tFHstFKC<=Infinity)_27_vPZqNwk$K_RP34tFHstFKC=_2b_vPZqNwk$K_RP34tFHstFKC, (if(_2b_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[0-9]/ .test(s.charAt(_2b_vPZqNwk$K_RP34tFHstFKC++ ) ) )_2b_vPZqNwk$K_RP34tFHstFKC= -1} ) ;
if(_2c_vPZqNwk$K_RP34tFHstFKC<1)_27_vPZqNwk$K_RP34tFHstFKC= -1} } } } ;
while(_27_vPZqNwk$K_RP34tFHstFKC> -1&& ++_28_vPZqNwk$K_RP34tFHstFKC<=1)_23_vPZqNwk$K_RP34tFHstFKC=_27_vPZqNwk$K_RP34tFHstFKC, (if(_27_vPZqNwk$K_RP34tFHstFKC> -1) {if(_27_vPZqNwk$K_RP34tFHstFKC> -1) {if(_27_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[eE]/ .test(s.charAt(_27_vPZqNwk$K_RP34tFHstFKC++ ) ) )_27_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_27_vPZqNwk$K_RP34tFHstFKC> -1) {if(_27_vPZqNwk$K_RP34tFHstFKC> -1) {var _29_vPZqNwk$K_RP34tFHstFKC=_27_vPZqNwk$K_RP34tFHstFKC,_2a_vPZqNwk$K_RP34tFHstFKC=0;
if(_29_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[-+]/ .test(s.charAt(_29_vPZqNwk$K_RP34tFHstFKC++ ) ) )_29_vPZqNwk$K_RP34tFHstFKC= -1} ;
while(_29_vPZqNwk$K_RP34tFHstFKC> -1&& ++_2a_vPZqNwk$K_RP34tFHstFKC<=1)_27_vPZqNwk$K_RP34tFHstFKC=_29_vPZqNwk$K_RP34tFHstFKC, (if(_29_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[-+]/ .test(s.charAt(_29_vPZqNwk$K_RP34tFHstFKC++ ) ) )_29_vPZqNwk$K_RP34tFHstFKC= -1} ) ;
if(_2a_vPZqNwk$K_RP34tFHstFKC<0)_27_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_27_vPZqNwk$K_RP34tFHstFKC> -1) {var _2b_vPZqNwk$K_RP34tFHstFKC=_27_vPZqNwk$K_RP34tFHstFKC,_2c_vPZqNwk$K_RP34tFHstFKC=0;
if(_2b_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[0-9]/ .test(s.charAt(_2b_vPZqNwk$K_RP34tFHstFKC++ ) ) )_2b_vPZqNwk$K_RP34tFHstFKC= -1} ;
while(_2b_vPZqNwk$K_RP34tFHstFKC> -1&& ++_2c_vPZqNwk$K_RP34tFHstFKC<=Infinity)_27_vPZqNwk$K_RP34tFHstFKC=_2b_vPZqNwk$K_RP34tFHstFKC, (if(_2b_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[0-9]/ .test(s.charAt(_2b_vPZqNwk$K_RP34tFHstFKC++ ) ) )_2b_vPZqNwk$K_RP34tFHstFKC= -1} ) ;
if(_2c_vPZqNwk$K_RP34tFHstFKC<1)_27_vPZqNwk$K_RP34tFHstFKC= -1} } } } ) ;
if(_28_vPZqNwk$K_RP34tFHstFKC<0)_23_vPZqNwk$K_RP34tFHstFKC= -1} } } } ) ;
if(_24_vPZqNwk$K_RP34tFHstFKC<0)ii= -1} } } } } } } } } ;
if(ii> -1)return new number(s,i,ii) } ,number.prototype= {map:function(f) {var r=f(this) ;
return r===true|| !r?this:r} ,start:function() {;
return this.start_} ,end:function() {;
return this.end_} ,length:0,toString:function() {;
return this.input_.substring(this.start_,this.end_) } } ,number.prototype.constructor=number,regexp=function(input_,start_,end_) {;
return this.constructor===regexp? (this.input_=input_,this.start_=start_,this.end_=end_,this) :regexp.parse(arguments[0] ,arguments[1] ||0) } ,regexp.parse=function(s,i) {var ii=i;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== "/" )ii= -1} ;
if(ii> -1) {if(ii> -1) {var _2d_vPZqNwk$K_RP34tFHstFKC=ii,_2e_vPZqNwk$K_RP34tFHstFKC=0;
if(_2d_vPZqNwk$K_RP34tFHstFKC> -1) {if(_2d_vPZqNwk$K_RP34tFHstFKC> -1) {var _2f_vPZqNwk$K_RP34tFHstFKC=_2d_vPZqNwk$K_RP34tFHstFKC;
if(_2f_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[^\\\/]/ .test(s.charAt(_2f_vPZqNwk$K_RP34tFHstFKC++ ) ) )_2f_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_2f_vPZqNwk$K_RP34tFHstFKC> -1)_2d_vPZqNwk$K_RP34tFHstFKC=_2f_vPZqNwk$K_RP34tFHstFKC;
else{if(_2d_vPZqNwk$K_RP34tFHstFKC> -1) {if(_2d_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /\\/ .test(s.charAt(_2d_vPZqNwk$K_RP34tFHstFKC++ ) ) )_2d_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_2d_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /./ .test(s.charAt(_2d_vPZqNwk$K_RP34tFHstFKC++ ) ) )_2d_vPZqNwk$K_RP34tFHstFKC= -1} } } } } ;
while(_2d_vPZqNwk$K_RP34tFHstFKC> -1&& ++_2e_vPZqNwk$K_RP34tFHstFKC<=Infinity)ii=_2d_vPZqNwk$K_RP34tFHstFKC, (if(_2d_vPZqNwk$K_RP34tFHstFKC> -1) {if(_2d_vPZqNwk$K_RP34tFHstFKC> -1) {var _2f_vPZqNwk$K_RP34tFHstFKC=_2d_vPZqNwk$K_RP34tFHstFKC;
if(_2f_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[^\\\/]/ .test(s.charAt(_2f_vPZqNwk$K_RP34tFHstFKC++ ) ) )_2f_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_2f_vPZqNwk$K_RP34tFHstFKC> -1)_2d_vPZqNwk$K_RP34tFHstFKC=_2f_vPZqNwk$K_RP34tFHstFKC;
else{if(_2d_vPZqNwk$K_RP34tFHstFKC> -1) {if(_2d_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /\\/ .test(s.charAt(_2d_vPZqNwk$K_RP34tFHstFKC++ ) ) )_2d_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_2d_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /./ .test(s.charAt(_2d_vPZqNwk$K_RP34tFHstFKC++ ) ) )_2d_vPZqNwk$K_RP34tFHstFKC= -1} } } } } ) ;
if(_2e_vPZqNwk$K_RP34tFHstFKC<0)ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "/" )ii= -1} } } ;
if(ii> -1)return new regexp(s,i,ii) } ,regexp.prototype= {map:function(f) {var r=f(this) ;
return r===true|| !r?this:r} ,start:function() {;
return this.start_} ,end:function() {;
return this.end_} ,length:0,toString:function() {;
return this.input_.substring(this.start_,this.end_) } } ,regexp.prototype.constructor=regexp,identifier=function(input_,start_,end_) {;
return this.constructor===identifier? (this.input_=input_,this.start_=start_,this.end_=end_,this) :identifier.parse(arguments[0] ,arguments[1] ||0) } ,identifier.parse=function(s,i) {var ii=i;
if(ii> -1) {if(ii> -1) {if( ! /[A-Za-z$_]/ .test(s.charAt(ii++ ) ) )ii= -1} ;
if(ii> -1) {var _2g_vPZqNwk$K_RP34tFHstFKC=ii,_2h_vPZqNwk$K_RP34tFHstFKC=0;
if(_2g_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[A-Za-z0-9$_]/ .test(s.charAt(_2g_vPZqNwk$K_RP34tFHstFKC++ ) ) )_2g_vPZqNwk$K_RP34tFHstFKC= -1} ;
while(_2g_vPZqNwk$K_RP34tFHstFKC> -1&& ++_2h_vPZqNwk$K_RP34tFHstFKC<=Infinity)ii=_2g_vPZqNwk$K_RP34tFHstFKC, (if(_2g_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[A-Za-z0-9$_]/ .test(s.charAt(_2g_vPZqNwk$K_RP34tFHstFKC++ ) ) )_2g_vPZqNwk$K_RP34tFHstFKC= -1} ) ;
if(_2h_vPZqNwk$K_RP34tFHstFKC<0)ii= -1} } ;
if(ii> -1)return new identifier(s,i,ii) } ,identifier.prototype= {map:function(f) {var r=f(this) ;
return r===true|| !r?this:r} ,start:function() {;
return this.start_} ,end:function() {;
return this.end_} ,length:0,toString:function() {;
return this.input_.substring(this.start_,this.end_) } } ,identifier.prototype.constructor=identifier,atom=function(input_,start_,end_) {;
return this.constructor===atom? (this.input_=input_,this.start_=start_,this.end_=end_,this) :atom.parse(arguments[0] ,arguments[1] ||0) } ,atom.parse=function(s,i) {var ii=i;
if(ii> -1) {var _2i_vPZqNwk$K_RP34tFHstFKC=ii;
if(_2i_vPZqNwk$K_RP34tFHstFKC> -1) {if(_2i_vPZqNwk$K_RP34tFHstFKC> -1) {if(_2i_vPZqNwk$K_RP34tFHstFKC> -1) {if(_2i_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_2i_vPZqNwk$K_RP34tFHstFKC,_2i_vPZqNwk$K_RP34tFHstFKC+=3) !== "pre" )_2i_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_2i_vPZqNwk$K_RP34tFHstFKC> -1) {if(_2i_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_2i_vPZqNwk$K_RP34tFHstFKC,_2i_vPZqNwk$K_RP34tFHstFKC+=1) !== ":" )_2i_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_2i_vPZqNwk$K_RP34tFHstFKC> -1) {if(_2i_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_2i_vPZqNwk$K_RP34tFHstFKC,_2i_vPZqNwk$K_RP34tFHstFKC+=2) !== "ws" )_2i_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_2i_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_2i_vPZqNwk$K_RP34tFHstFKC,_2i_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_2i_vPZqNwk$K_RP34tFHstFKC= -1} } } } } ;
if(_2i_vPZqNwk$K_RP34tFHstFKC> -1) {if(_2i_vPZqNwk$K_RP34tFHstFKC> -1) {if(_2i_vPZqNwk$K_RP34tFHstFKC> -1) {if(_2i_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_2i_vPZqNwk$K_RP34tFHstFKC,_2i_vPZqNwk$K_RP34tFHstFKC+=3) !== "lhs" )_2i_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_2i_vPZqNwk$K_RP34tFHstFKC> -1) {if(_2i_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_2i_vPZqNwk$K_RP34tFHstFKC,_2i_vPZqNwk$K_RP34tFHstFKC+=1) !== ":" )_2i_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_2i_vPZqNwk$K_RP34tFHstFKC> -1) {if(_2i_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_2i_vPZqNwk$K_RP34tFHstFKC,_2i_vPZqNwk$K_RP34tFHstFKC+=7) !== "literal" )_2i_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_2i_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_2i_vPZqNwk$K_RP34tFHstFKC,_2i_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_2i_vPZqNwk$K_RP34tFHstFKC= -1} } } } } ;
if(_2i_vPZqNwk$K_RP34tFHstFKC> -1) {if(_2i_vPZqNwk$K_RP34tFHstFKC> -1) {if(_2i_vPZqNwk$K_RP34tFHstFKC> -1) {if(_2i_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_2i_vPZqNwk$K_RP34tFHstFKC,_2i_vPZqNwk$K_RP34tFHstFKC+=2) !== "op" )_2i_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_2i_vPZqNwk$K_RP34tFHstFKC> -1) {if(_2i_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_2i_vPZqNwk$K_RP34tFHstFKC,_2i_vPZqNwk$K_RP34tFHstFKC+=1) !== ":" )_2i_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_2i_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[.]/ .test(s.charAt(_2i_vPZqNwk$K_RP34tFHstFKC++ ) ) )_2i_vPZqNwk$K_RP34tFHstFKC= -1} } } } ;
if(_2i_vPZqNwk$K_RP34tFHstFKC> -1) {if(_2i_vPZqNwk$K_RP34tFHstFKC> -1) {if(_2i_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_2i_vPZqNwk$K_RP34tFHstFKC,_2i_vPZqNwk$K_RP34tFHstFKC+=3) !== "rhs" )_2i_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_2i_vPZqNwk$K_RP34tFHstFKC> -1) {if(_2i_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_2i_vPZqNwk$K_RP34tFHstFKC,_2i_vPZqNwk$K_RP34tFHstFKC+=1) !== ":" )_2i_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_2i_vPZqNwk$K_RP34tFHstFKC> -1) {if(_2i_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_2i_vPZqNwk$K_RP34tFHstFKC,_2i_vPZqNwk$K_RP34tFHstFKC+=4) !== "atom" )_2i_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_2i_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_2i_vPZqNwk$K_RP34tFHstFKC,_2i_vPZqNwk$K_RP34tFHstFKC+=1) !== "@" )_2i_vPZqNwk$K_RP34tFHstFKC= -1} } } } } } } } ;
if(_2i_vPZqNwk$K_RP34tFHstFKC> -1)ii=_2i_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=3) !== "pre" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=2) !== "ws" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=3) !== "lhs" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=7) !== "literal" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } } } } ;
if(ii> -1)return new atom(s,i,ii) } ,atom.prototype= {map:function(f) {var r=f(this) ;
return r===true|| !r?this:r} ,start:function() {;
return this.start_} ,end:function() {;
return this.end_} ,length:0,toString:function() {;
return this.input_.substring(this.start_,this.end_) } } ,atom.prototype.constructor=atom,unary=function(input_,start_,end_) {;
return this.constructor===unary? (this.input_=input_,this.start_=start_,this.end_=end_,this) :unary.parse(arguments[0] ,arguments[1] ||0) } ,unary.parse=function(s,i) {var ii=i;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=3) !== "pre" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=2) !== "ws" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=2) !== "op" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {var _2j_vPZqNwk$K_RP34tFHstFKC=ii;
if(_2j_vPZqNwk$K_RP34tFHstFKC> -1) {if(_2j_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_2j_vPZqNwk$K_RP34tFHstFKC,_2j_vPZqNwk$K_RP34tFHstFKC+=1) !== "-" )_2j_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_2j_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_2j_vPZqNwk$K_RP34tFHstFKC,_2j_vPZqNwk$K_RP34tFHstFKC+=1) !== "-" )_2j_vPZqNwk$K_RP34tFHstFKC= -1} } ;
if(_2j_vPZqNwk$K_RP34tFHstFKC> -1)ii=_2j_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {var _2k_vPZqNwk$K_RP34tFHstFKC=ii;
if(_2k_vPZqNwk$K_RP34tFHstFKC> -1) {if(_2k_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /\+/ .test(s.charAt(_2k_vPZqNwk$K_RP34tFHstFKC++ ) ) )_2k_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_2k_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /\+/ .test(s.charAt(_2k_vPZqNwk$K_RP34tFHstFKC++ ) ) )_2k_vPZqNwk$K_RP34tFHstFKC= -1} } ;
if(_2k_vPZqNwk$K_RP34tFHstFKC> -1)ii=_2k_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {var _2l_vPZqNwk$K_RP34tFHstFKC=ii;
if(_2l_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_2l_vPZqNwk$K_RP34tFHstFKC,_2l_vPZqNwk$K_RP34tFHstFKC+=1) !== "-" )_2l_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_2l_vPZqNwk$K_RP34tFHstFKC> -1)ii=_2l_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {var _2m_vPZqNwk$K_RP34tFHstFKC=ii;
if(_2m_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /\+/ .test(s.charAt(_2m_vPZqNwk$K_RP34tFHstFKC++ ) ) )_2m_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_2m_vPZqNwk$K_RP34tFHstFKC> -1)ii=_2m_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {var _2n_vPZqNwk$K_RP34tFHstFKC=ii;
if(_2n_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_2n_vPZqNwk$K_RP34tFHstFKC,_2n_vPZqNwk$K_RP34tFHstFKC+=1) !== "~" )_2n_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_2n_vPZqNwk$K_RP34tFHstFKC> -1)ii=_2n_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {var _2o_vPZqNwk$K_RP34tFHstFKC=ii;
if(_2o_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_2o_vPZqNwk$K_RP34tFHstFKC,_2o_vPZqNwk$K_RP34tFHstFKC+=1) !== "!" )_2o_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_2o_vPZqNwk$K_RP34tFHstFKC> -1)ii=_2o_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {var _2p_vPZqNwk$K_RP34tFHstFKC=ii;
if(_2p_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_2p_vPZqNwk$K_RP34tFHstFKC,_2p_vPZqNwk$K_RP34tFHstFKC+=3) !== "new" )_2p_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_2p_vPZqNwk$K_RP34tFHstFKC> -1)ii=_2p_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {if(s.substring(ii,ii+=6) !== "typeof" )ii= -1} } } } } } } } } } } } } } } } } } } ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=4) !== "post" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=2) !== "ws" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=3) !== "rhs" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=10) !== "expression" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } } } } ;
if(ii> -1)return new unary(s,i,ii) } ,unary.prototype= {map:function(f) {var r=f(this) ;
return r===true|| !r?this:r} ,start:function() {;
return this.start_} ,end:function() {;
return this.end_} ,length:0,toString:function() {;
return this.input_.substring(this.start_,this.end_) } } ,unary.prototype.constructor=unary,binary=function(input_,start_,end_) {;
return this.constructor===binary? (this.input_=input_,this.start_=start_,this.end_=end_,this) :binary.parse(arguments[0] ,arguments[1] ||0) } ,binary.parse=function(s,i) {var ii=i;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=3) !== "lhs" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=4) !== "atom" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=3) !== "pre" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=2) !== "ws" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {var _2q_vPZqNwk$K_RP34tFHstFKC=ii;
if(_2q_vPZqNwk$K_RP34tFHstFKC> -1) {if(_2q_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_2q_vPZqNwk$K_RP34tFHstFKC,_2q_vPZqNwk$K_RP34tFHstFKC+=2) !== "op" )_2q_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_2q_vPZqNwk$K_RP34tFHstFKC> -1) {if(_2q_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_2q_vPZqNwk$K_RP34tFHstFKC,_2q_vPZqNwk$K_RP34tFHstFKC+=1) !== ":" )_2q_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_2q_vPZqNwk$K_RP34tFHstFKC> -1) {if( ! /[-.+*\/%!=<>&|^?:]/ .test(s.charAt(_2q_vPZqNwk$K_RP34tFHstFKC++ ) ) )_2q_vPZqNwk$K_RP34tFHstFKC= -1} } } ;
if(_2q_vPZqNwk$K_RP34tFHstFKC> -1)ii=_2q_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {var _2r_vPZqNwk$K_RP34tFHstFKC=ii;
if(_2r_vPZqNwk$K_RP34tFHstFKC> -1) {if(s.substring(_2r_vPZqNwk$K_RP34tFHstFKC,_2r_vPZqNwk$K_RP34tFHstFKC+=10) !== "instanceof" )_2r_vPZqNwk$K_RP34tFHstFKC= -1} ;
if(_2r_vPZqNwk$K_RP34tFHstFKC> -1)ii=_2r_vPZqNwk$K_RP34tFHstFKC;
else{if(ii> -1) {if(s.substring(ii,ii+=2) !== "in" )ii= -1} } } } } } ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=4) !== "post" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=2) !== "ws" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=3) !== "rhs" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=10) !== "expression" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } } } } } ;
if(ii> -1)return new binary(s,i,ii) } ,binary.prototype= {map:function(f) {var r=f(this) ;
return r===true|| !r?this:r} ,start:function() {;
return this.start_} ,end:function() {;
return this.end_} ,length:0,toString:function() {;
return this.input_.substring(this.start_,this.end_) } } ,binary.prototype.constructor=binary,group=function(input_,start_,end_) {;
return this.constructor===group? (this.input_=input_,this.start_=start_,this.end_=end_,this) :group.parse(arguments[0] ,arguments[1] ||0) } ,group.parse=function(s,i) {var ii=i;
if(ii> -1) {if(ii> -1) {if( ! /\(/ .test(s.charAt(ii++ ) ) )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== "x" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=11) !== "expressions" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if( ! /\)/ .test(s.charAt(ii++ ) ) )ii= -1} } } ;
if(ii> -1)return new group(s,i,ii) } ,group.prototype= {map:function(f) {var r=f(this) ;
return r===true|| !r?this:r} ,start:function() {;
return this.start_} ,end:function() {;
return this.end_} ,length:0,toString:function() {;
return this.input_.substring(this.start_,this.end_) } } ,group.prototype.constructor=group,array=function(input_,start_,end_) {;
return this.constructor===array? (this.input_=input_,this.start_=start_,this.end_=end_,this) :array.parse(arguments[0] ,arguments[1] ||0) } ,array.parse=function(s,i) {var ii=i;
if(ii> -1) {if(ii> -1) {if( ! /\[/ .test(s.charAt(ii++ ) ) )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=2) !== "xs" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=11) !== "expressions" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if( ! /\]/ .test(s.charAt(ii++ ) ) )ii= -1} } } ;
if(ii> -1)return new array(s,i,ii) } ,array.prototype= {map:function(f) {var r=f(this) ;
return r===true|| !r?this:r} ,start:function() {;
return this.start_} ,end:function() {;
return this.end_} ,length:0,toString:function() {;
return this.input_.substring(this.start_,this.end_) } } ,array.prototype.constructor=array,object=function(input_,start_,end_) {;
return this.constructor===object? (this.input_=input_,this.start_=start_,this.end_=end_,this) :object.parse(arguments[0] ,arguments[1] ||0) } ,object.parse=function(s,i) {var ii=i;
if(ii> -1) {if(ii> -1) {if( ! /\{/ .test(s.charAt(ii++ ) ) )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=2) !== "xs" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=1) !== ":" )ii= -1} ;
if(ii> -1) {if(ii> -1) {if(s.substring(ii,ii+=11) !== "expressions" )ii= -1} ;
if(ii> -1) {if(s.substring(ii,ii+=1) !== "@" )ii= -1} } } } } ;
if(ii> -1) {if( ! /\}/ .test(s.charAt(ii++ ) ) )ii= -1} } } ;
if(ii> -1)return new object(s,i,ii) } ,object.prototype= {map:function(f) {var r=f(this) ;
return r===true|| !r?this:r} ,start:function() {;
return this.start_} ,end:function() {;
return this.end_} ,length:0,toString:function() {;
return this.input_.substring(this.start_,this.end_) } } ,object.prototype.constructor=object