caterwaul.tconfiguration('std.qs std.fn std.bind','macro.defmacro',caterwaul.precompiled_internal((function (){var gensym_2_gmjsv4gr_7vsnoa=caterwaul.parse('defmacro[_][_]');
var gensym_2_gmjsv4gr_7vsnob=caterwaul.parse('null');
var gensym_2_gmjsv4gr_7vsnoc=caterwaul.parse('defsubst[_][_]');
var gensym_2_gmjsv4gr_7vsnod=caterwaul.parse('null');
return (function (gensym_2_gmjsv4gr_7vsno5){(function (wildcard){return this.macro(gensym_2_gmjsv4gr_7vsnoa,(function (pattern,expansion){return this.rmacro(pattern,this.compile(this.macroexpand(expansion))),gensym_2_gmjsv4gr_7vsnob})).macro(gensym_2_gmjsv4gr_7vsnoc,(function (pattern,expansion){return this.rmacro(pattern.rmap(wildcard),(function (wildcards){return (function (){return (function (hash,as){return this.util.map((function (v,i){return hash[v.data]=as[i]}),wildcards),expansion.replace(hash)}).call(this,{},arguments)})}).call(this,pattern.collect(wildcard))),gensym_2_gmjsv4gr_7vsnod}))}).call(this,(function (n){return n.data.constructor===String&&n.data.charAt(0)==='_'&&'_'}))})})())).tconfiguration('std.qs std.fn std.bind','macro.with_gensyms',caterwaul.precompiled_internal((function (){var gensym_2_gmjsv4gr_7vsnof=caterwaul.parse('with_gensyms[_][_]');
var gensym_2_gmjsv4gr_7vsnoh=caterwaul.parse('qs[_]');
return (function (gensym_2_gmjsv4gr_7vsno6){this.rmacro(gensym_2_gmjsv4gr_7vsnof,(function (vars,expansion){return (function (bindings){return vars.flatten(',').each((function (gensym_2_gmjsv4gr_7vsnog){return (function (){return (function (v){return bindings[v.data]=this.gensym()}).apply(gensym_2_gmjsv4gr_7vsnog,arguments)})})(this)),gensym_2_gmjsv4gr_7vsnoh.replace({_:expansion.replace(bindings)})}).call(this,{})}))})})())).tconfiguration('std.qs std.fn','macro.compile_eval',caterwaul.precompiled_internal((function (){var gensym_2_gmjsv4gr_7vsnoj=caterwaul.parse('compile_eval[_]');
var gensym_2_gmjsv4gr_7vsnok=caterwaul.parse('fn_[_]');
return (function (gensym_2_gmjsv4gr_7vsno7){this.macro(gensym_2_gmjsv4gr_7vsnoj,(function (e){return new this.ref(this.compile(this.macroexpand(gensym_2_gmjsv4gr_7vsnok.replace({_:e}))).call(this))}))})})())).configuration('macro',function (gensym_2_gmjsv4gr_7vsno8){this.configure('macro.defmacro macro.with_gensyms macro.compile_eval')});
