caterwaul.tconfiguration('std seq continuation memoize','parser.core',caterwaul.precompiled_internal((function (){var gensym_2_gmjsv9bw_4u1rkr=caterwaul.clone('std.qs std.qg std.bind std.lvalue std.cond std.fn std.obj std.ref std.string std seq.core seq.finite.core seq.finite.object seq.finite.mutability seq.finite.traversal seq.finite.zip seq.finite.quantification seq.finite.serialization seq.infinite.core seq.infinite.y seq.infinite.transform seq.infinite.traversal seq.numeric seq.dsl seq continuation.core continuation.unwind continuation.cps continuation.delimited continuation memoize');
var gensym_2_gmjsv9bw_4u1rks=gensym_2_gmjsv9bw_4u1rkr;
return (function (gensym_2_gmjsv9bw_4u1rkg){((function (_){return _.parse_state=(function (input,i,result,memo){return ((function (_){return this.input=input,this.i=i,this.result=result,this.memo=memo,_})).call(this,undefined)}),((function (s){return s.from_input=(function (input){return new _.parse_state(input,0,null,{})}),((function (_){return _.accept=(function (i,r){return new this.constructor(this.input,i,r,this.memo)}),_.has_input=(function (){return this.i<this.input.length}),_.toString=(function (){return ('ps['+(this.input.substr(this.i))+', '+(this.result)+']')}),_})).call(this,s.prototype),s})).call(this,_.parse_state),_.memoize=gensym_2_gmjsv9bw_4u1rkr.memoize.from((function (c,as,f){return (function (k,m){return k in m?m[k]:(m[k]=f.apply(c,as))}).call(this,(''+(f.original.memo_id)+'|'+(as[0].i)+''),as[0].memo||(as[0].memo={}))})),_.promote_non_states=(function (f){return (function (state){return state instanceof _.parse_state?f.call(this,state):((function (_){return _&&_.result})).call(this,f.call(this,_.parse_state.from_input(state)))})}),_.identify=(function (f){return ((function (_){return _.memo_id=gensym_2_gmjsv9bw_4u1rks.gensym(),_})).call(this,f)}),_.parser=(function (f){return _.promote_non_states(_.memoize(_.identify(f)))}),_.defparser=(function (name,f){return _.parsers[name]=(function (){return _.parser(f.apply(this,arguments))})}),_.parsers={},_})).call(this,this.namespace('parser'))})})())).tconfiguration('std seq continuation','parser.c',caterwaul.precompiled_internal((function (){var gensym_2_gmjsv9bw_4u1rku=caterwaul.clone('std.qs std.qg std.bind std.lvalue std.cond std.fn std.obj std.ref std.string std seq.core seq.finite.core seq.finite.object seq.finite.mutability seq.finite.traversal seq.finite.zip seq.finite.quantification seq.finite.serialization seq.infinite.core seq.infinite.y seq.infinite.transform seq.infinite.traversal seq.numeric seq.dsl seq continuation.core continuation.unwind continuation.cps continuation.delimited continuation');
var gensym_2_gmjsv9bw_4u1rkv=gensym_2_gmjsv9bw_4u1rku;
var gensym_2_gmjsv9bw_4u1rkw=gensym_2_gmjsv9bw_4u1rku;
var gensym_2_gmjsv9bw_4u1rkx=gensym_2_gmjsv9bw_4u1rku;
return (function (gensym_2_gmjsv9bw_4u1rkh){this.configure('parser.core').parser.defparser('c',(function (x,l){return (function (){var check_index=(function (i,s,p){return i.exists((function (_,_i){return (function (s){return _[('@'+(s)+'')]&&s}).call(this,s.substr(p,_.length))}))}),index_entries=(function (xs){return (function (){var xsp=(new gensym_2_gmjsv9bw_4u1rku.seq.finite(xs)),ls=gensym_2_gmjsv9bw_4u1rkv.seq.finite.keys((xsp.map((function (_,_i){return [_.length,true]}))).object()).map((function (_,_i){return Number(_)}));
return (new gensym_2_gmjsv9bw_4u1rkw.seq.finite(ls.slice().sort((function (x,y){return y-x})))).map((function (l,li){return (xsp.filter((function (_,_i){return _.length===l})).map((function (_,_i){return [('@'+(_)+''),true]})).concat([['length',l]])).object()}))}).call(this)}),add_absolute_anchors_to=(function (x){return (function (parts){return new RegExp(('^'+(parts[1])+'$'),parts[2])}).call(this,/^\/(.*)\/(\w*)$/.exec(x.toString()))}),fail_length=(function (re,s,p,l){return re.test(s.substr(p,l))?p+(l<<1)<=s.length?fail_length(re,s,p,l<<1):l<<1:l}),split_lengths=(function (re,s,p,l,u){return (function (){var b=(function (l,u){return l+1<u?((function (m){return re.test(s.substr(p,m))?b(m,u):b(l,m)})).call(this,(l+(u-l>>1))):l});
return b(l,u)}).call(this)});
return x.constructor===String?(function (st){return (x===st.input.substr(st.i,x.length))&&(st.accept(st.i+x.length,x))}):x instanceof Array?(function (index){return (function (st){return ((function (_){return _&&st.accept(st.i+_.length,_)})).call(this,check_index(index,st.input,st.i))})}).call(this,index_entries(x)):x.constructor===RegExp?(function (x){return (function (st){return ((function (_){return _>l&&((function (_){return st.accept(st.i+_,x.exec(st.input.substr(st.i,_)))})).call(this,split_lengths(x,st.input,st.i,l,_))})).call(this,fail_length(x,st.input,st.i,l))})}).call(this,add_absolute_anchors_to(x)):x.constructor===Function?(function (st){return ((function (_){return _&&st.accept(st.i+_,st.input.substr(st.i,_))})).call(this,x.call(st,st.input,st.i))}):(function (index){return (function (st){return ((function (_){return _&&st.accept(st.i+_.length,x[_])})).call(this,check_index(index,st.input,st.i))})}).call(this,index_entries(gensym_2_gmjsv9bw_4u1rkx.seq.finite.keys(x)))}).call(this)}))})})())).tconfiguration('std opt seq continuation','parser.seq',caterwaul.precompiled_internal((function (){var gensym_2_gmjsv9bw_4u1rkz=caterwaul.clone('std.qs std.qg std.bind std.lvalue std.cond std.fn std.obj std.ref std.string std opt.unroll opt seq.core seq.finite.core seq.finite.object seq.finite.mutability seq.finite.traversal seq.finite.zip seq.finite.quantification seq.finite.serialization seq.infinite.core seq.infinite.y seq.infinite.transform seq.infinite.traversal seq.numeric seq.dsl seq continuation.core continuation.unwind continuation.cps continuation.delimited continuation');
return (function (gensym_2_gmjsv9bw_4u1rki){this.configure('parser.core').parser.defparser('seq',(function (){return (function (as){return (function (state){return (function (result){return (gensym_2_gmjsv9bw_4u1rkz.continuation.call_cc.call(this,(function (cc){return (function (gensym_2_gmjsv9bw_4u1rf5){for (var gensym_2_gmjsv9bw_4u1rf6=gensym_2_gmjsv9bw_4u1rf5>=0&&gensym_2_gmjsv9bw_4u1rf5>>3,gensym_2_gmjsv9bw_4u1rf7=gensym_2_gmjsv9bw_4u1rf5>=0&&gensym_2_gmjsv9bw_4u1rf5&7,i=0;
i<gensym_2_gmjsv9bw_4u1rf7;
 ++i)(state=as[i](state))?result.push(state.result):cc(false);
for (var gensym_2_gmjsv9bw_4u1rf8=0;
gensym_2_gmjsv9bw_4u1rf8<gensym_2_gmjsv9bw_4u1rf6;
 ++gensym_2_gmjsv9bw_4u1rf8){(state=as[i](state))?result.push(state.result):cc(false);
i++;
(state=as[i](state))?result.push(state.result):cc(false);
i++;
(state=as[i](state))?result.push(state.result):cc(false);
i++;
(state=as[i](state))?result.push(state.result):cc(false);
i++;
(state=as[i](state))?result.push(state.result):cc(false);
i++;
(state=as[i](state))?result.push(state.result):cc(false);
i++;
(state=as[i](state))?result.push(state.result):cc(false);
i++;
(state=as[i](state))?result.push(state.result):cc(false);
i++};
return gensym_2_gmjsv9bw_4u1rf5}).call(this,as.length),state.accept(state.i,result)})))}).call(this,[])})}).call(this,arguments)}))})})())).tconfiguration('std opt seq continuation','parser.alt',caterwaul.precompiled_internal((function (){var gensym_2_gmjsv9bw_4u1rl1=caterwaul.clone('std.qs std.qg std.bind std.lvalue std.cond std.fn std.obj std.ref std.string std opt.unroll opt seq.core seq.finite.core seq.finite.object seq.finite.mutability seq.finite.traversal seq.finite.zip seq.finite.quantification seq.finite.serialization seq.infinite.core seq.infinite.y seq.infinite.transform seq.infinite.traversal seq.numeric seq.dsl seq continuation.core continuation.unwind continuation.cps continuation.delimited continuation');
return (function (gensym_2_gmjsv9bw_4u1rkj){this.configure('parser.core').parser.defparser('alt',(function (){return (function (as){return (function (state){return as.exists((function (_,_i){return _(state)}))})}).call(this,(new gensym_2_gmjsv9bw_4u1rl1.seq.finite(arguments)))}))})})())).tconfiguration('std opt seq continuation','parser.times',caterwaul.precompiled_internal((function (){var gensym_2_gmjsv9bw_4u1rl3=caterwaul.clone('std.qs std.qg std.bind std.lvalue std.cond std.fn std.obj std.ref std.string std opt.unroll opt seq.core seq.finite.core seq.finite.object seq.finite.mutability seq.finite.traversal seq.finite.zip seq.finite.quantification seq.finite.serialization seq.infinite.core seq.infinite.y seq.infinite.transform seq.infinite.traversal seq.numeric seq.dsl seq continuation.core continuation.unwind continuation.cps continuation.delimited continuation');
var gensym_2_gmjsv9bw_4u1rl4=gensym_2_gmjsv9bw_4u1rl3;
var gensym_2_gmjsv9bw_4u1rl5=gensym_2_gmjsv9bw_4u1rl3;
return (function (gensym_2_gmjsv9bw_4u1rkk){this.configure('parser.core').parser.defparser('times',(function (p,lower,upper){return (function (state){return (function (count,result){return (gensym_2_gmjsv9bw_4u1rl3.continuation.call_cc.call(this,(function (cc){return (function (gensym_2_gmjsv9bw_4u1rf5){for (var gensym_2_gmjsv9bw_4u1rf6=gensym_2_gmjsv9bw_4u1rf5>=0&&gensym_2_gmjsv9bw_4u1rf5>>3,gensym_2_gmjsv9bw_4u1rf7=gensym_2_gmjsv9bw_4u1rf5>=0&&gensym_2_gmjsv9bw_4u1rf5&7,i=0;
i<gensym_2_gmjsv9bw_4u1rf7;
 ++i) ++count,(state=p(state))?result.push(state.result):cc(false);
for (var gensym_2_gmjsv9bw_4u1rf8=0;
gensym_2_gmjsv9bw_4u1rf8<gensym_2_gmjsv9bw_4u1rf6;
 ++gensym_2_gmjsv9bw_4u1rf8){ ++count,(state=p(state))?result.push(state.result):cc(false);
i++;
 ++count,(state=p(state))?result.push(state.result):cc(false);
i++;
 ++count,(state=p(state))?result.push(state.result):cc(false);
i++;
 ++count,(state=p(state))?result.push(state.result):cc(false);
i++;
 ++count,(state=p(state))?result.push(state.result):cc(false);
i++;
 ++count,(state=p(state))?result.push(state.result):cc(false);
i++;
 ++count,(state=p(state))?result.push(state.result):cc(false);
i++;
 ++count,(state=p(state))?result.push(state.result):cc(false);
i++};
return gensym_2_gmjsv9bw_4u1rf5}).call(this,lower),true})))&&(gensym_2_gmjsv9bw_4u1rl4.continuation.call_cc.call(this,(function (){var loop=(function (cc){return ( !upper||count++<upper)&&state.has_input()&&((function (_){return (_)&&(state=_),_})).call(this,p(state))?result.push(state.result)&&(gensym_2_gmjsv9bw_4u1rl5.continuation.call_tail.call(loop,cc)):cc(state.accept(state.i,result))});
return loop}).call(this)))}).call(this,0,[])})}))})})())).tconfiguration('std opt seq continuation','parser.opt',caterwaul.precompiled_internal((function (){null;
return (function (gensym_2_gmjsv9bw_4u1rkl){this.configure('parser.core').parser.defparser('opt',(function (p){return (function (state){return (function (){var s=p(state),n=s?s.i:state.i,r=s&&s.result;
return state.accept(n,r)}).call(this)})}))})})())).tconfiguration('std opt seq continuation','parser.match',caterwaul.precompiled_internal((function (){null;
return (function (gensym_2_gmjsv9bw_4u1rkm){((function (_){return _.defparser('match',(function (p){return (function (state){return ((function (_){return _&&state.accept(state.i,state.result)})).call(this,p(state))})})),_.defparser('reject',(function (p){return (function (state){return ((function (_){return  !_&&state.accept(state.i,null)})).call(this,p(state))})})),_})).call(this,this.configure('parser.core').parser)})})())).tconfiguration('std opt seq continuation','parser.bind',caterwaul.precompiled_internal((function (){null;
return (function (gensym_2_gmjsv9bw_4u1rkn){((function (_){return _.defparser('bind',(function (p,f){return (function (state){return ((function (_){return _&&_.accept(_.i,f.call(_,_.result))})).call(this,p(state))})})),_})).call(this,this.configure('parser.core').parser)})})())).tconfiguration('std opt seq continuation','parser.dsl',caterwaul.precompiled_internal((function (){var gensym_2_gmjsv9bw_4u1rla=caterwaul.parse('peg[_]');
var gensym_2_gmjsv9bw_4u1rlb=caterwaul.parse('qg[l*[_bindings][_parser]]');
var gensym_2_gmjsv9bw_4u1rlc=caterwaul.clone('std.qs std.qg std.bind std.lvalue std.cond std.fn std.obj std.ref std.string std opt.unroll opt seq.core seq.finite.core seq.finite.object seq.finite.mutability seq.finite.traversal seq.finite.zip seq.finite.quantification seq.finite.serialization seq.infinite.core seq.infinite.y seq.infinite.transform seq.infinite.traversal seq.numeric seq.dsl seq continuation.core continuation.unwind continuation.cps continuation.delimited continuation');
var gensym_2_gmjsv9bw_4u1rld=caterwaul.parse('_x=_y');
var gensym_2_gmjsv9bw_4u1rle=caterwaul.parse('_name(_x,_y)');
var gensym_2_gmjsv9bw_4u1rlf=caterwaul.parse('_name(_x,_y)');
var gensym_2_gmjsv9bw_4u1rlg=caterwaul.parse('_name(_x)');
var gensym_2_gmjsv9bw_4u1rlh=caterwaul.parse('_(_)');
var gensym_2_gmjsv9bw_4u1rli=caterwaul.parse('_x(_y)');
var gensym_2_gmjsv9bw_4u1rlj=caterwaul.parse('_/_');
var gensym_2_gmjsv9bw_4u1rlk=caterwaul.parse('_%_');
var gensym_2_gmjsv9bw_4u1rll=caterwaul.parse('_>>_');
var gensym_2_gmjsv9bw_4u1rlm=caterwaul.parse('[_]');
var gensym_2_gmjsv9bw_4u1rln=caterwaul.parse('_');
var gensym_2_gmjsv9bw_4u1rlo=caterwaul.parse('_[_]');
var gensym_2_gmjsv9bw_4u1rlp=caterwaul.parse('times(_x,_l)');
var gensym_2_gmjsv9bw_4u1rlq=caterwaul.parse('_[_,_]');
var gensym_2_gmjsv9bw_4u1rlr=caterwaul.parse('times(_x,_l,_u)');
var gensym_2_gmjsv9bw_4u1rls=gensym_2_gmjsv9bw_4u1rlc;
return (function (gensym_2_gmjsv9bw_4u1rko){this.configure('parser.core').rmacro(gensym_2_gmjsv9bw_4u1rla,(function (x){return (function (outer){return gensym_2_gmjsv9bw_4u1rlb.replace({_bindings:new this.syntax(',',gensym_2_gmjsv9bw_4u1rlc.seq.finite.pairs(this.parser.parsers).map((function (_,_i){return gensym_2_gmjsv9bw_4u1rld.replace({_x:_[0],_y:new outer.ref(_[1])})}))),_parser:this.parser.dsl.macroexpand(x)})}).call(this,this)})),this.parser.dsl=((function (dsl){return ((function (_){return (function (){var e=dsl.macroexpand,fb=(function (op,name){return (function (x,y){return gensym_2_gmjsv9bw_4u1rle.replace({_name:name,_x:((function (_){return _.data=',',_})).call(this,x.flatten(op).map(e)),_y:e(y)})})}),b=(function (name){return (function (x,y){return gensym_2_gmjsv9bw_4u1rlf.replace({_name:name,_x:e(x),_y:y})})}),u=(function (name){return (function (x){return gensym_2_gmjsv9bw_4u1rlg.replace({_name:name,_x:e(x)})})});
return _(gensym_2_gmjsv9bw_4u1rlh,(function (x,y){return gensym_2_gmjsv9bw_4u1rli.replace({_x:e(x),_y:y})})),_(gensym_2_gmjsv9bw_4u1rlj,fb('/','alt')),_(gensym_2_gmjsv9bw_4u1rlk,fb('%','seq')),_(gensym_2_gmjsv9bw_4u1rll,b('bind')),_(gensym_2_gmjsv9bw_4u1rlm,u('opt')),_(gensym_2_gmjsv9bw_4u1rln.as('('),(function (x){return e(x).as('(')})),_(gensym_2_gmjsv9bw_4u1rlo,(function (x,l){return gensym_2_gmjsv9bw_4u1rlp.replace({_x:e(x),_l:l})})),_(gensym_2_gmjsv9bw_4u1rlq,(function (x,l,u){return gensym_2_gmjsv9bw_4u1rlr.replace({_x:e(x),_l:l,_u:u})}))}).call(this),_})).call(this,dsl.macro),dsl})).call(this,gensym_2_gmjsv9bw_4u1rls.global().clone())})})())).configuration('parser',function (gensym_2_gmjsv9bw_4u1rkp){this.configure('parser.core parser.c parser.seq parser.alt parser.times parser.opt parser.match parser.bind parser.dsl')});
