// Code generation functions | Spencer Tipping
// Licensed under the terms of the MIT source code license

// Introduction.
// Many Caterwaul functions generate code in common patterns. This module provides functions that handle the most common cases.

  caterwaul.tconfiguration('gen', function () {
    var gen = this.namespace('gen'),
        

    gen.scope = function (vars, body) {
// Generated by SDoc 
