// Node/CommonJS Caterwaul module (preprocessed) | Spencer Tipping
// Licensed under the terms of the MIT source code license

- pinclude pp::js::modules/caterwaul.all.pre

// Expose the Caterwaul global function as an export.

exports.caterwaul = caterwaul;
// Generated by SDoc 
