caterwaul.tconfiguration('std','seq.core',caterwaul.precompiled_internal((function (){null;
return (function (gensym_2_gmjt2ug2_eud8ut){this.shallow('seq',{core:((function (_){return _.prototype=((function (p){return p.constructor=_,p})).call(this,[]),_})).call(this,(function (){return null}))})})})())).tconfiguration('std opt continuation','seq.finite.core',caterwaul.precompiled_internal((function (){null;
return (function (gensym_2_gmjt2ug2_eud8uu){this.configure('seq.core').seq.finite=((function (c){return c.prototype=((function (_){return _.size=(function (){return this.l||this.length}),_.slice=(function (){return ((function (_){return (function (gensym_2_gmjt2ug2_eud8pi){for (var gensym_2_gmjt2ug2_eud8pj=gensym_2_gmjt2ug2_eud8pi>=0&&gensym_2_gmjt2ug2_eud8pi>>3,gensym_2_gmjt2ug2_eud8pk=gensym_2_gmjt2ug2_eud8pi>=0&&gensym_2_gmjt2ug2_eud8pi&7,i=0;
i<gensym_2_gmjt2ug2_eud8pk;
 ++i)_.push(this[i]);
for (var gensym_2_gmjt2ug2_eud8pl=0;
gensym_2_gmjt2ug2_eud8pl<gensym_2_gmjt2ug2_eud8pj;
 ++gensym_2_gmjt2ug2_eud8pl){_.push(this[i]);
i++;
_.push(this[i]);
i++;
_.push(this[i]);
i++;
_.push(this[i]);
i++;
_.push(this[i]);
i++;
_.push(this[i]);
i++;
_.push(this[i]);
i++;
_.push(this[i]);
i++};
return gensym_2_gmjt2ug2_eud8pi}).call(this,this.size()),_})).call(this,[])}),_.constructor=c,_})).call(this,new this.seq.core()),c})).call(this,((function (xs){return this.length=this.l=xs?(function (gensym_2_gmjt2ug2_eud8pi){for (var gensym_2_gmjt2ug2_eud8pj=gensym_2_gmjt2ug2_eud8pi>=0&&gensym_2_gmjt2ug2_eud8pi>>3,gensym_2_gmjt2ug2_eud8pk=gensym_2_gmjt2ug2_eud8pi>=0&&gensym_2_gmjt2ug2_eud8pi&7,i=0;
i<gensym_2_gmjt2ug2_eud8pk;
 ++i)this[i]=xs[i];
for (var gensym_2_gmjt2ug2_eud8pl=0;
gensym_2_gmjt2ug2_eud8pl<gensym_2_gmjt2ug2_eud8pj;
 ++gensym_2_gmjt2ug2_eud8pl){this[i]=xs[i];
i++;
this[i]=xs[i];
i++;
this[i]=xs[i];
i++;
this[i]=xs[i];
i++;
this[i]=xs[i];
i++;
this[i]=xs[i];
i++;
this[i]=xs[i];
i++;
this[i]=xs[i];
i++};
return gensym_2_gmjt2ug2_eud8pi}).call(this,xs.size?xs.size():xs.length):0,undefined})))})})())).tconfiguration('std opt continuation','seq.finite.serialization',caterwaul.precompiled_internal((function (){null;
return (function (gensym_2_gmjt2ug2_eud8uv){((function (_){return _.toString=(function (){return ('seq['+(this.slice().join(", "))+']')}),_.join=(function (x){return this.slice().join(x)}),_})).call(this,this.configure('seq.finite.core').seq.finite.prototype)})})())).tconfiguration('std opt continuation','seq.finite.mutability',caterwaul.precompiled_internal((function (){null;
return (function (gensym_2_gmjt2ug2_eud8uw){(function (push,slice){return ((function (_){return _.push=(function (){return (function (as){return ((function (_){return this.length=this.l,this})).call(this,(function (gensym_2_gmjt2ug2_eud8pi){for (var gensym_2_gmjt2ug2_eud8pj=gensym_2_gmjt2ug2_eud8pi>=0&&gensym_2_gmjt2ug2_eud8pi>>3,gensym_2_gmjt2ug2_eud8pk=gensym_2_gmjt2ug2_eud8pi>=0&&gensym_2_gmjt2ug2_eud8pi&7,i=0;
i<gensym_2_gmjt2ug2_eud8pk;
 ++i)this[this.l++]=as[i];
for (var gensym_2_gmjt2ug2_eud8pl=0;
gensym_2_gmjt2ug2_eud8pl<gensym_2_gmjt2ug2_eud8pj;
 ++gensym_2_gmjt2ug2_eud8pl){this[this.l++]=as[i];
i++;
this[this.l++]=as[i];
i++;
this[this.l++]=as[i];
i++;
this[this.l++]=as[i];
i++;
this[this.l++]=as[i];
i++;
this[this.l++]=as[i];
i++;
this[this.l++]=as[i];
i++;
this[this.l++]=as[i];
i++};
return gensym_2_gmjt2ug2_eud8pi}).call(this,as.length))}).call(this,arguments)}),_.pop=(function (){return ((function (_){return delete this[this.length=this.l],_})).call(this,this[ --this.l])}),_.concat=(function (xs){return ((function (_){return _.push.apply(_,slice.call(xs)),_})).call(this,new this.constructor(this))}),_})).call(this,this.configure('seq.finite.core').seq.finite.prototype)}).call(this,Array.prototype.push,Array.prototype.slice)})})())).tconfiguration('std opt continuation','seq.finite.object',caterwaul.precompiled_internal((function (){null;
return (function (gensym_2_gmjt2ug2_eud8ux){(function (own){return ((function (_){return _.keys=(function (o,all){return ((function (_){return (function (gensym_2_gmjt2ug2_eud8uy){for (var k in o)if (all||own.call(o,k))_.push(k)})(),_})).call(this,new _())}),_.values=(function (o,all){return ((function (_){return (function (gensym_2_gmjt2ug2_eud8uz){for (var k in o)if (all||own.call(o,k))_.push(o[k])})(),_})).call(this,new _())}),_.pairs=(function (o,all){return ((function (_){return (function (gensym_2_gmjt2ug2_eud8v0){for (var k in o)if (all||own.call(o,k))_.push([k,o[k]])})(),_})).call(this,new _())}),_.prototype.object=(function (o){return ((function (_){return this.each((function (p){return _[p[0]]=p[1]})),_})).call(this,(o||{}))}),_})).call(this,this.configure('seq.finite.core').seq.finite)}).call(this,Object.prototype.hasOwnProperty)})})())).tconfiguration('std opt continuation','seq.finite.traversal',caterwaul.precompiled_internal((function (){null;
return (function (gensym_2_gmjt2ug2_eud8v1){((function (_){return _.map=(function (f){return ((function (_){return (function (gensym_2_gmjt2ug2_eud8pi){for (var gensym_2_gmjt2ug2_eud8pj=gensym_2_gmjt2ug2_eud8pi>=0&&gensym_2_gmjt2ug2_eud8pi>>3,gensym_2_gmjt2ug2_eud8pk=gensym_2_gmjt2ug2_eud8pi>=0&&gensym_2_gmjt2ug2_eud8pi&7,i=0;
i<gensym_2_gmjt2ug2_eud8pk;
 ++i)_.push(f.call(this,this[i],i));
for (var gensym_2_gmjt2ug2_eud8pl=0;
gensym_2_gmjt2ug2_eud8pl<gensym_2_gmjt2ug2_eud8pj;
 ++gensym_2_gmjt2ug2_eud8pl){_.push(f.call(this,this[i],i));
i++;
_.push(f.call(this,this[i],i));
i++;
_.push(f.call(this,this[i],i));
i++;
_.push(f.call(this,this[i],i));
i++;
_.push(f.call(this,this[i],i));
i++;
_.push(f.call(this,this[i],i));
i++;
_.push(f.call(this,this[i],i));
i++;
_.push(f.call(this,this[i],i));
i++};
return gensym_2_gmjt2ug2_eud8pi}).call(this,this.l),_})).call(this,new this.constructor())}),_.filter=(function (f){return ((function (_){return (function (gensym_2_gmjt2ug2_eud8pi){for (var gensym_2_gmjt2ug2_eud8pj=gensym_2_gmjt2ug2_eud8pi>=0&&gensym_2_gmjt2ug2_eud8pi>>3,gensym_2_gmjt2ug2_eud8pk=gensym_2_gmjt2ug2_eud8pi>=0&&gensym_2_gmjt2ug2_eud8pi&7,i=0;
i<gensym_2_gmjt2ug2_eud8pk;
 ++i)(f.call(this,this[i],i))&&(_.push(this[i]));
for (var gensym_2_gmjt2ug2_eud8pl=0;
gensym_2_gmjt2ug2_eud8pl<gensym_2_gmjt2ug2_eud8pj;
 ++gensym_2_gmjt2ug2_eud8pl){(f.call(this,this[i],i))&&(_.push(this[i]));
i++;
(f.call(this,this[i],i))&&(_.push(this[i]));
i++;
(f.call(this,this[i],i))&&(_.push(this[i]));
i++;
(f.call(this,this[i],i))&&(_.push(this[i]));
i++;
(f.call(this,this[i],i))&&(_.push(this[i]));
i++;
(f.call(this,this[i],i))&&(_.push(this[i]));
i++;
(f.call(this,this[i],i))&&(_.push(this[i]));
i++;
(f.call(this,this[i],i))&&(_.push(this[i]));
i++};
return gensym_2_gmjt2ug2_eud8pi}).call(this,this.l),_})).call(this,new this.constructor())}),_.each=(function (f){return ((function (_){return (function (gensym_2_gmjt2ug2_eud8pi){for (var gensym_2_gmjt2ug2_eud8pj=gensym_2_gmjt2ug2_eud8pi>=0&&gensym_2_gmjt2ug2_eud8pi>>3,gensym_2_gmjt2ug2_eud8pk=gensym_2_gmjt2ug2_eud8pi>=0&&gensym_2_gmjt2ug2_eud8pi&7,i=0;
i<gensym_2_gmjt2ug2_eud8pk;
 ++i)f.call(_,_[i],i);
for (var gensym_2_gmjt2ug2_eud8pl=0;
gensym_2_gmjt2ug2_eud8pl<gensym_2_gmjt2ug2_eud8pj;
 ++gensym_2_gmjt2ug2_eud8pl){f.call(_,_[i],i);
i++;
f.call(_,_[i],i);
i++;
f.call(_,_[i],i);
i++;
f.call(_,_[i],i);
i++;
f.call(_,_[i],i);
i++;
f.call(_,_[i],i);
i++;
f.call(_,_[i],i);
i++;
f.call(_,_[i],i);
i++};
return gensym_2_gmjt2ug2_eud8pi}).call(this,_.l),_})).call(this,this)}),_.reversed=(function (){return ((function (_){return (function (l){return (function (gensym_2_gmjt2ug2_eud8pi){for (var gensym_2_gmjt2ug2_eud8pj=gensym_2_gmjt2ug2_eud8pi>=0&&gensym_2_gmjt2ug2_eud8pi>>3,gensym_2_gmjt2ug2_eud8pk=gensym_2_gmjt2ug2_eud8pi>=0&&gensym_2_gmjt2ug2_eud8pi&7,i=0;
i<gensym_2_gmjt2ug2_eud8pk;
 ++i)_.push(this[l-i-1]);
for (var gensym_2_gmjt2ug2_eud8pl=0;
gensym_2_gmjt2ug2_eud8pl<gensym_2_gmjt2ug2_eud8pj;
 ++gensym_2_gmjt2ug2_eud8pl){_.push(this[l-i-1]);
i++;
_.push(this[l-i-1]);
i++;
_.push(this[l-i-1]);
i++;
_.push(this[l-i-1]);
i++;
_.push(this[l-i-1]);
i++;
_.push(this[l-i-1]);
i++;
_.push(this[l-i-1]);
i++;
_.push(this[l-i-1]);
i++};
return gensym_2_gmjt2ug2_eud8pi}).call(this,l)}).call(this,this.l),_})).call(this,new this.constructor())}),_.flat_map=(function (f){return ((function (_){return this.each((function (x,xi){return (((function (xs){return xs.each?xs:new this.constructor(xs)})).call(this,f.call(this,x,xi))).each((function (x){return _.push(x)}))})),_})).call(this,new this.constructor())}),_.foldl=(function (f,x){return (function (x,xi){return (this.l>=xi)&&((function (gensym_2_gmjt2ug2_eud8pi){for (var gensym_2_gmjt2ug2_eud8pj=gensym_2_gmjt2ug2_eud8pi>=0&&gensym_2_gmjt2ug2_eud8pi>>3,gensym_2_gmjt2ug2_eud8pk=gensym_2_gmjt2ug2_eud8pi>=0&&gensym_2_gmjt2ug2_eud8pi&7,i=0;
i<gensym_2_gmjt2ug2_eud8pk;
 ++i)x=f.call(this,x,this[i+xi],i+xi);
for (var gensym_2_gmjt2ug2_eud8pl=0;
gensym_2_gmjt2ug2_eud8pl<gensym_2_gmjt2ug2_eud8pj;
 ++gensym_2_gmjt2ug2_eud8pl){x=f.call(this,x,this[i+xi],i+xi);
i++;
x=f.call(this,x,this[i+xi],i+xi);
i++;
x=f.call(this,x,this[i+xi],i+xi);
i++;
x=f.call(this,x,this[i+xi],i+xi);
i++;
x=f.call(this,x,this[i+xi],i+xi);
i++;
x=f.call(this,x,this[i+xi],i+xi);
i++;
x=f.call(this,x,this[i+xi],i+xi);
i++;
x=f.call(this,x,this[i+xi],i+xi);
i++};
return gensym_2_gmjt2ug2_eud8pi}).call(this,this.l-xi),x)}).call(this,arguments.length>1?x:this[0],2-arguments.length)}),_.foldr=(function (f,x){return (function (x,xi,l){return (l>=xi-1)&&((function (gensym_2_gmjt2ug2_eud8pi){for (var gensym_2_gmjt2ug2_eud8pj=gensym_2_gmjt2ug2_eud8pi>=0&&gensym_2_gmjt2ug2_eud8pi>>3,gensym_2_gmjt2ug2_eud8pk=gensym_2_gmjt2ug2_eud8pi>=0&&gensym_2_gmjt2ug2_eud8pi&7,i=0;
i<gensym_2_gmjt2ug2_eud8pk;
 ++i)x=f.call(this,this[l-(i+xi)],x,l-(i+xi));
for (var gensym_2_gmjt2ug2_eud8pl=0;
gensym_2_gmjt2ug2_eud8pl<gensym_2_gmjt2ug2_eud8pj;
 ++gensym_2_gmjt2ug2_eud8pl){x=f.call(this,this[l-(i+xi)],x,l-(i+xi));
i++;
x=f.call(this,this[l-(i+xi)],x,l-(i+xi));
i++;
x=f.call(this,this[l-(i+xi)],x,l-(i+xi));
i++;
x=f.call(this,this[l-(i+xi)],x,l-(i+xi));
i++;
x=f.call(this,this[l-(i+xi)],x,l-(i+xi));
i++;
x=f.call(this,this[l-(i+xi)],x,l-(i+xi));
i++;
x=f.call(this,this[l-(i+xi)],x,l-(i+xi));
i++;
x=f.call(this,this[l-(i+xi)],x,l-(i+xi));
i++};
return gensym_2_gmjt2ug2_eud8pi}).call(this,l-(xi-1)),x)}).call(this,arguments.length>1?x:this[this.l-1],3-arguments.length,this.l)}),_})).call(this,this.configure('seq.finite.core seq.finite.mutability').seq.finite.prototype)})})())).tconfiguration('std opt continuation','seq.finite.zip',caterwaul.precompiled_internal((function (){var gensym_2_gmjt2ug2_eud8vi=caterwaul.clone('std.qs std.qg std.bind std.lvalue std.cond std.fn std.obj std.ref std.string std opt.unroll opt continuation.core continuation.unwind continuation.cps continuation.delimited continuation');
return (function (gensym_2_gmjt2ug2_eud8v2){((function (_){return (function (seq,slice){return _.prototype.zip=(function (){return (function (as,options){return (as[as.size()-1].constructor===Object)&&(gensym_2_gmjt2ug2_eud8vi.util.merge(options,as.pop())),(function (l,f){return ((function (_){return (function (gensym_2_gmjt2ug2_eud8pi){for (var gensym_2_gmjt2ug2_eud8pj=gensym_2_gmjt2ug2_eud8pi>=0&&gensym_2_gmjt2ug2_eud8pi>>3,gensym_2_gmjt2ug2_eud8pk=gensym_2_gmjt2ug2_eud8pi>=0&&gensym_2_gmjt2ug2_eud8pi&7,i=0;
i<gensym_2_gmjt2ug2_eud8pk;
 ++i)_.push(f.apply({i:i},as.map((function (x){return x[i]})).slice()));
for (var gensym_2_gmjt2ug2_eud8pl=0;
gensym_2_gmjt2ug2_eud8pl<gensym_2_gmjt2ug2_eud8pj;
 ++gensym_2_gmjt2ug2_eud8pl){_.push(f.apply({i:i},as.map((function (x){return x[i]})).slice()));
i++;
_.push(f.apply({i:i},as.map((function (x){return x[i]})).slice()));
i++;
_.push(f.apply({i:i},as.map((function (x){return x[i]})).slice()));
i++;
_.push(f.apply({i:i},as.map((function (x){return x[i]})).slice()));
i++;
_.push(f.apply({i:i},as.map((function (x){return x[i]})).slice()));
i++;
_.push(f.apply({i:i},as.map((function (x){return x[i]})).slice()));
i++;
_.push(f.apply({i:i},as.map((function (x){return x[i]})).slice()));
i++;
_.push(f.apply({i:i},as.map((function (x){return x[i]})).slice()));
i++};
return gensym_2_gmjt2ug2_eud8pi}).call(this,l),_})).call(this,new this.constructor())}).call(this,as.map((function (x){return x.size?x.size():x.length})).foldl(options.outer?(function (x,y){return Math.max(x,y)}):(function (x,y){return Math.min(x,y)})),options.f)}).call(this,new seq([this].concat(slice.call(arguments))),{f:(function (){return new seq(arguments)}),outer:false})})}).call(this,_,Array.prototype.slice),_})).call(this,this.configure('seq.finite.traversal').seq.finite)})})())).tconfiguration('std opt continuation','seq.finite.quantification',caterwaul.precompiled_internal((function (){var gensym_2_gmjt2ug2_eud8vk=caterwaul.clone('std.qs std.qg std.bind std.lvalue std.cond std.fn std.obj std.ref std.string std opt.unroll opt continuation.core continuation.unwind continuation.cps continuation.delimited continuation');
return (function (gensym_2_gmjt2ug2_eud8v3){((function (_){return _.exists=(function (f){return (gensym_2_gmjt2ug2_eud8vk.continuation.call_cc.call(this,(function (gensym_2_gmjt2ug2_eud8vl){return (function (){return (function (cc){return (function (gensym_2_gmjt2ug2_eud8pi){for (var gensym_2_gmjt2ug2_eud8pj=gensym_2_gmjt2ug2_eud8pi>=0&&gensym_2_gmjt2ug2_eud8pi>>3,gensym_2_gmjt2ug2_eud8pk=gensym_2_gmjt2ug2_eud8pi>=0&&gensym_2_gmjt2ug2_eud8pi&7,i=0;
i<gensym_2_gmjt2ug2_eud8pk;
 ++i)((function (_){return _&&cc(_)})).call(this,f.call(this,this[i],i));
for (var gensym_2_gmjt2ug2_eud8pl=0;
gensym_2_gmjt2ug2_eud8pl<gensym_2_gmjt2ug2_eud8pj;
 ++gensym_2_gmjt2ug2_eud8pl){((function (_){return _&&cc(_)})).call(this,f.call(this,this[i],i));
i++;
((function (_){return _&&cc(_)})).call(this,f.call(this,this[i],i));
i++;
((function (_){return _&&cc(_)})).call(this,f.call(this,this[i],i));
i++;
((function (_){return _&&cc(_)})).call(this,f.call(this,this[i],i));
i++;
((function (_){return _&&cc(_)})).call(this,f.call(this,this[i],i));
i++;
((function (_){return _&&cc(_)})).call(this,f.call(this,this[i],i));
i++;
((function (_){return _&&cc(_)})).call(this,f.call(this,this[i],i));
i++;
((function (_){return _&&cc(_)})).call(this,f.call(this,this[i],i));
i++};
return gensym_2_gmjt2ug2_eud8pi}).call(this,this.l),false}).apply(gensym_2_gmjt2ug2_eud8vl,arguments)})})(this)))}),_.forall=(function (f){return  !this.exists((function (){return  !f.apply(this,arguments)}))}),_})).call(this,this.configure('seq.finite.core').seq.finite.prototype)})})())).tconfiguration('std opt continuation','seq.infinite.core',caterwaul.precompiled_internal((function (){null;
return (function (gensym_2_gmjt2ug2_eud8v4){this.configure('seq.core').seq.infinite=((function (_){return (function (i){return _.def=(function (name,ctor,h,t){return i[name]=((function (_){return _.prototype=((function (_){return _.h=h,_.t=t,_.constructor=ctor,_})).call(this,new i()),_})).call(this,ctor)})}).call(this,_),_.def('cons',(function (h,t){return this._h=h,this._t=t}),(function (){return this._h}),(function (){return this._t})),_.def('k',(function (x){return this._x=x}),(function (){return this._x}),(function (){return this})),_})).call(this,((function (_){return (function (ctor){return _.prototype=((function (_){return _.constructor=ctor,_})).call(this,new this.seq.core())}).call(this,_),_})).call(this,(function (){return null})))})})())).tconfiguration('std opt continuation','seq.infinite.y',caterwaul.precompiled_internal((function (){null;
return (function (gensym_2_gmjt2ug2_eud8v5){this.configure('seq.infinite.core').seq.infinite.def('y',((function (f,x){return this._f=f,this._x=x,undefined})),(function (){return this._x}),(function (){return new this.constructor(this._f,this._f(this._x))}))})})())).tconfiguration('std opt continuation','seq.infinite.transform',caterwaul.precompiled_internal((function (){var gensym_2_gmjt2ug2_eud8vp=caterwaul.clone('std.qs std.qg std.bind std.lvalue std.cond std.fn std.obj std.ref std.string std opt.unroll opt continuation.core continuation.unwind continuation.cps continuation.delimited continuation');
var gensym_2_gmjt2ug2_eud8vq=gensym_2_gmjt2ug2_eud8vp;
return (function (gensym_2_gmjt2ug2_eud8v6){((function (_){return _.prototype.map=(function (f){return new _.map(f,this)}),_.def('map',((function (f,xs){return this._f=f,this._xs=xs,undefined})),(function (){return this._f(this._xs.h())}),(function (){return new this.constructor(this._f,this._xs.t())})),_.prototype.filter=(function (f){return new _.filter(f,this)}),_.def('filter',((function (f,xs){return this._f=f,this._xs=(function (){var next=(function (s){return (function (cc){return f(s.h())?cc(s):(gensym_2_gmjt2ug2_eud8vp.continuation.call_tail.call(next(s.t()),cc))})});
return (gensym_2_gmjt2ug2_eud8vq.continuation.call_cc.call(this,next(xs)))}).call(this),undefined})),(function (){return this._xs.h()}),(function (){return new this.constructor(this._f,this._xs.t())})),_})).call(this,this.configure('seq.infinite.core').seq.infinite)})})())).tconfiguration('std opt continuation','seq.infinite.traversal',caterwaul.precompiled_internal((function (){var gensym_2_gmjt2ug2_eud8vs=caterwaul.clone('std.qs std.qg std.bind std.lvalue std.cond std.fn std.obj std.ref std.string std opt.unroll opt continuation.core continuation.unwind continuation.cps continuation.delimited continuation');
var gensym_2_gmjt2ug2_eud8vt=gensym_2_gmjt2ug2_eud8vs;
var gensym_2_gmjt2ug2_eud8vu=gensym_2_gmjt2ug2_eud8vs;
var gensym_2_gmjt2ug2_eud8vv=gensym_2_gmjt2ug2_eud8vs;
return (function (gensym_2_gmjt2ug2_eud8v7){(function (finite){return ((function (_){return _.drop=(function (f){return (function (){var next=(function (s){return (function (cc){return f(s.h())?(gensym_2_gmjt2ug2_eud8vs.continuation.call_tail.call(next(s.t()),cc)):cc(s)})});
return (gensym_2_gmjt2ug2_eud8vt.continuation.call_cc.call(this,next(this)))}).call(this)}),_.take=(function (f){return (function (){var xs=new finite(),next=(function (s){return (function (cc){return (function (h){return f(h)?(xs.push(h),(gensym_2_gmjt2ug2_eud8vu.continuation.call_tail.call(next(s.t()),cc))):cc(xs)}).call(this,s.h())})});
return (gensym_2_gmjt2ug2_eud8vv.continuation.call_cc.call(this,next(this)))}).call(this)}),_})).call(this,this.configure('seq.infinite.core').seq.infinite.prototype)}).call(this,this.configure('seq.finite.core seq.finite.mutability').seq.finite)})})())).tconfiguration('std opt continuation','seq.numeric',caterwaul.precompiled_internal((function (){null;
return (function (gensym_2_gmjt2ug2_eud8v8){((function (_){return _.naturals_from=(function (x){return new _.infinite.y((function (n){return n+1}),x)}),_.naturals=_.naturals_from(0),_.n=(function (l,u,s){return (function (lower,upper){return (function (step){return new _.infinite.y((function (n){return n+step}),lower).take((function (x){return (upper-lower)*(upper-x)>0}))}).call(this,Math.abs(s||1)*(lower<upper?1: -1))}).call(this,arguments.length>1?l:0,arguments.length>1?u:l)}),_})).call(this,this.configure('seq.infinite.core seq.infinite.y seq.finite.core').seq)})})())).tconfiguration('std opt continuation','seq.dsl',caterwaul.precompiled_internal((function (){var gensym_2_gmjt2ug2_eud8vz=caterwaul.parse(' -x');
var gensym_2_gmjt2ug2_eud8w0=caterwaul.parse('[_]');
var gensym_2_gmjt2ug2_eud8w1=caterwaul.parse('_[_]');
var gensym_2_gmjt2ug2_eud8w2=caterwaul.parse(' +_');
var gensym_2_gmjt2ug2_eud8w3=caterwaul.parse('_+x');
var gensym_2_gmjt2ug2_eud8w4=caterwaul.clone('std.qs std.qg std.bind std.lvalue std.cond std.fn std.obj std.ref std.string std opt.unroll opt continuation.core continuation.unwind continuation.cps continuation.delimited continuation');
var gensym_2_gmjt2ug2_eud8w5=caterwaul.parse('qg[fn[f][fn_[ !f.apply(this,arguments)]]]');
var gensym_2_gmjt2ug2_eud8w6=caterwaul.parse('fn[xs][y]');
var gensym_2_gmjt2ug2_eud8w7=caterwaul.parse('fb');
var gensym_2_gmjt2ug2_eud8w8=caterwaul.parse('fn');
var gensym_2_gmjt2ug2_eud8w9=caterwaul.parse('_x.filter(_y)');
var gensym_2_gmjt2ug2_eud8wa=caterwaul.parse('_,_i');
var gensym_2_gmjt2ug2_eud8wb=caterwaul.parse('_x.map(_y)');
var gensym_2_gmjt2ug2_eud8wc=caterwaul.parse('_,_i');
var gensym_2_gmjt2ug2_eud8wd=caterwaul.parse('_x.foldl(_y)');
var gensym_2_gmjt2ug2_eud8we=caterwaul.parse('_,_0,_i');
var gensym_2_gmjt2ug2_eud8wf=caterwaul.parse('_x.filter(c(_y))');
var gensym_2_gmjt2ug2_eud8wg=caterwaul.parse('_,_i');
var gensym_2_gmjt2ug2_eud8wh=caterwaul.parse('_x.each(_y)');
var gensym_2_gmjt2ug2_eud8wi=caterwaul.parse('_,_i');
var gensym_2_gmjt2ug2_eud8wj=caterwaul.parse('_x.foldr(_y)');
var gensym_2_gmjt2ug2_eud8wk=caterwaul.parse('_,_0,_i');
var gensym_2_gmjt2ug2_eud8wl=caterwaul.parse('_x.forall(_y)');
var gensym_2_gmjt2ug2_eud8wm=caterwaul.parse('_,_i');
var gensym_2_gmjt2ug2_eud8wn=caterwaul.parse('_x.exists(_y)');
var gensym_2_gmjt2ug2_eud8wo=caterwaul.parse('_,_i');
var gensym_2_gmjt2ug2_eud8wp=caterwaul.parse('_x.flat_map(_y)');
var gensym_2_gmjt2ug2_eud8wq=caterwaul.parse('_,_i');
var gensym_2_gmjt2ug2_eud8wr=caterwaul.parse('_x.drop(_y)');
var gensym_2_gmjt2ug2_eud8ws=caterwaul.parse('_');
var gensym_2_gmjt2ug2_eud8wt=caterwaul.parse('_x.take(_y)');
var gensym_2_gmjt2ug2_eud8wu=caterwaul.parse('_');
var gensym_2_gmjt2ug2_eud8wv=caterwaul.parse('new caterwaul.seq.infinite.y(_y,_x)');
var gensym_2_gmjt2ug2_eud8ww=caterwaul.parse('_');
var gensym_2_gmjt2ug2_eud8wx=caterwaul.parse('_+_');
var gensym_2_gmjt2ug2_eud8wy=caterwaul.parse('qg[_x].size()+qg[_y].size()');
var gensym_2_gmjt2ug2_eud8wz=caterwaul.parse('_&&_');
var gensym_2_gmjt2ug2_eud8x0=caterwaul.parse('((function (xp){return xp&&xp.size()?_y:xp}).call(this,_x))');
var gensym_2_gmjt2ug2_eud8x1=caterwaul.parse('_||_');
var gensym_2_gmjt2ug2_eud8x2=caterwaul.parse('((function (xp){return xp&&xp.size()?xp:_y}).call(this,_x))');
var gensym_2_gmjt2ug2_eud8x3=caterwaul.parse('_===_');
var gensym_2_gmjt2ug2_eud8x4=caterwaul.parse('qg[l[xp=_x,yp=_y][xp===yp||xp.size()===yp.size()&&xp.zip(yp).forall(fn[p][p[0]===p[1]])]]');
var gensym_2_gmjt2ug2_eud8x5=caterwaul.parse('_!==_');
var gensym_2_gmjt2ug2_eud8x6=caterwaul.parse('qg[l[xp=_x,yp=_y][xp!==yp&&(xp.size()!==yp.size()||xp.zip(yp).exists(fn[p][p[0]!==p[1]]))]]');
var gensym_2_gmjt2ug2_eud8x7=caterwaul.parse('_^_');
var gensym_2_gmjt2ug2_eud8x8=caterwaul.parse('_x.zip(_y)');
var gensym_2_gmjt2ug2_eud8x9=caterwaul.parse('_+_');
var gensym_2_gmjt2ug2_eud8xa=caterwaul.parse('_x.concat(_y)');
var gensym_2_gmjt2ug2_eud8xb=caterwaul.parse(' !_');
var gensym_2_gmjt2ug2_eud8xc=caterwaul.parse('_x.object()');
var gensym_2_gmjt2ug2_eud8xd=caterwaul.parse('_,_');
var gensym_2_gmjt2ug2_eud8xe=caterwaul.parse('_x,_y');
var gensym_2_gmjt2ug2_eud8xf=caterwaul.parse(' ~_');
var gensym_2_gmjt2ug2_eud8xg=caterwaul.parse('qg[new caterwaul.seq.finite(_x)]');
var gensym_2_gmjt2ug2_eud8xh=caterwaul.parse('_?_:_');
var gensym_2_gmjt2ug2_eud8xi=caterwaul.parse('x?y:z');
var gensym_2_gmjt2ug2_eud8xj=caterwaul.parse('_(_)');
var gensym_2_gmjt2ug2_eud8xk=caterwaul.parse('_x(_y)');
var gensym_2_gmjt2ug2_eud8xl=caterwaul.parse('_[_]');
var gensym_2_gmjt2ug2_eud8xm=caterwaul.parse('_x[_y]');
var gensym_2_gmjt2ug2_eud8xn=caterwaul.parse('_._');
var gensym_2_gmjt2ug2_eud8xo=caterwaul.parse('_x._y');
var gensym_2_gmjt2ug2_eud8xp=caterwaul.parse('_');
var gensym_2_gmjt2ug2_eud8xq=caterwaul.parse('qg[_x]');
var gensym_2_gmjt2ug2_eud8xr=caterwaul.parse(' +_');
var gensym_2_gmjt2ug2_eud8xs=caterwaul.parse('N');
var gensym_2_gmjt2ug2_eud8xt=caterwaul.parse('caterwaul.seq.naturals');
var gensym_2_gmjt2ug2_eud8xu=caterwaul.parse('N[_]');
var gensym_2_gmjt2ug2_eud8xv=caterwaul.parse('caterwaul.seq.naturals_from(x)');
var gensym_2_gmjt2ug2_eud8xw=caterwaul.parse('n[_]');
var gensym_2_gmjt2ug2_eud8xx=caterwaul.parse('caterwaul.seq.n(x)');
var gensym_2_gmjt2ug2_eud8xz=caterwaul.parse('p[_]');
var gensym_2_gmjt2ug2_eud8y0=caterwaul.parse('caterwaul.seq.finite.r(x)');
var gensym_2_gmjt2ug2_eud8y1=caterwaul.parse('seq[_]');
var gensym_2_gmjt2ug2_eud8y2=gensym_2_gmjt2ug2_eud8w4;
return (function (gensym_2_gmjt2ug2_eud8v9){this.configure('seq.core seq.infinite.y seq.finite.core seq.finite.zip seq.finite.traversal seq.finite.mutability').seq.dsl=((function (_){return (function (){var rxy=(function (tree){return (function (x,y){return tree.replace({_x:_.macroexpand(x),_y:y&&_.macroexpand(y)})})}),seq=(function (gensym_2_gmjt2ug2_eud8vy){return (function (){return (function (xs){return new this.seq.finite(xs)}).apply(gensym_2_gmjt2ug2_eud8vy,arguments)})})(this),prepend=(function (operator){return (function (x){return ((function (_){return _.data=operator,_})).call(this,gensym_2_gmjt2ug2_eud8vz.replace({x:x}))})}),tree_forms=(function (){var base=seq([gensym_2_gmjt2ug2_eud8w0,gensym_2_gmjt2ug2_eud8w1]),mod=(function (fs,op){return fs.concat(fs.map(prepend(op)))});
return mod(mod(base,'u-'),'u~').concat(seq([gensym_2_gmjt2ug2_eud8w2]))}).call(this),template=(function (op){return (function (t){return ((function (_){return _.data=op,_})).call(this,gensym_2_gmjt2ug2_eud8w3.replace({x:t}))})}),qw=gensym_2_gmjt2ug2_eud8w4.util.qw,not=gensym_2_gmjt2ug2_eud8w5,trees_for=(function (op){return ((function (_){return _.map(template(op.replace(/!$/,'')))})).call(this,((function (_){return op.charAt(op.length-1)==='!'?_.map(prepend('u!')):_})).call(this,tree_forms))});
return _.prefix_substitute=(function (tree,prefix){return tree.rmap((function (n){return (n.data.charAt(0)==='_')&&(new n.constructor((''+(prefix)+''+(n.data.substring(1))+'')))}))}),_.define_functional=(function (op,expansion,xs){return trees_for(op).map((function (t,i){return _.macro(t,(function (l,v,r){return expansion.replace({_x:_.macroexpand(l),_y:i>=8?v:gensym_2_gmjt2ug2_eud8w6.replace({fn:i&2?gensym_2_gmjt2ug2_eud8w7:gensym_2_gmjt2ug2_eud8w8,xs:_.prefix_substitute(xs,i&1?v.data:'_'),y:(i&4?_.macroexpand:(function (x){return x}))(r||v)})})}))}))}),((function (_){return _('%',gensym_2_gmjt2ug2_eud8w9,gensym_2_gmjt2ug2_eud8wa),_('*',gensym_2_gmjt2ug2_eud8wb,gensym_2_gmjt2ug2_eud8wc),_('/',gensym_2_gmjt2ug2_eud8wd,gensym_2_gmjt2ug2_eud8we),_('%!',gensym_2_gmjt2ug2_eud8wf.replace({c:not}),gensym_2_gmjt2ug2_eud8wg),_('*!',gensym_2_gmjt2ug2_eud8wh,gensym_2_gmjt2ug2_eud8wi),_('/!',gensym_2_gmjt2ug2_eud8wj,gensym_2_gmjt2ug2_eud8wk),_('&',gensym_2_gmjt2ug2_eud8wl,gensym_2_gmjt2ug2_eud8wm),_('|',gensym_2_gmjt2ug2_eud8wn,gensym_2_gmjt2ug2_eud8wo),_('-',gensym_2_gmjt2ug2_eud8wp,gensym_2_gmjt2ug2_eud8wq),_('>>',gensym_2_gmjt2ug2_eud8wr,gensym_2_gmjt2ug2_eud8ws),_('<<',gensym_2_gmjt2ug2_eud8wt,gensym_2_gmjt2ug2_eud8wu),_('>>>',gensym_2_gmjt2ug2_eud8wv,gensym_2_gmjt2ug2_eud8ww),_})).call(this,_.define_functional),seq(qw('> < >= <= == !=')).each((function (op){return _.macro(((function (_){return _.data=op,_})).call(this,gensym_2_gmjt2ug2_eud8wx.clone()),rxy(((function (_){return _.data=op,_})).call(this,gensym_2_gmjt2ug2_eud8wy.clone())))})),(function (e){return ((function (_){return _(gensym_2_gmjt2ug2_eud8wz,rxy(gensym_2_gmjt2ug2_eud8x0)),_(gensym_2_gmjt2ug2_eud8x1,rxy(gensym_2_gmjt2ug2_eud8x2)),_(gensym_2_gmjt2ug2_eud8x3,rxy(gensym_2_gmjt2ug2_eud8x4)),_(gensym_2_gmjt2ug2_eud8x5,rxy(gensym_2_gmjt2ug2_eud8x6)),_(gensym_2_gmjt2ug2_eud8x7,rxy(gensym_2_gmjt2ug2_eud8x8)),_(gensym_2_gmjt2ug2_eud8x9,rxy(gensym_2_gmjt2ug2_eud8xa)),_(gensym_2_gmjt2ug2_eud8xb,rxy(gensym_2_gmjt2ug2_eud8xc)),_(gensym_2_gmjt2ug2_eud8xd,rxy(gensym_2_gmjt2ug2_eud8xe)),_(gensym_2_gmjt2ug2_eud8xf,rxy(gensym_2_gmjt2ug2_eud8xg)),_(gensym_2_gmjt2ug2_eud8xh,(function (x,y,z){return gensym_2_gmjt2ug2_eud8xi.replace({x:e(x),y:e(y),z:e(z)})})),(function (rx){return _(gensym_2_gmjt2ug2_eud8xj,rx(gensym_2_gmjt2ug2_eud8xk)),_(gensym_2_gmjt2ug2_eud8xl,rx(gensym_2_gmjt2ug2_eud8xm)),_(gensym_2_gmjt2ug2_eud8xn,rx(gensym_2_gmjt2ug2_eud8xo)),_(gensym_2_gmjt2ug2_eud8xp.as('('),rx(gensym_2_gmjt2ug2_eud8xq))}).call(this,(function (t){return (function (x,y){return t.replace({_x:e(x),_y:y})})})),_(gensym_2_gmjt2ug2_eud8xr,(function (x){return x})),(function (rx){return _(gensym_2_gmjt2ug2_eud8xs,(function (){return gensym_2_gmjt2ug2_eud8xt})),_(gensym_2_gmjt2ug2_eud8xu,rx(gensym_2_gmjt2ug2_eud8xv)),_(gensym_2_gmjt2ug2_eud8xw,rx(gensym_2_gmjt2ug2_eud8xx))}).call(this,(function (t){return (function (x){return t.replace({x:x})})})),seq(qw('sk sv sp')).zip(qw('keys values pairs')).each((function (gensym_2_gmjt2ug2_eud8xy){return (function (){return (function (p){return _(gensym_2_gmjt2ug2_eud8xz.replace({p:p[0]}),(function (x){return gensym_2_gmjt2ug2_eud8y0.replace({r:p[1],x:x})}))}).apply(gensym_2_gmjt2ug2_eud8xy,arguments)})})(this)),_})).call(this,_.macro)}).call(this,(function (x){return _.macroexpand(x)})),this.rmacro(gensym_2_gmjt2ug2_eud8y1,_.macroexpand)}).call(this),_})).call(this,gensym_2_gmjt2ug2_eud8y2.global().clone())})})())).configuration('seq',function (gensym_2_gmjt2ug2_eud8va){this.configure('seq.core seq.finite.core seq.finite.object seq.finite.mutability seq.finite.traversal seq.finite.zip seq.finite.quantification '+'seq.finite.serialization seq.infinite.core seq.infinite.y seq.infinite.transform seq.infinite.traversal '+'seq.numeric seq.dsl')});
