#!/bin/bash
rm -f caterwaul.js
sdoc -p . lib test modules modules/*.test

no_rhino=yes
echo 'Note: Not using Rhino due to stack overflow.'

function start() {
  echo starting $*
}

function fail() {
  echo fail $* >> .test-log
  echo -e "\033[1;31mfail $*\033[0;0m:"
  return 1
}

function pass() {
  echo pass $* >> .test-log
}

function run-rhino() {
  start rhino $*
  egrep -vh '^\s*//' "$@" > tmp.js
  rhino -O 9 -debug tmp.js || fail rhino $* || return 1
  rm -f tmp.js
  pass rhino $*
}

function run-v8() {
  start v8 $*
  egrep -vh '^\s*//' "$@" > tmp.js
  node tmp.js || fail v8 $* || return 1
  rm -f tmp.js
  pass v8 $*
}

if [[ $1 == clean ]]; then
  mv -f tmp.js tmp.js.backup
  rm -f modules/*.test/*.js test/*.js *.js
  exit
fi

if [[ $1 == fast || $1 == v8 ]]; then
  no_rhino=yes
  no_full=yes
  shift
fi

if [[ $1 == full ]]; then
  no_min=yes
  shift
fi

if [[ $1 == stable ]]; then
  stable=yes
  version=$2
  shift
  shift
fi

rm -f caterwaul.min.js
node lib/minify.js < caterwaul.js > caterwaul.min.js

if [[ $1 == loc ]]; then
  echo "Total LOC/chars:   $(cat test/*.js caterwaul.js | wc -lm)"
  echo "Comment LOC/chars: $(grep '//' < caterwaul.js | wc -lm)"
  echo "Source LOC/chars:  $(grep -v '//' < caterwaul.js | grep -v '^$' | wc -lm)"
  echo "Test SLOC/chars:   $(cat test/*.js | grep -v '//' | grep -v '^$' | wc -lm)"
  echo "GZip bytes: $(gzip  -c9 caterwaul.min.js | wc -c)"
  exit
fi

rm -f .test-log
for file in test/$1*.js modules/*.test/$1*.js; do
  [[ -z "$no_full" ]]                   && run-v8    caterwaul.js     modules/*.js lib/unit.js $file
  [[ -z "$no_min" ]]                    && run-v8    caterwaul.min.js modules/*.js lib/unit.js $file
  [[ -z "$no_rhino" && -z "$no_full" ]] && run-rhino caterwaul.js     modules/*.js lib/unit.js $file
  [[ -z "$no_rhino" && -z "$no_min" ]]  && run-rhino caterwaul.min.js modules/*.js lib/unit.js $file
done

if [[ ! -z "$stable" ]]; then
  mkdir -p stable/$version
  cp caterwaul.min.js stable/$version
  cp modules/*.min.js stable/$version
fi

grep '^fail' .test-log && $0 clean
echo
