#!/bin/bash
sdoc . lib test

if [[ $1 == debug ]]; then
  debug="lib/divergence.js lib/divergence.rebase.js lib/divergence.debug.js lib/debug.js"
  shift
fi

if [[ $1 == clean ]]; then
  rm -f test/*.js *.js
  exit
fi

if [[ $1 == loc ]]; then
  echo "Total LOC/chars:   $(cat test/*.js caterwaul.js | wc -lm)"
  echo "Comment LOC/chars: $(grep '//' < caterwaul.js | wc -lm)"
  echo "Source LOC/chars:  $(grep -v '//' < caterwaul.js | grep -v '^$' | wc -lm)"
  echo "Test SLOC/chars:   $(cat test/*.js | grep -v '//' | grep -v '^$' | wc -lm)"
  exit
fi

rm -f .test-log
for file in test/$1*.js; do
  echo $file
  ${js:-d8} $debug caterwaul.js lib/unit.js $file
  if [[ $? -eq 0 ]]; then echo pass $file >> .test-log
  else                    echo fail $file >> .test-log
                          echo -e "\033[1;31mfail\033[0;0m: $file"; fi
done

grep '^fail' .test-log && $0 clean
echo
