// Caterwaul JS | Spencer Tipping
// Licensed under the terms of the MIT source code license

// Core caterwaul compiler.
// This is generated from the files in the core/ directory of the source distribution.

- pinclude pp::js::core/caterwaul

// Core behaviors.
// These are pulled from behaviors/core/ and add standard macros and code generation facilities to the core compiler.

- pinclude pp::js::behaviors/core
// Generated by SDoc 
