// Replcable functions | Spencer Tipping
// Licensed under the terms of the MIT source code license

// Introduction.
// Caterwaul makes extensive use of replication as a way to isolate otherwise stateful configuration.
// Generated by SDoc 
