(function (f){return f(f,(function (x){return function (){return  ++x}})(0))})(function (initializer,unique,undefined){var qw=function (x){return x.split(/\s+/)},id=function (x){return x},se=function (x,f){return f&&f.call(x,x)||x},genval=(function (n,m,u){return function (){return [u,n, ++m]}})( +new Date(),Math.random()*(1<<30)>>>0,unique()),genint=function (){var v=genval();
return (v[0]<<2)+v[0]+(v[1]<<1)+v[1]+v[2]},gensym=function (){var v=genval();
return ['gensym',v[0].toString(36),v[1].toString(36),v[2].toString(36)].join('_')},fail=function (m){throw new Error(m)},bind=function (f,t){return f.binding===t?f:f.original?bind(f.original,t):merge(function (){return f.apply(t,arguments)},{original:f,binding:t})},map=function (f,xs){for (var i=0,ys=[],l=xs.length;
i<l;
 ++i)ys.push(f(xs[i],i));
return ys},hash=function (s){for (var i=0,xs=qw(s),o={},l=xs.length;
i<l;
 ++i)o[xs[i]]=true;
return annotate_keys(o)},merge=function (o){for (var i=1,l=arguments.length,_;
i<l;
 ++i)if (_=arguments[i])for (var k in _)has(_,k)&&(o[k]=_[k]);
return o},extend=function (f){merge.apply(null,[f.prototype].concat(Array.prototype.slice.call(arguments,1)));
return f},is_caterwaul=gensym(),max_length_key=gensym(),annotate_keys=function (o){var max=0;
for (var k in o)own.call(o,k)&&(max=k.length>max?k.length:max);
o[max_length_key]=max;
return o},has=function (o,p){return p!=null&& !(p.length>o[max_length_key])&&own.call(o,p)},own=Object.prototype.hasOwnProperty;
var configurable=(function (){var associator_for=function (f){return function (name,behavior,value){return f[name]=(f.behaviors[f.attributes[name]=behavior]||id).call(f,value),f}},shallow_copy=function (x){return x&&(x.constructor===Array?x.slice():x.clone?x.clone():merge({},x))},copy_of=function (f){var g=merge(function (){return g.init.apply(g,arguments)},{behaviors:shallow_copy(f.behaviors),attributes:{}});
return se(g,function (g){(g.associate=associator_for(g))('behavior','method',function (name,definition){this.behaviors[name]=definition;
return this.associate(name,'method',function (attribute,value){return this.associate(attribute,name,value)})}).behavior('method',g.behaviors.method);
for (var k in f.attributes)has(f.attributes,k)&&g.associate(k,f.attributes[k],f[k])})},replica=se(function (){return copy_of({behaviors:{method:function (v){return bind(v,this)}}}).behavior('field').behavior('shallow',shallow_copy).behavior('self_reference',function (){return this})},function (f){f.init=f});
return function (){return replica().shallow('configurations',{}).shallow('has',{}).method('configuration',function (name,f){this.configurations[name]=f;
return this}).method('tconfiguration',function (configs,name,f,bindings){this.configurations[name]=this.clone(configs)(f,bindings);
return this}).method('namespace',function (s){return this[s]||this.shallow(s,{})[s]}).method('alias',function (from,to){return this.method(to,function (){return this[from].apply(this,arguments)})}).method('clone',function (){return arguments.length?this.clone().configure.apply(null,arguments):copy_of(this)}).method('tconfigure',function (cs,f){return this.configure(this.clone(cs)(f))}).method('configure',function (){for (var i=0,l=arguments.length,_;
_=arguments[i],i<l;
 ++i)if (_.constructor===String)for (var cs=qw(arguments[i]),j=0,lj=cs.length;
_=cs[j],j<lj;
 ++j)if (this.configurations[_])this.has[_]||(this.has[_]=this.configurations[_].call(this,this)||this);
else throw new Error('error: configuration "'+_+'" does not exist');
else _ instanceof Array?this.configure.apply(this,_.slice()):_.call(this,this);
return this})}})();
var original_global=typeof caterwaul==='undefined'?undefined:caterwaul,caterwaul_global=caterwaul=se(configurable(),function (){this.deglobalize=function (){caterwaul=original_global;
return this}});
caterwaul_global.method('global',function (){return caterwaul_global}).method('id',function (){return this._id||(this._id=gensym())}).field('is_caterwaul',is_caterwaul).field('initializer',initializer).field('unique',unique).field('gensym',gensym).field('genint',genint).self_reference('caterwaul').method('toString',function (){return '[caterwaul instance '+this.id()+']'}).field('merge',merge).method('check_version',function (){if (original_global&&this.version===original_global.version)this.deglobalize();
return this}).method('reinitialize',function (transform,erase_configurations){var c=(transform||id)(this.initializer),result=c(c,this.unique).deglobalize();
erase_configurations||(result.configurations=this.configurations);
return result}).method('magic',(function (table){return function (name){return table[name]||(table[name]={})}}));
caterwaul_global.method('variadic',function (name,f){return this.method(name,function (){for (var i=0,l=arguments.length;
i<l;
 ++i)f.call(this,arguments[i]);
return this})}).method('right_variadic_binary',function (name,f){return this.method(name,function (){for (var i=0,l=arguments.length-1,x=arguments[l];
i<l;
 ++i)f.call(this,arguments[i],x);
return this})});
var lex_op=hash('. new ++ -- u++ u-- u+ u- typeof u~ u! ! * / % + - << >> >>> < > <= >= instanceof in == != === !== & ^ | && || ? = += -= *= /= %= &= |= ^= <<= >>= >>>= : , '+'return throw case var const break continue void else u; ;'),lex_table=function (s){for (var i=0,xs=[false];
i<8;
 ++i)xs.push.apply(xs,xs);
for (var i=0,l=s.length;
i<l;
 ++i)xs[s.charCodeAt(i)]=true;
return xs},lex_float=lex_table('.0123456789'),lex_decimal=lex_table('0123456789'),lex_integer=lex_table('0123456789abcdefABCDEFx'),lex_exp=lex_table('eE'),lex_space=lex_table(' \n\r\t'),lex_bracket=lex_table('()[]{}'),lex_opener=lex_table('([{'),lex_punct=lex_table('+-*/%&|^!~=<>?:;.,'),lex_eol=lex_table('\n\r'),lex_regexp_suffix=lex_table('gims'),lex_quote=lex_table('\'"/'),lex_slash='/'.charCodeAt(0),lex_star='*'.charCodeAt(0),lex_back='\\'.charCodeAt(0),lex_x='x'.charCodeAt(0),lex_dot='.'.charCodeAt(0),lex_zero='0'.charCodeAt(0),lex_postfix_unary=hash('++ --'),lex_ident=lex_table('$_abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'),parse_reduce_order=map(hash,['function','( [ . [] ()','new delete','u++ u-- ++ -- typeof u~ u! u+ u-','* / %','+ -','<< >> >>>','< > <= >= instanceof in','== != === !==','&','^','|','&&','||','case','?','= += -= *= /= %= &= |= ^= <<= >>= >>>=',':',',','return throw break continue void','var const','if else try catch finally for switch with while do',';']),parse_associates_right=hash('= += -= *= /= %= &= ^= |= <<= >>= >>>= ~ ! new typeof u+ u- -- ++ u-- u++ ? if else function try catch finally for switch case with while do'),parse_inverse_order=(function (xs){for (var o={},i=0,l=xs.length;
i<l;
 ++i)for (var k in xs[i])has(xs[i],k)&&(o[k]=i);
return annotate_keys(o)})(parse_reduce_order),parse_index_forward=(function (rs){for (var xs=[],i=0,l=rs.length,_=null;
_=rs[i],xs[i]=true,i<l;
 ++i)for (var k in _)if (has(_,k)&&(xs[i]=xs[i]&& !has(parse_associates_right,k)))break ;
return xs})(parse_reduce_order),parse_lr=hash('[] . () * / % + - << >> >>> < > <= >= instanceof in == != === !== & ^ | && || = += -= *= /= %= &= |= ^= <<= >>= >>>= , : ;'),parse_r_until_block=annotate_keys({'function':2,'if':1,'do':1,'catch':1,'try':1,'for':1,'while':1,'with':1,'switch':1}),parse_accepts=annotate_keys({'if':'else','do':'while','catch':'finally','try':'catch'}),parse_invocation=hash('[] ()'),parse_r_optional=hash('return throw break continue else'),parse_r=hash('u+ u- u! u~ u++ u-- new typeof finally case var const void delete'),parse_block=hash('; {'),parse_invisible=hash('i;'),parse_l=hash('++ --'),parse_group=annotate_keys({'(':')','[':']','{':'}','?':':'}),parse_ambiguous_group=hash('[ ('),parse_ternary=hash('?'),parse_not_a_value=hash('function if for while catch'),parse_also_expression=hash('function');
(function (){var syntax_node_inspect=function (x){return x?x.inspect():'(<>)'},syntax_node_tostring=function (x){return x?x.serialize?x.serialize():x.toString():''},syntax_common={_replace:function (n){return (n.l=this.l)&&(this.l.r=n),(n.r=this.r)&&(this.r.l=n),this},_append_to:function (n){return n&&n._append(this),this},_reparent:function (n){return this.p&&this.p[0]===this&&(this.p[0]=n),this},_fold_l:function (n){return this._append(this.l&&this.l._unlink(this))},_append:function (n){return (this[this.length++]=n)&&(n.p=this),this},_fold_r:function (n){return this._append(this.r&&this.r._unlink(this))},_sibling:function (n){return n.p=this.p,(this.r=n).l=this},_fold_lr:function (){return this._fold_l()._fold_r()},_wrap:function (n){return n.p=this._replace(n).p,this._reparent(n),delete this.l,delete this.r,this._append_to(n)},_fold_rr:function (){return this._fold_r()._fold_r()},_unlink:function (n){return this.l&&(this.l.r=this.r),this.r&&(this.r.l=this.l),delete this.l,delete this.r,this._reparent(n)},pop:function (){return  --this.length,this},push:function (x){return this[this.length++]=x,this},id:function (){var id=genint();
return (this.id=function (){return id})()},each:function (f){for (var i=0,l=this.length;
i<l;
 ++i)f(this[i],i);
return this},map:function (f){for (var n=new this.constructor(this),i=0,l=this.length;
i<l;
 ++i)n.push(f(this[i],i)||this[i]);
return n},nmap:function (f){for (var n=new this.constructor(this),i=0,l=this.length,r;
i<l;
 ++i)(r=f(this[i],i))&&n.push(r);
return n},reach:function (f){f(this);
this.each(function (n){n&&n.reach(f)});
return this},rmap:function (f){var r=f(this);
return  !r||r===this?this.map(function (n){return n&&n.rmap(f)}):r.data===undefined?new this.constructor(r):r},rnmap:function (f){var r=f(this);
return r===this?this.nmap(function (n){return n&&n.rnmap(f)}):r&&r.data===undefined?new this.constructor(r):r},clone:function (){return this.rmap(function (){return false})},collect:function (p){var ns=[];
this.reach(function (n){p(n)&&ns.push(n)});
return ns},replace:function (rs){return this.rnmap(function (n){if ( !own.call(rs,n.data))return n;
var replacement=rs[n.data];
return replacement&&replacement.constructor===String?new n.constructor(replacement,Array.prototype.slice.call(n)):replacement})},repopulated_with:function (xs){return new this.constructor(this.data,xs)},change:function (i,x){return se(new this.constructor(this.data,Array.prototype.slice.call(this)),function (n){n[i]=x})},compose_single:function (i,f){return this.change(i,f(this[i]))},traverse:function (f){f({entering:this});
f({exiting:this.each(function (n){n&&n.traverse(f)})});
return this},flatten:function (d){d=d||this.data;
return d!==this.data?this.as(d): !(has(parse_lr,d)&&this.length)?this:has(parse_associates_right,d)?se(new this.constructor(d),bind(function (n){for (var i=this;
i&&i.data===d;
i=i[1])n.push(i[0]);
n.push(i)},this)):se(new this.constructor(d),bind(function (n){for (var i=this,ns=[];
i.data===d;
i=i[0])i[1]&&ns.push(i[1]);
ns.push(i);
for (i=ns.length-1;
i>=0;
 --i)n.push(ns[i])},this))},unflatten:function (){var right=has(parse_associates_right,this.data);
return this.length<=2?this:se(new this.constructor(this.data),bind(function (n){if (right)for (var i=0,l=this.length-1;
i<l;
 ++i)n=n.push(this[i]).push(i<l-2?new this.constructor(this.data):this[i])[1];
else for (var i=this.length-1;
i>=1;
 --i)n=n.push(i>1?new this.constructor(this.data):this[0]).push(this[i])[0]},this))},as:function (d){return this.data===d?this:new this.constructor(d).push(this)},is_string:function (){return /['"]/.test(this.data.charAt(0))},as_escaped_string:function (){return this.data.substr(1,this.data.length-2)},is_number:function (){return /^-?(0x|\d|\.\d+)/.test(this.data)},as_number:function (){return Number(this.data)},is_boolean:function (){return this.data==='true'||this.data==='false'},as_boolean:function (){return this.data==='true'},is_regexp:function (){return /^\/./.test(this.data)},as_escaped_regexp:function (){return this.data.substring(1,this.data.lastIndexOf('/'))},is_wildcard:function (){return this.data.charCodeAt(0)===95},has_grouped_block:function (){return has(parse_r_until_block,this.data)},is_block:function (){return has(parse_block,this.data)},is_blockless_keyword:function (){return has(parse_r_optional,this.data)},is_null_or_undefined:function (){return this.data==='null'||this.data==='undefined'},is_constant:function (){return this.is_number()||this.is_string()||this.is_boolean()||this.is_regexp()||this.is_null_or_undefined()},left_is_lvalue:function (){return /=$/.test(this.data)||/\+\+$/.test(this.data)||/--$/.test(this.data)},is_empty:function (){return  !this.length},has_parameter_list:function (){return this.data==='function'||this.data==='catch'},has_lvalue_list:function (){return this.data==='var'||this.data==='const'},is_dereference:function (){return this.data==='.'||this.data==='[]'},is_invocation:function (){return this.data==='()'},is_contextualized_invocation:function (){return this.is_invocation()&&this[0]&&this[0].is_dereference()},is_invisible:function (){return has(parse_invisible,this.data)},is_binary_operator:function (){return has(parse_lr,this.data)},is_prefix_unary_operator:function (){return has(parse_r,this.data)},is_postfix_unary_operator:function (){return has(parse_l,this.data)},is_unary_operator:function (){return this.is_prefix_unary_operator()||this.is_postfix_unary_operator()},accepts:function (e){return parse_accepts[this.data]&&this.accepts[parse.data]===(e.data||e)},bindings:function (hash){var result=hash||{};
this.reach(function (n){if (n.binds_a_value)result[n.data]=n.value});
return result},match:function (target,variables){variables||(variables={all:target});
if (this.is_wildcard())return variables[this.data]=target,variables;
else if (this.length===target.length&&this.data===target.data){for (var i=0,l=this.length;
i<l;
 ++i)if ( !this[i].match(target[i],variables))return null;
return variables}},ends_with_block:function (){var block=this[parse_r_until_block[this.data]];
return this.data==='{'||has(parse_r_until_block,this.data)&&(this.data!=='function'||this.length===3)&&block&&block.ends_with_block()},toString:function (){return 'qs['+this.serialize()+']'},inspect:function (){return this.toString()},structure:function (){return (this.l?'(left) <- ':'')+'('+this.data+(this.length?' '+map(syntax_node_inspect,this).join(' '):'')+')'+(this.r?' -> '+this.r.inspect():'')},serialize:function (xs){var op=this.data,space=op&&/\w/.test(op.charAt(op.length-1))?' ':'';
return op===';'?this.length?map(syntax_node_tostring,this).join(';\n'):';':has(parse_invisible,op)?map(syntax_node_tostring,this).join(space):has(parse_invocation,op)?map(syntax_node_tostring,[this[0],op.charAt(0),this[1],op.charAt(1)]).join(space):has(parse_ternary,op)?map(syntax_node_tostring,[this[0],op,this[1],parse_group[op],this[2]]).join(space):has(parse_group,op)?op+map(syntax_node_tostring,this).join(space)+parse_group[op]:has(parse_lr,op)?this.length?map(syntax_node_tostring,this).join(space+op+space):op:has(parse_r,op)||has(parse_r_optional,op)?op.replace(/^u/,' ')+space+(this[0]?this[0].serialize():''):has(parse_r_until_block,op)?has(parse_accepts,op)&&this[1]&&this[2]&&parse_accepts[op]===this[2].data&& !this[1].ends_with_block()?op+space+map(syntax_node_tostring,[this[0],this[1],';\n',this[2]]).join(''):op+space+map(syntax_node_tostring,this).join(''):has(parse_l,op)?(this[0]?this[0].serialize():'')+space+op:op}};
caterwaul_global.method('define_syntax',function (name,ctor){return this.field(name,extend.apply(this,[ctor,syntax_common].concat(Array.prototype.slice.call(arguments,2))))}).method('ensure_syntax',function (thing){return thing&&thing.constructor===String?this.parse(thing):thing}).field('syntax_common',syntax_common).define_syntax('ref',function (value){if (value instanceof this.constructor){this.value=value.value;
this.data=value.data}else {this.value=value;
this.data=gensym()}},{length:0,binds_a_value:true}).define_syntax('syntax',function (data){if (data instanceof this.constructor)this.data=data.data,this.length=0;
else {this.data=data&&data.toString();
this.length=0;
for (var i=1,l=arguments.length,_;
_=arguments[i],i<l;
 ++i)for (var j=0,lj=_.length,it,itc;
_ instanceof Array?(it=_[j],j<lj):(it=_, !j);
 ++j)this._append((itc=it.constructor)===String||itc===Number||itc===Boolean?new this.constructor(it):it)}})})();
caterwaul_global.alias('parse','decompile').method('parse',(function (){return function (input){var s=input.toString(),mark=0,c=0,re=true,esc=false,dot=false,exp=false,close=0,t='',i=0,l=s.length,cs=function (i){return s.charCodeAt(i)},grouping_stack=[],gs_top=null,head=null,parent=null,indexes=map(function (){return []},parse_reduce_order),invocation_nodes=[],all_nodes=[],new_node=function (n){return all_nodes.push(n),n},push=function (n){return head?head._sibling(head=n):(head=n._append_to(parent)),new_node(n)},syntax_node=caterwaul_global.syntax;
while ((mark=i)<l){while (lex_space[c=cs(i)]&&i<l)mark= ++i;
esc=exp=dot=t=false;
if (lex_bracket[c]){t= ! ! ++i;
re=lex_opener[c]}else if (c===lex_slash&&cs(i+1)===lex_star&&(i+=2)){while ( ++i<l&&cs(i)!==lex_slash||cs(i-1)!==lex_star);
t= ! ++i}else if (c===lex_slash&&cs(i+1)===lex_slash){while ( ++i<l&& !lex_eol[cs(i)]);
t=false}else if (lex_quote[c]&&(close=c)&&re&& !(re= !(t=s.charAt(i)))){while ( ++i<l&&(c=cs(i))!==close||esc)esc= !esc&&c===lex_back;
while ( ++i<l&&lex_regexp_suffix[cs(i)]);
t=true}else if (c===lex_zero&&lex_integer[cs(i+1)]){while ( ++i<l&&lex_integer[cs(i)]);
re= !(t=true)}else if (lex_float[c]&&(c!==lex_dot||lex_decimal[cs(i+1)])){while ( ++i<l&&(lex_decimal[c=cs(i)]||(dot^(dot|=c===lex_dot))||(exp^(exp|=lex_exp[c]&& ++i))));
while (i<l&&lex_decimal[cs(i)]) ++i;
re= !(t=true)}else if (lex_punct[c]&&(t=re?'u':'',re=true)){while (i<l&&lex_punct[cs(i)]&&has(lex_op,t+s.charAt(i)))t+=s.charAt(i++);
re= !has(lex_postfix_unary,t)}else {while ( ++i<l&&lex_ident[cs(i)]);
re=has(lex_op,t=s.substring(mark,i))}if (i===mark)throw new Error('Caterwaul lex error at "'+s.substr(mark,40)+'" with leading context "'+s.substr(mark-40,40)+'" (probably a Caterwaul bug)');
if (t===false)continue ;
t=t===true?s.substring(mark,i):t==='u;'?';':t;
t===gs_top?(grouping_stack.pop(),gs_top=grouping_stack[grouping_stack.length-1],head=head?head.p:parent,parent=null):(has(parse_group,t)?(grouping_stack.push(gs_top=parse_group[t]),parent=push(new_node(new syntax_node(t))),head=null):push(new_node(new syntax_node(t))),has(parse_inverse_order,t)&&indexes[parse_inverse_order[t]].push(head||parent));
re|=t===')'&&head.l&&has(parse_r_until_block,head.l.data)}for (var i=0,l=indexes.length,forward,_;
_=indexes[i],forward=parse_index_forward[i],i<l;
 ++i)for (var j=forward?0:_.length-1,lj=_.length,inc=forward?1: -1,node,data;
node=_[j],data=node&&node.data,forward?j<lj:j>=0;
j+=inc)if (has(parse_lr,data))node._fold_lr();
else if (has(parse_ambiguous_group,data)&&node.l&&(node.l.data==='.'|| !(has(lex_op,node.l.data)||has(parse_not_a_value,node.l.data))))invocation_nodes.push(node.l._wrap(new_node(new syntax_node(data+parse_group[data]))).p._fold_r());
else if (has(parse_l,data))node._fold_l();
else if (has(parse_r,data))node._fold_r();
else if (has(parse_ternary,data)){node._fold_lr();
var temp=node[1];
node[1]=node[0];
node[0]=temp}else if (has(parse_r_until_block,data)&&node.r&&node.r.data!==':'){for (var count=0,limit=parse_r_until_block[data];
count<limit&&node.r&& !has(parse_block,node.r.data);
 ++count)node._fold_r();
node.r&&node.r.data!==';'&&node._fold_r();
if (has(parse_accepts,data)&&parse_accepts[data]===(node.r&&node.r.r&&node.r.r.data))node._fold_r().pop()._fold_r();
else if (has(parse_accepts,data)&&parse_accepts[data]===(node.r&&node.r.data))node._fold_r()}else if (has(parse_r_optional,data))node.r&&node.r.data!==';'&&node._fold_r();
for (var i=all_nodes.length-1,_;
_=all_nodes[i],i>=0;
 --i)_.r&&_._wrap(new syntax_node('i;')).p._fold_r();
for (var i=0,l=invocation_nodes.length,_,child;
_=invocation_nodes[i],i<l;
 ++i)(child=_[1]=_[1][0])&&(child.p=_);
while (head.p)head=head.p;
for (var i=all_nodes.length-1;
i>=0;
 --i)delete all_nodes[i].p;
return head}})());
caterwaul_global.shallow('globals',{}).method('compile',function (tree,environment){var vars=[],values=[],bindings=merge({},this.globals,environment||{},tree.bindings()),s=gensym();
for (var k in bindings)if (own.call(bindings,k))vars.push(k),values.push(bindings[k]);
var code=map(function (v){return v==='this'?'':'var '+v+'='+s+'.'+v},vars).join(';')+';return('+tree.serialize()+')';
try {return (new Function(s,code)).call(bindings['this'],bindings)}catch (e){throw new Error('caught '+e+' while compiling '+code)}});
caterwaul_global.variadic('event',function (name){var listeners=name+'_listeners',new_listener='on_'+name;
return this.shallow(listeners,[]).variadic(new_listener,function (l){this[listeners].push(l);
return this}).method(name,function (){for (var ls=this[listeners],i=0,l=ls.length;
i<l;
 ++i)ls[i].apply(this,arguments);
return this})});
caterwaul_global.event('bake').on_bake(function (){this.on_bake(function (){throw new Error('cannot bake a caterwaul function more than once')})}).method('method_until_baked',function (name,f){return this.method(name,f).on_bake(function (){this.method(name,function (){throw new Error('cannot call '+name+' on a baked caterwaul')})})});
(function (){caterwaul_global.shallow('macro_patterns',[]).shallow('macro_expanders',[]).method('with_gensyms',function (t){var gensyms={};
return this.ensure_syntax(t).rmap(function (n){return /^gensym/.test(n.data)&&new this.constructor(gensyms[n.data]||(gensyms[n.data]=gensym()),this)})}).method('macroexpand',function (t){return this.ensure_syntax(t).rmap(this.macroexpand_single)}).method('macroexpand_single',function (t){return this.macro_expand_naive(t,this.macro_patterns,this.macro_expanders)}).on_bake(function (){this.method('macroexpand_single',this.create_baked_macroexpander(this.macro_patterns,this.macro_expanders))}).method('expander_from_string',function (expander){var tree=this.parse(expander);
return function (match){return tree.replace(match)}}).method('ensure_expander',function (expander){return expander.constructor===String?this.expander_from_string(expander):expander.constructor===this.syntax?function (match){return expander.replace(match)}:expander.constructor===Function?expander:fail('unknown macroexpander format: '+expander)}).right_variadic_binary('final_macro',function (pattern,expander){return this.macro_patterns.push(this.ensure_syntax(pattern)),this.macro_expanders.push(this.ensure_expander(expander)),this}).right_variadic_binary('macro',function (pattern,expander){expander=this.ensure_expander(expander);
return this.final_macro(pattern,function (){var t=expander.apply(this,arguments);
return t&&this.macroexpand(t)})})})();
caterwaul_global.method('macro_expand_naive',function (t,macros,expanders){var self=this;
return t.rmap(function (n){for (var i=macros.length-1,match,replacement;
i>=0;
 --i)if ((match=macros[i].match(n))&&(replacement=expanders[i].call(self,match)))return replacement})});
caterwaul_global.method('create_baked_macroexpander',(function (){var resolve_tree_path=function (tree,path){for (var i=0,l=path.length;
i<l;
 ++i)if ( !(tree=tree[path.charCodeAt(i)]))return tree;
return tree},partition_treeset=function (trees,path){for (var r={},i=0,l=trees.length,t,ti;
i<l;
 ++i)(t=resolve_tree_path(ti=trees[i],path))?(t=String.fromCharCode(t.length)+t.data):(t=''),(r[t]||(r[t]=[])).push(ti);
return r},next_path=function (visited,trees){if ( !visited)return '';
for (var k in visited)if (visited.hasOwnProperty(k))for (var i=0,l=visited[k],p;
i<l;
 ++i)if ( !((p=k+String.fromCharCode(i)) in visited)){for (var j=0,lj=trees.length,skip;
j<lj;
 ++j)if (skip=resolve_tree_path(trees[j],p).is_wildcard())break ;
if ( !skip)return p}},visit_path=function (path,visited,trees){var partitions=partition_treeset(trees,path),kv=function (k,v){var r={};
r[k]=v;
return r};
for (var k in partitions)if (partitions.hasOwnProperty(k))partitions[k]={trees:partitions[k],visited:merge({},visited,kv(path,k.charCodeAt(0)))};
return partitions},split_treeset_on_specification=function (trees,pattern_data,visited){var r=[],visited_count=0,available_paths={},available_count=0;
if (visited!=null){for (var k in visited)if (visited.hasOwnProperty(k)){ ++visited_count;
for (var i=0,l=visited[k];
i<l;
 ++i)available_paths[k+String.fromCharCode(i)]= ++available_count}}else available_paths={'':available_count=1};
for (var p=[],s=false,remaining_paths=null,remaining_count=0,i=0,l=trees.length,t,td;
i<l;
 ++i)if (((td=pattern_data[(t=trees[i]).id()]).non_wildcards===visited_count)!==s)r.push(p),p=[t],s= !s,remaining_paths=null;
else if (s)p.push(t);
else {if (remaining_paths===null)remaining_paths=merge({},available_paths),remaining_count=available_count;
for (var ps=td.wildcard_paths,j=0,lj=ps.length,pj;
j<lj;
 ++j)remaining_count-=remaining_paths.hasOwnProperty(pj=ps[j]),delete remaining_paths[pj];
if (remaining_count)p.push(t);
else r.push(p),r.push([]),p=[t],remaining_paths=null}p.length&&r.push(p);
return r},wildcard_paths=function (t){for (var r=t.is_wildcard()?['']:[],i=0,l=t.length;
i<l;
 ++i)for (var ps=t[i]&&wildcard_paths(t[i]),j=0,lj=ps.length;
j<lj;
 ++j)r.push(String.fromCharCode(i)+ps[j]);
return r},pattern_data=function (ps,es){for (var r={},i=0,l=ps.length,p;
i<l;
 ++i)r[(p=ps[i]).id()]={expander:es[i],non_wildcards:non_wildcard_node_count(p),wildcard_paths:wildcard_paths(p)};
return r},pattern_match_function_template=caterwaul_global.parse('function (t) {var result; _body}'),empty_variable_mapping_table=function (){return {'':'t'}},partition_template=caterwaul_global.parse('switch (_value) {_cases}'),partition_branch_template=caterwaul_global.parse('case _value: _body; break'),single_macro_attempt_template=caterwaul_global.parse('do {_body} while (false)'),indexed_path_reference_template=caterwaul_global.parse('_base[_index]'),absolute_path_reference_template=caterwaul_global.parse('_base'),generate_path_reference=function (variables,path){return variables[path]?absolute_path_reference_template.replace({_base:variables[path]}):indexed_path_reference_template.replace({_base:generate_path_reference(variables,path.substr(0,path.length-1)),_index:''+path.charCodeAt(path.length-1)})},path_variable_template=caterwaul_global.parse('var _temp = _value; if (! _temp) break'),path_exists_template=caterwaul_global.parse('null'),generate_path_variable=function (variables,path){if (variables[path])return path_exists_template;
var name='t'+genint(),replacements={_value:generate_path_reference(variables,path),_temp:name};
return variables[path]=name,path_variable_template.replace(replacements)},non_wildcard_node_count=function (tree){var r=0;
tree.reach(function (node){r+= !node.is_wildcard()});
return r},path_reference_object_template=caterwaul_global.parse('{_elements}'),variable_value_pair_template=caterwaul_global.parse('_variable: _value'),generate_path_reference_object=function (pattern,variables,paths){for (var refs=[],i=0,l=paths.length;
i<l;
 ++i)refs.push(variable_value_pair_template.replace({_variable:resolve_tree_path(pattern,paths[i]).data,_value:generate_path_reference(variables,paths[i])}));
return path_reference_object_template.replace({_elements:refs.length?new caterwaul_global.syntax(',',refs):undefined})},macroexpander_invocation_template=caterwaul_global.parse('if (result = _expander.apply(this, _path_reference_object)) return result'),generate_macroexpander_invocation=function (pattern_data,pattern,variables){return macroexpander_invocation_template.replace({_expander:new caterwaul_global.ref(pattern_data[pattern.id()].expander),_path_reference_object:generate_path_reference_object(pattern,variables,pattern_data[pattern.id()].wildcard_paths)})},length_reference_template=caterwaul_global.parse('_value.length'),data_reference_template=caterwaul_global.parse('_value.data'),generate_partitioned_switch=function (trees,visited,variables,pattern_data){var path=next_path(visited,trees),partitions=visit_path(path,visited,trees),lengths={},length_pairs=[];
for (var k in partitions)if (partitions.hasOwnProperty(k))(lengths[k.charCodeAt(0)]||(lengths[k.charCodeAt(0)]=[])).push(k.substr(1));
for (var k in lengths)if (lengths.hasOwnProperty(k))length_pairs.push([k,lengths[k]]);
var new_variables=merge({},variables),path_reference_variable=generate_path_variable(new_variables,path),variable=new_variables[path],length_reference=length_reference_template.replace({_value:variable}),data_reference=data_reference_template.replace({_value:variable});
for (var length_cases=new caterwaul_global.syntax(';'),i=0,l=length_pairs.length,pair;
i<l;
 ++i){for (var data_cases=new caterwaul_global.syntax(';'),length=(pair=length_pairs[i])[0],values=pair[1],j=0,lj=values.length,p,v;
j<lj;
 ++j)p=partitions[String.fromCharCode(length)+(v=values[j])],data_cases.push(partition_branch_template.replace({_value:'"'+v.replace(/([\\"])/g,'\\$1')+'"',_body:generate_decision_tree(p.trees,path,p.visited,new_variables,pattern_data)}));
lj&&length_cases.push(partition_branch_template.replace({_value:''+length_pairs[i][0],_body:partition_template.replace({_value:data_reference,_cases:data_cases})}))}return single_macro_attempt_template.replace({_body:new caterwaul_global.syntax(';',path_reference_variable,length_cases.length?partition_template.replace({_value:length_reference,_cases:length_cases}):[])})},generate_unpartitioned_sequence=function (trees,variables,pattern_data){for (var r=new caterwaul_global.syntax(';'),i=0,l=trees.length;
i<l;
 ++i)r.push(generate_macroexpander_invocation(pattern_data,trees[i],variables));
return r},generate_decision_tree=function (trees,path,visited,variables,pattern_data){for (var r=new caterwaul_global.syntax(';'),sts=split_treeset_on_specification(trees,pattern_data,visited),i=0,l=sts.length;
i<l;
 ++i)sts[i].length&&r.push(i&1?generate_unpartitioned_sequence(sts[i],variables,pattern_data):generate_partitioned_switch(sts[i],visited,variables,pattern_data));
return r};
return function (patterns,expanders){for (var i=patterns.length-1,rps=[],res=[];
i>=0;
 --i)rps.push(patterns[i]),res.push(expanders[i]);
return this.compile(pattern_match_function_template.replace({_body:generate_decision_tree(rps,null,null,empty_variable_mapping_table(),pattern_data(rps,res))}))}})());
caterwaul_global.method('macro_form',function (){for (var i=0,l=arguments.length-1;
i<l;
 ++i)this.define_macro_form(arguments[i],arguments[l]);
return this}).method('define_macro_form',function (name,define){var names=name+'s',form=name+'_form',forms=name+'_forms',define_name='define_'+name;
return this.shallow(names,[]).method(name,function (){for (var fs=this[forms],def=this[define_name],i=0,l=arguments.length-1,definition=this.ensure_expander(arguments[l]),lj=fs.length;
i<l;
 ++i){for (var name=arguments[i],j=0;
j<lj;
 ++j)def.call(this,name,definition,fs[j]);
this[names].push({name:name,definition:definition})}return this}).shallow(forms,[]).method(form,function (){for (var xs=this[names],def=this[define_name],i=0,l=arguments.length,lj=xs.length;
i<l;
 ++i){for (var form=this.ensure_syntax(arguments[i]),j=0;
j<lj;
 ++j)def.call(this,xs[j].name,xs[j].definition,form);
this[forms].push(form)}return this}).method(define_name,function (){return define.apply(this,arguments),this})});
caterwaul_global.shallow('after_functions',[]).method('after',function (){if (arguments.length){for (var i=0,l=arguments.length;
i<l;
 ++i)this.after_functions.push(arguments[i]);
return this}else return this.after_functions});
caterwaul_global.field('precompiled_internal_table',{}).method('precompiled_internal',function (f){var k=gensym();
return this.precompiled_internal_table[k]=f,k}).method('is_precompiled',function (f){return f.constructor===String&&this.precompiled_internal_table[f]}).method('init',function (f,environment){return this.is_precompiled(f)||this.init_not_precompiled(f,environment)}).method('init_not_precompiled',function (f,environment){var result=f.constructor===this.syntax?this.macroexpand(f):this.compile(this(this.decompile(f)),environment);
if (f.constructor===this.syntax)for (var i=0,l=this.after_functions.length;
i<l;
 ++i)result=this.after_functions[i](result);
return result});
return caterwaul_global});
caterwaul.field('version','689250303e7e8de99523fa2ccff5262f').check_version();
caterwaul.macro_form('adverb','modified_adverb',function (name,def,form){this.macro(form.replace({it:name}),def)});
caterwaul.macro_form('adjective','modified_adjective',function (name,def,form){this.macro(form.replace({it:name}),def)});
caterwaul.configuration('core.js',function (){this.adjective_form('it[_expression]','_expression |it','_expression /it').modified_adverb_form('it[_modifiers][_expression]','it[_modifiers] in _expression','it._modifiers[_expression]','it._modifiers in _expression','_expression, it[_modifiers]','_expression |it[_modifiers]','_expression /it[_modifiers]','_expression -it[_modifiers','_expression -it- _modifiers','_expression, it._modifiers','_expression |it._modifiers','_expression /it._modifiers','_expression -it._modifiers','_expression <it> _modifiers');
this.macro('wobbly[_x]','(function () {throw _x}).call(this)');
this.macro('_string',function (match){var s=match._string.data,q=s.charAt(0);
if (q!=='\''&&q!=='"'|| !/#\{[^\}]+\}/.test(s))return false;
for (var pieces=[],i=1,l=s.length-1,brace_depth=0,got_hash=false,start=1,c;
i<l;
 ++i)if (brace_depth)if ((c=s.charAt(i))==='}') --brace_depth||pieces.push(s.substring(start,i))&&(start=i+1),got_hash=false;
else brace_depth+=c==='{';
else if ((c=s.charAt(i))==='#')got_hash=true;
else if (c==='{'&&got_hash)pieces.push(s.substring(start,i-1)),start=i+1, ++brace_depth;
else got_hash=false;
pieces.push(s.substring(start,l));
for (var escaped=new RegExp('\\\\'+q,'g'),i=0,l=pieces.length;
i<l;
 ++i)if (i&1)pieces[i]=this.parse(pieces[i].replace(escaped,q)).as('(');
else pieces[i]=new this.syntax(q+pieces[i]+q);
return new this.syntax('+',pieces).unflatten().as('(')});
this.macro('_left(_args) = _right','_left = (function (_args) {return _right})')});
caterwaul.configuration('core.quote',function (){this.adjective('qs',function (match){return new this.ref(match._expression)}).adjective('qse',function (match){return new this.ref(this.macroexpand(match._expression))})});
caterwaul.configuration('core.words',function (){this.modified_adverb('given','from','fn','(function (_modifiers) {return _expression})').modified_adverb('bgiven','bfrom','fb','(function (t, f) {return (function () {return f.apply(t, arguments)})})(this, (function (_modifiers) {return _expression}))');
this.modified_adverb('effect','se','(function (it) {return (_modifiers), it}).call(this, (_expression))').modified_adverb('then','re','returning','(function (it) {return (_modifiers)}).call(this, (_expression))');
this.modified_adverb('where','bind','(function () {var _modifiers; return (_expression)}).call(this)');
this.modified_adverb('when','((_modifiers) && (_expression))').modified_adverb('unless','(! (_modifiers) && (_expression))').modified_adverb('otherwise','((_expression) || (_modifiers))');
this.modified_adverb('over',this.with_gensyms('(function () {for (var gensym_xs = (_modifiers), gensym_result = [], gensym_i = 0, gensym_l = gensym_xs.length, it; gensym_i < gensym_l; ++gensym_i) '+'  it = gensym_xs[gensym_i], gensym_result.push(_expression); return gensym_result}).call(this)')).modified_adverb('over_keys',this.with_gensyms('(function () {var gensym_x = (_modifiers), gensym_result = []; '+'for (var it in gensym_x) Object.prototype.hasOwnProperty.call(gensym_x, it) && gensym_result.push(_expression); return gensym_result}).call(this)')).modified_adverb('over_values',this.with_gensyms('(function () {var gensym_x = (_modifiers), gensym_result = [], it; '+'for (var gensym_k in gensym_x) Object.prototype.hasOwnProperty.call(gensym_x, gensym_k) && (it = gensym_x[gensym_k], gensym_result.push(_expression));'+'return gensym_result}).call(this)'));
this.modified_adverb('until',this.with_gensyms('(function () {var gensym_result = []; while (! (_modifiers)) gensym_result.push(_expression); return gensym_result}).call(this)'))});
caterwaul.tconfigure('core.js core.words core.quote',caterwaul.precompiled_internal((function (){var gensym_1_gms0djx5_9i6t98=new caterwaul.syntax('()',new caterwaul.syntax('.',new caterwaul.syntax('caterwaul'),new caterwaul.syntax('precompiled_internal')),new caterwaul.syntax('_x'));
var gensym_1_gms0djx5_9i6t99=new caterwaul.syntax('new',new caterwaul.syntax('()',new caterwaul.syntax('.',new caterwaul.syntax('caterwaul'),new caterwaul.syntax('syntax')),new caterwaul.syntax('_name')));
var gensym_1_gms0djx5_9i6t9a=new caterwaul.syntax('new',new caterwaul.syntax('()',new caterwaul.syntax('.',new caterwaul.syntax('caterwaul'),new caterwaul.syntax('syntax')),new caterwaul.syntax(',',new caterwaul.syntax('_name'),new caterwaul.syntax('_children'))));
var gensym_1_gms0djx5_9i6t9b=new caterwaul.syntax('()',new caterwaul.syntax('.',new caterwaul.syntax('caterwaul'),new caterwaul.syntax('clone')),new caterwaul.syntax('_string'));
return (function (){(function (){var nontrivial_function_pattern=caterwaul.parse('function (_args) {_body}'),trivial_function_pattern=caterwaul.parse('function ()      {_body}'),nontrivial_function_gensym_template=caterwaul.parse('function (_args, _gensym) {_body}'),trivial_function_gensym_template=caterwaul.parse('function (_gensym)        {_body}'),nontrivial_gensym_detection_pattern=nontrivial_function_gensym_template,trivial_gensym_detection_pattern=trivial_function_gensym_template,annotate_macro_generator=(function (template){return (function (references){return (function (match){return (function (){var s=caterwaul.gensym(),result=template.replace({_args:match._args,_gensym:s,_body:annotate_functions_in(match._body,references)});
return ((function (it){return (references[s]={tree:result}),it}).call(this,(result)))}).call(this)})})}),mark_nontrivial_function_macro=annotate_macro_generator(nontrivial_function_gensym_template),mark_trivial_function_macro=annotate_macro_generator(trivial_function_gensym_template),annotate_functions_in=(function (tree,references){return caterwaul.macro_expand_naive(tree,[trivial_function_pattern,nontrivial_function_pattern],[mark_trivial_function_macro(references),mark_nontrivial_function_macro(references)])}),function_key=(function (tree){return (function (){var matches=nontrivial_gensym_detection_pattern.match(tree)||trivial_gensym_detection_pattern.match(tree);
return (((matches)&&(matches._gensym.data)))}).call(this)}),mark_as_compiled=(function (references,k,tree,environment){return ((k&&references[k])&&((function (it){return (references[k].compiled=tree,references[k].environment=environment),it}).call(this,((function (it){return (((references[k].compiled)&&((function (){throw new Error(('detected multiple compilations of '+(references[k].tree.serialize())+''))}).call(this)))),it}).call(this,(references[k]))))))}),wrapped_compile=(function (original,references){return (function (tree,environment){return (function (it){return (mark_as_compiled(references,function_key(tree),tree,caterwaul.merge({},this.globals,environment))),it}).call(this,(original.call(this,tree,environment)))})}),signal_already_compiled=(function (tree){return gensym_1_gms0djx5_9i6t98.replace({_x:tree})}),closure_template=caterwaul.parse('(function () {_vars; return (_value)})()'),closure_variable_template=caterwaul.parse('var _var = _value'),closure_null_template=caterwaul.parse('null'),escape_string=(function (s){return '\''+s.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/'/g,'\\\'')+'\''}),caterwaul_ref_string=(function (configurations){return '\''+(function (){var gensym_1_gms0djx5_9i6t92=(configurations),gensym_1_gms0djx5_9i6t93=[];
for (var it in gensym_1_gms0djx5_9i6t92)Object.prototype.hasOwnProperty.call(gensym_1_gms0djx5_9i6t92,it)&&gensym_1_gms0djx5_9i6t93.push(it);
return gensym_1_gms0djx5_9i6t93}).call(this)+'\''}),serialize_syntax=(function (value){return value.length===0?gensym_1_gms0djx5_9i6t99.replace({_name:escape_string(value.data)}):(function (){var children=new caterwaul.syntax(',',(function (){for (var gensym_1_gms0djx5_9i6t8y=(value),gensym_1_gms0djx5_9i6t8z=[],gensym_1_gms0djx5_9i6t90=0,gensym_1_gms0djx5_9i6t91=gensym_1_gms0djx5_9i6t8y.length,it;
gensym_1_gms0djx5_9i6t90<gensym_1_gms0djx5_9i6t91;
 ++gensym_1_gms0djx5_9i6t90)it=gensym_1_gms0djx5_9i6t8y[gensym_1_gms0djx5_9i6t90],gensym_1_gms0djx5_9i6t8z.push(serialize_syntax(it));
return gensym_1_gms0djx5_9i6t8z}).call(this)).unflatten();
return (gensym_1_gms0djx5_9i6t9a.replace({_name:escape_string(value.data),_children:children}))}).call(this)}),serialize_caterwaul=(function (value){return gensym_1_gms0djx5_9i6t9b.replace({_string:caterwaul_ref_string(value.has)})}),serialize_ref=(function (value,name,seen){return  !value?(''+(value)+''):value.constructor===caterwaul.syntax?seen[value.id()]||(function (it){return (serialize_syntax(value))}).call(this,((seen[value.id()]=name))):value.is_caterwaul===caterwaul.is_caterwaul?seen[value.id()]||(function (it){return (serialize_caterwaul(value))}).call(this,((seen[value.id()]=name))):(function (){throw new Error(('syntax ref value is not serializable: '+(value)+''))}).call(this)}),single_variable=(function (name,value){return closure_variable_template.replace({_var:name,_value:value})}),names_and_values_for=(function (environment){return (function (){var gensym_1_gms0djx5_9i6t92=(environment),gensym_1_gms0djx5_9i6t93=[];
for (var it in gensym_1_gms0djx5_9i6t92)Object.prototype.hasOwnProperty.call(gensym_1_gms0djx5_9i6t92,it)&&gensym_1_gms0djx5_9i6t93.push(single_variable(it,environment[it]));
return gensym_1_gms0djx5_9i6t93}).call(this)}),tree_variables=(function (tree){return (function (){var vars=[],seen={};
return ((function (it){return (tree.reach((function (n){return ((n&&n.binds_a_value)&&(vars.push(single_variable(n.data,serialize_ref(n.value,n.data,seen)))))}))),it}).call(this,(vars)))}).call(this)}),variables_for=(function (tree,environment){return (function (){var all_variables=names_and_values_for(environment).concat(tree_variables(tree));
return (all_variables.length?new caterwaul.syntax(';',all_variables):closure_null_template)}).call(this)}),precompiled_closure=(function (tree,environment){return closure_template.replace({_vars:variables_for(tree,environment),_value:tree})}),precompiled_function=(function (tree,environment){return signal_already_compiled(precompiled_closure(tree,environment))}),substitute_precompiled=(function (references){return (function (match){return (function (){var ref=references[match._gensym.data];
return (((ref&&ref.compiled)&&(precompiled_function(ref.compiled,ref.environment))))}).call(this)})}),perform_substitution=(function (references,tree){return (function (){var expander=substitute_precompiled(references);
return (caterwaul.macro_expand_naive(tree,[trivial_gensym_detection_pattern,nontrivial_gensym_detection_pattern],[expander,expander]))}).call(this)}),reconstruct_original=(function (references,match){return (function (){var new_match={_body:remove_gensyms(references,match._body),_args:match._args};
return (match._args?nontrivial_function_pattern.replace(new_match):trivial_function_pattern.replace(new_match))}).call(this)}),remove_referenced_gensyms=(function (references){return (function (match){return (function (){var ref=references[match._gensym.data];
return (((ref&&ref.tree)&&(reconstruct_original(references,match))))}).call(this)})}),remove_gensyms=(function (references,tree){return (function (){var expander=remove_referenced_gensyms(references);
return (caterwaul.macro_expand_naive(tree,[trivial_gensym_detection_pattern,nontrivial_gensym_detection_pattern],[expander,expander]))}).call(this)}),annotated_caterwaul=(function (caterwaul,references){return caterwaul.clone().method('compile',wrapped_compile(caterwaul.compile,references))}),trace_execution=(function (caterwaul,f){return (function (){var references={},annotated=annotate_functions_in(caterwaul.parse(f),references);
return ((function (it){return (caterwaul.compile(annotated,{caterwaul:annotated_caterwaul(caterwaul,references)})()),it}).call(this,({references:references,annotated:annotated})))}).call(this)});
return (this.method('precompile',(function (f){return (function (){var traced=trace_execution(this,f);
return (this.compile(remove_gensyms(traced.references,perform_substitution(traced.references,traced.annotated))))}).call(this)})))}).call(this)})})()));
caterwaul.configuration('core.trace',function (){this.after(this.trace.clone())}).shallow('trace',caterwaul.clone().tconfigure('core.js core.words core.quote',caterwaul.precompiled_internal((function (){var gensym_1_gms0djx5_9i6t9n=new caterwaul.syntax(',',new caterwaul.syntax('()',new caterwaul.syntax('_before_hook'),new caterwaul.syntax('_tree')),new caterwaul.syntax('()',new caterwaul.syntax('_after_hook'),new caterwaul.syntax(',',new caterwaul.syntax('_tree'),new caterwaul.syntax('_expression'))));
var gensym_1_gms0djx5_9i6t9o=new caterwaul.syntax(',',new caterwaul.syntax('()',new caterwaul.syntax('_before_hook'),new caterwaul.syntax('_tree')),new caterwaul.syntax('()',new caterwaul.syntax('_after_hook'),new caterwaul.syntax(',',new caterwaul.syntax(',',new caterwaul.syntax(',',new caterwaul.syntax('_tree'),new caterwaul.syntax('_object')),new caterwaul.syntax('_method')),new caterwaul.syntax('[',new caterwaul.syntax('_parameters')))));
var gensym_1_gms0djx5_9i6t9p=new caterwaul.syntax('=',new caterwaul.syntax('_x'),new caterwaul.syntax('_y'));
var gensym_1_gms0djx5_9i6t9q=new caterwaul.syntax('[]',new caterwaul.syntax('H'),new caterwaul.syntax(',',new caterwaul.syntax('all'),new caterwaul.syntax('=',new caterwaul.syntax('_x'),new caterwaul.syntax('[]',new caterwaul.syntax('E'),new caterwaul.syntax('_y')))));
var gensym_1_gms0djx5_9i6t9r=new caterwaul.syntax('=',new caterwaul.syntax('[]',new caterwaul.syntax('_x'),new caterwaul.syntax('_y')),new caterwaul.syntax('_z'));
var gensym_1_gms0djx5_9i6t9s=new caterwaul.syntax('[]',new caterwaul.syntax('H'),new caterwaul.syntax(',',new caterwaul.syntax('all'),new caterwaul.syntax('=',new caterwaul.syntax('[]',new caterwaul.syntax('[]',new caterwaul.syntax('E'),new caterwaul.syntax('_x')),new caterwaul.syntax('[]',new caterwaul.syntax('E'),new caterwaul.syntax('_y'))),new caterwaul.syntax('[]',new caterwaul.syntax('E'),new caterwaul.syntax('_z')))));
var gensym_1_gms0djx5_9i6t9t=new caterwaul.syntax('=',new caterwaul.syntax('.',new caterwaul.syntax('_x'),new caterwaul.syntax('_y')),new caterwaul.syntax('_z'));
var gensym_1_gms0djx5_9i6t9u=new caterwaul.syntax('[]',new caterwaul.syntax('H'),new caterwaul.syntax(',',new caterwaul.syntax('all'),new caterwaul.syntax('=',new caterwaul.syntax('.',new caterwaul.syntax('[]',new caterwaul.syntax('E'),new caterwaul.syntax('_x')),new caterwaul.syntax('_y')),new caterwaul.syntax('[]',new caterwaul.syntax('E'),new caterwaul.syntax('_z')))));
var gensym_1_gms0djx5_9i6t9v=new caterwaul.syntax('+',new caterwaul.syntax('_x'),new caterwaul.syntax('_y'));
var gensym_1_gms0djx5_9i6t9w=new caterwaul.syntax('[]',new caterwaul.syntax('H'),new caterwaul.syntax(',',new caterwaul.syntax('all'),new caterwaul.syntax('+',new caterwaul.syntax('[]',new caterwaul.syntax('E'),new caterwaul.syntax('_x')),new caterwaul.syntax('[]',new caterwaul.syntax('E'),new caterwaul.syntax('_y')))));
var gensym_1_gms0djx5_9i6t9x=new caterwaul.syntax('u+',new caterwaul.syntax('_x'));
var gensym_1_gms0djx5_9i6t9y=new caterwaul.syntax('[]',new caterwaul.syntax('H'),new caterwaul.syntax(',',new caterwaul.syntax('all'),new caterwaul.syntax('u+',new caterwaul.syntax('[]',new caterwaul.syntax('T'),new caterwaul.syntax('_x')))));
return (function (){(function (){var self=this,qw=(function (s){return s.split(/\s+/)}),trace_directive_aliases=(function (it){return ((function (){var o=it;
return ((function (){var gensym_1_gms0djx5_9i6t9h=(o),gensym_1_gms0djx5_9i6t9i=[];
for (var it in gensym_1_gms0djx5_9i6t9h)Object.prototype.hasOwnProperty.call(gensym_1_gms0djx5_9i6t9h,it)&&gensym_1_gms0djx5_9i6t9i.push(o[o[it]]=it);
return gensym_1_gms0djx5_9i6t9i}).call(this))}).call(this)),it}).call(this,((function (it){return ((function (){var o=it;
return ((function (){for (var gensym_1_gms0djx5_9i6t9d=(qw('I D H S E')),gensym_1_gms0djx5_9i6t9e=[],gensym_1_gms0djx5_9i6t9f=0,gensym_1_gms0djx5_9i6t9g=gensym_1_gms0djx5_9i6t9d.length,it;
gensym_1_gms0djx5_9i6t9f<gensym_1_gms0djx5_9i6t9g;
 ++gensym_1_gms0djx5_9i6t9f)it=gensym_1_gms0djx5_9i6t9d[gensym_1_gms0djx5_9i6t9f],gensym_1_gms0djx5_9i6t9e.push(o[it]=this.gensym());
return gensym_1_gms0djx5_9i6t9e}).call(this))}).call(this)),it}).call(this,({})))),convert_trace_directives_in=(function (tree){return self.ensure_syntax(tree).replace(trace_directive_aliases)}),with_tmacro=(function (){return this.method('tmacro',(function (lhs,rhs){return this.final_macro(lhs,convert_trace_directives_in(rhs))}))}),statement=this.clone(with_tmacro),expression=this.clone(with_tmacro),trace_directive_expander=this.clone(),before_hook=(function (tree){return self.before_trace(tree)}),after_hook=(function (tree,value){return (function (it){return (value)}).call(this,(self.after_trace(tree,value)))}),after_method_hook=(function (tree,object,method,parameters){return (function (){var resolved=object[method];
return ((function (it){return (after_hook(tree,resolved.apply(object,parameters)))}).call(this,((function (it){return (self.after_trace(tree[0],resolved))}).call(this,(self.before_trace(tree[0]))))))}).call(this)}),before_hook_ref=new this.ref(before_hook),after_hook_ref=new this.ref(after_hook),after_method_hook_ref=new this.ref(after_method_hook),expression_hook_template=gensym_1_gms0djx5_9i6t9n.as('('),expression_hook=(function (original,tree){return expression_hook_template.replace({_before_hook:before_hook_ref,_after_hook:after_hook_ref,_tree:new self.ref(original),_expression:tree.as('(')})}),indirect_method_hook_template=gensym_1_gms0djx5_9i6t9o.as('('),quote_method_name=(function (method){return ('"'+(method.data.replace(/"/g,"\\\""))+'"')}),method_hook=(function (tree,object,method,parameters){return indirect_method_hook_template.replace({_before_hook:before_hook_ref,_after_hook:after_method_hook_ref,_tree:new self.ref(tree),_object:object,_method:method,_parameters:parameters})}),direct_method_hook=(function (tree,match){return method_hook(tree,match._object,quote_method_name(match._method),match._parameters)}),indirect_method_hook=(function (tree,match){return method_hook(tree,match._object,match._method,match._parameters)});
return (this.event('before_trace','after_trace'),this.shallow('expression',expression.after(trace_directive_expander).configure(function (){this.method('assignment_operator',(function (op){return this.tmacro(gensym_1_gms0djx5_9i6t9p.replace({'=':op}),gensym_1_gms0djx5_9i6t9q.replace({'=':op})).tmacro(gensym_1_gms0djx5_9i6t9r.replace({'=':op}),gensym_1_gms0djx5_9i6t9s.replace({'=':op})).tmacro(gensym_1_gms0djx5_9i6t9t.replace({'=':op}),gensym_1_gms0djx5_9i6t9u.replace({'=':op}))})).method('binary_operator',(function (op){return this.tmacro(gensym_1_gms0djx5_9i6t9v.replace({'+':op}),gensym_1_gms0djx5_9i6t9w.replace({'+':op}))})).method('unary_operator',(function (op){return this.tmacro(gensym_1_gms0djx5_9i6t9x.replace({'u+':('u'+(op)+'')}),gensym_1_gms0djx5_9i6t9y.replace({'u+':('u'+(op)+'')}))})),this.tmacro('_x','H[_x, _x]').tmacro('(_x)','(E[_x])').tmacro('++_x','H[all, ++_x]').tmacro('--_x','H[all, --_x]').tmacro('_x++','H[all, _x++]').tmacro('_x--','H[all, _x--]').tmacro('_x, _y','E[_x], E[_y]').tmacro('_x._y','H[all, E[_x]._y]').tmacro('_o._m(_xs)','D[all, E[_o], _m, [E[_xs]]]').tmacro('_o[_m](_xs)','I[all, E[_o], E[_m], [E[_xs]]]').tmacro('typeof _x','H[all, typeof _x]').tmacro('delete _x._y','H[all, delete E[_x]._y]').tmacro('new _x(_y)','H[all, new H[_x](E[_y])]').tmacro('{_ps}','H[all, {E[_ps]}]').tmacro('_k: _v','_k: E[_v]').tmacro('[_xs]','H[all, [E[_xs]]]').tmacro('_x ? _y : _z','H[all, E[_x] ? E[_y] : E[_z]]').tmacro('function (_xs) {_body}','H[all, function (_xs) {S[_body]}]'),(function (){for (var gensym_1_gms0djx5_9i6t9d=(qw('= += -= *= /= %= &= |= ^= <<= >>= >>>=')),gensym_1_gms0djx5_9i6t9e=[],gensym_1_gms0djx5_9i6t9f=0,gensym_1_gms0djx5_9i6t9g=gensym_1_gms0djx5_9i6t9d.length,it;
gensym_1_gms0djx5_9i6t9f<gensym_1_gms0djx5_9i6t9g;
 ++gensym_1_gms0djx5_9i6t9f)it=gensym_1_gms0djx5_9i6t9d[gensym_1_gms0djx5_9i6t9f],gensym_1_gms0djx5_9i6t9e.push(this.assignment_operator(it));
return gensym_1_gms0djx5_9i6t9e}).call(this),(function (){for (var gensym_1_gms0djx5_9i6t9d=(qw('() [] + - * / % < > <= >= == != === !== in instanceof ^ & | && ||')),gensym_1_gms0djx5_9i6t9e=[],gensym_1_gms0djx5_9i6t9f=0,gensym_1_gms0djx5_9i6t9g=gensym_1_gms0djx5_9i6t9d.length,it;
gensym_1_gms0djx5_9i6t9f<gensym_1_gms0djx5_9i6t9g;
 ++gensym_1_gms0djx5_9i6t9f)it=gensym_1_gms0djx5_9i6t9d[gensym_1_gms0djx5_9i6t9f],gensym_1_gms0djx5_9i6t9e.push(this.binary_operator(it));
return gensym_1_gms0djx5_9i6t9e}).call(this),(function (){for (var gensym_1_gms0djx5_9i6t9d=(qw('+ - void')),gensym_1_gms0djx5_9i6t9e=[],gensym_1_gms0djx5_9i6t9f=0,gensym_1_gms0djx5_9i6t9g=gensym_1_gms0djx5_9i6t9d.length,it;
gensym_1_gms0djx5_9i6t9f<gensym_1_gms0djx5_9i6t9g;
 ++gensym_1_gms0djx5_9i6t9f)it=gensym_1_gms0djx5_9i6t9d[gensym_1_gms0djx5_9i6t9f],gensym_1_gms0djx5_9i6t9e.push(this.unary_operator(it));
return gensym_1_gms0djx5_9i6t9e}).call(this)})),this.shallow('statement',statement.after(trace_directive_expander).configure(function (){this.tmacro('_x','E[_x]').tmacro('for (_x) _y','for (S[_x]) S[_y]').tmacro('{_x}','{S[_x]}').tmacro('for (_x; _y; _z) _body','for (S[_x]; E[_y]; E[_z]) S[_body]').tmacro('_x; _y','S[_x]; S[_y]').tmacro('while (_x) _y','while (E[_x]) S[_y]').tmacro('do _x; while (_y)','do S[_x]; while (E[_y])').tmacro('function _f(_args) {_body}','function _f(_args) {S[_body]}').tmacro('do {_x} while (_y)','do {S[_x]} while (E[_y])').tmacro('_x, _y','S[_x], S[_y]').tmacro('_x = _y','_x = E[_y]').tmacro('try {_x} catch (_e) {_y}','try {S[_x]} catch (_e) {S[_y]}').tmacro('var _xs','var S[_xs]').tmacro('try {_x} catch (_e) {_y} finally {_z}','try {S[_x]} catch (_e) {S[_y]} finally {S[_z]}').tmacro('const _xs','const S[_xs]').tmacro('try {_x} finally {_y}','try {S[_x]} finally {S[_y]}').tmacro('if (_x) _y','if (E[_x]) S[_y]').tmacro('return _x','return E[_x]').tmacro('if (_x) _y; else _z','if (E[_x]) S[_y]; else S[_z]').tmacro('return','return').tmacro('if (_x) {_y} else _z','if (E[_x]) {S[_y]} else S[_z]').tmacro('throw _x','throw E[_x]').tmacro('break _label','break _label').tmacro('switch (_c) {_body}','switch (E[_c]) {S[_body]}').tmacro('break','break').tmacro('with (_x) _y','with (E[_x]) S[_y]').tmacro('continue _label','continue _label').tmacro('continue','continue').tmacro('_label: _stuff','_label: S[_stuff]')})),this.shallow('trace_directive_expander',trace_directive_expander.configure(function (){this.method('tmacro',(function (lhs,rhs){return this.macro(convert_trace_directives_in(lhs),rhs)})).tmacro('H[_tree, _x]',(function (match){return expression_hook(match._tree,match._x)})).tmacro('D[_tree, _object, _method, [_parameters]]',(function (match){return direct_method_hook(match._tree,match)})).tmacro('I[_tree, _object, _method, [_parameters]]',(function (match){return indirect_method_hook(match._tree,match)})).tmacro('E[_x]',(function (match){return expression(match._x)})).tmacro('S[_x]',(function (match){return statement(match._x)}))})),this.final_macro('_x',(function (match){return statement(match._x)})),this.self_variable=self,this.on_bake((function (invocation){return (function (it){return (trace_directive_expander.bake())}).call(this,((function (it){return (statement.bake())}).call(this,(expression.bake()))))})))}).call(this)})})())));
