#!/bin/bash
# Builds a stable version of Caterwaul.

if [[ -d stable/$1 ]]; then
  echo version $1 already exists
  return 1
fi

./caterwaul.html render || return 1
./caterwaul.html test | tee test-log

grep 'Error' test-log && return 1
rm test-log

mkdir stable/$1
cp *.js modules/*.js stable/$1/
cp caterwaul.html stable/$1/
git add stable/$1
git commit -am "Automatic commit for version $1"
git tag version-$1
cp .git/refs/heads/master stable/$1/commit-id
tar -cj stable/$1 > stable/$1.tar.bz2
git add stable/$1*
git commit -am "Automatic commit for version $1 deployment"
