// Falsy ref tests.
// It's possible that Caterwaul 0.5 and earlier reject falsy references; e.g.

// | defmacro[foo][fn_[new this.ref(false)]];
//   foo   // may result in undefined variable

test('caterwaul.std.falsy-refs', function () {
  var c = caterwaul.clone('std macro');

  c(function (eq) {
    defmacro[falsy][fn_[new this.ref(false)]];
    eq(falsy, false);
  })(eq);
});
// Generated by SDoc 
