// Caterwaul with_gensyms tests

test(function () {
  var c = caterwaul.clone('std.qs', 'std.qg', 'std.fn', 'std.defmacro', 'std.with_gensyms', 'std.string');

  c(function (eq) {
    defmacro[foo][fn_[qs[qs[_]].replace({_: with_gensyms[bar][bar]})]];
    defmacro[bif][fn_[qs[qs[_]].replace({_: with_gensyms[bif, baz, bar][bar]})]];

    var symbol1 = foo;
    var symbol2 = bif;

    if (symbol1.data === symbol2.data) throw new Error('Gensyms not unique: #{symbol1.data} === #{symbol2.data}');
  }) (eq);
});

// Generated by SDoc 
