// DSL tests for the caterwaul parser.

test('caterwaul.parser.dsl', function () {
  var c = caterwaul.clone('std parser');

  c(function (eq) {
    var bind_test = peg[c('a')];
    eq(bind_test('a').result, 'a');
  })(eq);
});
// Generated by SDoc 
