// Tests for lookahead assertions.

test('caterwaul.parser.lookahead', function () {
  var c = caterwaul.clone('std parser');

  c(function (eq) {
    var p = caterwaul.parser.parsers;
    
    var aa = p.seq(p.c('a'), p.match(p.c('a')), p.alt(p.c('a'), p.c('b')));
    eq(aa('aa').join(','), 'a,a,a');
    eq(aa('ab'), false);
    eq(aa('a'), false);

    var ab = p.seq(p.c('a'), p.reject(p.c('a')), p.alt(p.c('a'), p.c('b')));
    eq(ab('ab').length, 3);
    eq(ab('ab')[0], 'a');
    eq(ab('ab')[1], null);
    eq(ab('ab')[2], 'b');
    eq(ab('aa'), false);
    eq(ab('a'), false);
  })(eq);
});
// Generated by SDoc 
