// Tests for the .each() method and <se<

test(function () {
  var c = caterwaul.clone('std continuation seq');
  
  c(function (eq) {
    var s = sa<< [1, 2, 3];
    var i = 0;

    i++ <se< s;
    eq(i, 3);

    i = 0;
    (i += x) <se< s;
    eq(i, 6);
  })(eq);

  c(function (eq) {
    var naturals = x + 1 <sa< [1];
    var i = 0;
    naturals.first(100).each(fn[x][i += x]);
    eq(i, 5050);
  })(eq);
});

// Generated by SDoc 
