// Finite sequence core method tests.

test('caterwaul.seq.finite.core', function () {
  var c = caterwaul.clone('std seq');
  c(function (eq) {
    var s = new caterwaul.seq.finite();
    eq(s.size(), 0);
    eq('0' in s, false);
    eq(s.push(1), s);
    eq('0' in s, true);
    eq(s.size(), 1);
    eq(s.pop(), 1);
    eq('0' in s, false);
    eq(s.size(), 0);
  })(eq);
});
// Generated by SDoc 
