// Finite sequence object-related tests.

test('caterwaul.seq.finite.object', function () {
  var c = caterwaul.clone('std seq');

  c(function (eq) {
    var base = {foo: 'bar', bif: 'baz'};
    var ks = caterwaul.seq.finite.keys(base);
    var vs = caterwaul.seq.finite.values(base);
    var ps = caterwaul.seq.finite.pairs(base);

    eq(ks.size(), 2);
    eq(ks[0].length, 3);
    eq(ks[1].length, 3);
    eq(base[ks[0]].length, 3);
    eq(base[ks[1]].length, 3);

    eq(vs.size(), 2);
    eq(base[ks[0]], vs[0]);
    eq(base[ks[1]], vs[1]);

    eq(ps.size(), 2);
    eq(base[ps[0][0]], ps[0][1]);
    eq(base[ps[1][0]], ps[1][1]);

    var o = ps.object();

    eq(o.foo, 'bar');
    eq(o.bif, 'baz');

    var o2 = {other: 'property'};
    eq(ps.object(o2), o2);
    eq(o2.foo, 'bar');
    eq(o2.bif, 'baz');
    eq(o2.other, 'property');
  })(eq);
});

// Generated by SDoc 
