// Finite sequence folding tests

test(function () {
  var c = caterwaul.clone('std seq');

  c(function (eq) {
    var xs = new caterwaul.seq.finite([1, 2, 3, 4, 5]);

    eq(xs.foldl(fn[x, y][x + y]), 15);
    eq(xs.foldl(fn[x, y][x + y], ''), '12345');
    eq(xs.foldl(fn[x, y]['(#{x + y})'], ''), '(((((1)2)3)4)5)');

    var ys = new caterwaul.seq.finite([1, 2, 3, 4]);

    eq(ys.foldr(fn[x, y][x + y]), 10);
    eq(ys.foldr(fn[x, y][x + y], ''), '1234');
    eq(ys.foldr(fn[x, y]['(#{x + y})'], ''), '(1(2(3(4))))');
  })(eq);
});

// Generated by SDoc 
