// Head/tail method tests.

test('caterwaul.seq.infinite.y', function () {
  var c = caterwaul.clone('std continuation seq');
  c(function (eq) {
    var naturals = new caterwaul.seq.infinite.y(fn[x][x + 1], 0);

    eq(naturals.h.constructor, Function);
    eq(naturals.t.constructor, Function);

    eq(naturals.constructor, caterwaul.seq.infinite.y);
    eq(naturals.h(), 0);
    eq(naturals.t().constructor, naturals.constructor);

    eq(naturals.t().h(), 1);
    eq(naturals.t().t().h(), 2);
  })(eq);
});

// Generated by SDoc 
