// Numeric sequence tests.

test('caterwaul.seq.numeric', function () {
  var c = caterwaul.clone('std seq continuation');

  c(function (eq) {
    eq(caterwaul.seq.naturals.take(fn[x][x < 5]).join(','), '0,1,2,3,4');

    eq(caterwaul.seq.naturals.h(), 0);
    eq(caterwaul.seq.naturals.t().h(), 1);
    eq(caterwaul.seq.naturals.t().t().h(), 2);

    eq(seq[N].h(), 0);
    eq(seq[N].t().h(), 1);
    eq(seq[N].t().t().h(), 2);

    eq(seq[N[10]].h(), 10);
    eq(seq[N[10]].t().h(), 11);

    eq(caterwaul.seq.n(5).join(','), '0,1,2,3,4');
    eq(caterwaul.seq.n(1, 5).join(','), '1,2,3,4');
    eq(caterwaul.seq.n(1, 5, 0.5).join(','), '1,1.5,2,2.5,3,3.5,4,4.5');
  })(eq);
});
// Generated by SDoc 
