// Object tests.

test(function () {
  var c = caterwaul.clone('std seq');

  c(function (eq) {
    var o = {foo: 1, bar: 2, bif: 3, baz: 4};
    var ks = (sk<< o).force().sort();

    eq(ks.length, 4);
    eq(ks[0], 'bar');
    eq(ks[1], 'baz');
    eq(ks[2], 'bif');
    eq(ks[3], 'foo');

    var vs = (sv<< o).force().sort();
    eq(vs.length, 4);
    eq(vs[0], 1);
    eq(vs[1], 2);
    eq(vs[2], 3);
    eq(vs[3], 4);

    var kvs = (x.join(': ') <sm< skv<< o).force().sort();
    eq(kvs.length, 4);
    eq(kvs[0], 'bar: 2');
    eq(kvs[1], 'baz: 4');
    eq(kvs[2], 'bif: 3');
    eq(kvs[3], 'foo: 1');
  })(eq);
});

// Generated by SDoc 
