// Caterwaul JS | Spencer Tipping
// Licensed under the terms of the MIT source code license

// Introduction.
// Caterwaul is a Javascript-to-Javascript compiler. Visit http://spencertipping.com/caterwaul/caterwaul.html for information about how and why you might use it.

(function (f) {return f(f, (function (x) {return function () {return ++x}})(0))})(function (initializer, unique, undefined) {

- pinclude pp::js::core/caterwaul.utilities
- pinclude pp::js::core/caterwaul.configuration
- pinclude pp::js::core/caterwaul.global

- pinclude pp::js::core/caterwaul.parser-data

- pinclude pp::js::core/caterwaul.tree
- pinclude pp::js::core/caterwaul.parser
- pinclude pp::js::core/caterwaul.compiler

- pinclude pp::js::core/caterwaul.bake

- pinclude pp::js::core/caterwaul.macroexpander
- pinclude pp::js::core/caterwaul.macroexpander.naive
- pinclude pp::js::core/caterwaul.macroexpander.jit

- pinclude pp::js::core/caterwaul.precompile
- pinclude pp::js::core/caterwaul.composition

- pinclude pp::js::core/caterwaul.init

  return caterwaul_global});
// Generated by SDoc 
