// Baking support.
// To "bake" a caterwaul function is to freeze its settings and apply long-run optimizations such as macroexpander compilation. Once a function is baked you can't do certain things, most notably
// adding macros. (Other restrictions may apply later as further optimizations are implemented.) You also can't re-bake a caterwaul instance.

  caterwaul_global.event('bake').on_bake(function () {this.on_bake(function () {throw new Error('cannot bake a caterwaul function more than once')})}).
                  method('method_until_baked', function (name, f) {return this.method(name, f).on_bake(function () {
                                                                          this.method(name, function () {throw new Error('cannot call ' + name + ' on a baked caterwaul')})})});
// Generated by SDoc 
