// Unit testing library functions

var already_failed = false;
var on_error = function (e) {throw new Error(e)};

var log = function (message) {};

var eq = function (x, y, message) {
  if (x == y) return true;
  else        return on_error((message ? message + ': ' : '') + '\n' + x + '\n\n!==\n\n' + y);
};

var aeq = function (xs, ys, message) {
  eq(xs.length, ys.length, xs + ' == ' + ys + ': ' + message + ' (length check)');
  for (var i = 0, l = xs.length; i < l; ++i)
    eq(xs[i], ys[i], message + ' (element check: ' + i + ')');
  return true;
};

var test = function (f) {
  f()

  print('Reinitializing');
  caterwaul = caterwaul.reinitialize(caterwaul);
  f();
};

// Generated by SDoc 