// Unit testing library functions

var already_failed = false;
var on_error = function (e) {typeof console === 'undefined' ?
                               print('Error at eq count ' + eq_count) :
                               console.log('Error at eq count ' + eq_count);
                             throw new Error(e)};
var eq_count = 0;

var _log = function (message) {};

var eq = function (x, y, message) {
  ++eq_count;
  if (x == y) return true;
  else        return on_error((message ? message + ': ' : ' (eq ' + eq_count + ')') + '\n' + x + '\n\n!==\n\n' + y);
};

var aeq = function (xs, ys, message) {
  eq(xs.length, ys.length, xs + ' == ' + ys + ': ' + message + ' (length check)');
  for (var i = 0, l = xs.length; i < l; ++i)
    eq(xs[i], ys[i], message + ' (element check: ' + i + ')');
  return true;
};

var test = function (f) {
  try {
    eq_count = 0;
    f();
    caterwaul = caterwaul.reinitialize(caterwaul);
    eq_count = 0;
    f();
  } catch (e) {
    on_error(e);
  }
};

// Generated by SDoc 
