// Unit testing library functions

var already_failed = false;
var on_error = function (name, e) {typeof console === 'undefined' ?
                                     print('Error at eq count ' + eq_count + ' in test ' + name) :
                                     console.log('Error at eq count ' + eq_count + ' in test ' + name);
                                   throw new Error(e)};
var eq_count = 0;

var _log = function (message) {};

var eq = function (x, y, message) {
  ++eq_count;
  if (x == y) return true;
  else        return on_error(current_test, (message ? message + ': ' : ' (eq ' + eq_count + ')') + '\n' + x + '\n\n!==\n\n' + y);
};

var aeq = function (xs, ys, message) {
  eq(xs.length, ys.length, xs + ' == ' + ys + ': ' + message + ' (length check)');
  for (var i = 0, l = xs.length; i < l; ++i)
    eq(xs[i], ys[i], message + ' (element check: ' + i + ')');
  return true;
};

var current_test = null;
var test = function (name, f) {
  try {
    current_test = name;
    eq_count = 0;
    f();
    caterwaul = caterwaul.reinitialize(caterwaul);
    eq_count = 0;
    f();
  } catch (e) {
    on_error(name, e);
  }
};

// Generated by SDoc 
