// Client-side unit testing hooks.

on_error = function (e) {
  var d = document.createElement('div');
  d.appendChild(document.createTextNode(e.description));
  document.getElementById('log').appendChild(d);
};

log = function (message) {
  on_error('Log: ' + message);
};

// Generated by SDoc 
