caterwaul.tconfiguration('std','seq.core',caterwaul.precompiled_internal((function (){null;
return (function (gensym_2_gnathvw5_29yenz){this.shallow('seq',{core:((function (_){return _.prototype=((function (p){return p.constructor=_,p})).call(this,[]),_})).call(this,(function (){return null}))})})})())).tconfiguration('std opt continuation','seq.finite.core',caterwaul.precompiled_internal((function (){null;
return (function (gensym_2_gnathvw5_29yeo0){this.configure('seq.core').seq.finite=((function (c){return c.prototype=((function (_){return _.size=(function (){return this.l||this.length}),_.slice=(function (){return ((function (_){return (function (gensym_2_gnathvw5_29yeio){for (var gensym_2_gnathvw5_29yeip=gensym_2_gnathvw5_29yeio>=0&&gensym_2_gnathvw5_29yeio>>3,gensym_2_gnathvw5_29yeiq=gensym_2_gnathvw5_29yeio>=0&&gensym_2_gnathvw5_29yeio&7,i=0;
i<gensym_2_gnathvw5_29yeiq;
 ++i)_.push(this[i]);
for (var gensym_2_gnathvw5_29yeir=0;
gensym_2_gnathvw5_29yeir<gensym_2_gnathvw5_29yeip;
 ++gensym_2_gnathvw5_29yeir){_.push(this[i]);
i++;
_.push(this[i]);
i++;
_.push(this[i]);
i++;
_.push(this[i]);
i++;
_.push(this[i]);
i++;
_.push(this[i]);
i++;
_.push(this[i]);
i++;
_.push(this[i]);
i++};
return gensym_2_gnathvw5_29yeio}).call(this,this.size()),_})).call(this,[])}),_.constructor=c,_})).call(this,new this.seq.core()),c})).call(this,((function (xs){return this.length=this.l=xs?(function (gensym_2_gnathvw5_29yeio){for (var gensym_2_gnathvw5_29yeip=gensym_2_gnathvw5_29yeio>=0&&gensym_2_gnathvw5_29yeio>>3,gensym_2_gnathvw5_29yeiq=gensym_2_gnathvw5_29yeio>=0&&gensym_2_gnathvw5_29yeio&7,i=0;
i<gensym_2_gnathvw5_29yeiq;
 ++i)this[i]=xs[i];
for (var gensym_2_gnathvw5_29yeir=0;
gensym_2_gnathvw5_29yeir<gensym_2_gnathvw5_29yeip;
 ++gensym_2_gnathvw5_29yeir){this[i]=xs[i];
i++;
this[i]=xs[i];
i++;
this[i]=xs[i];
i++;
this[i]=xs[i];
i++;
this[i]=xs[i];
i++;
this[i]=xs[i];
i++;
this[i]=xs[i];
i++;
this[i]=xs[i];
i++};
return gensym_2_gnathvw5_29yeio}).call(this,xs.size?xs.size():xs.length):0,undefined})))})})())).tconfiguration('std opt continuation','seq.finite.serialization',caterwaul.precompiled_internal((function (){null;
return (function (gensym_2_gnathvw5_29yeo1){((function (_){return _.toString=(function (){return ('seq['+(this.slice().join(", "))+']')}),_.join=(function (x){return this.slice().join(x)}),_})).call(this,this.configure('seq.finite.core').seq.finite.prototype)})})())).tconfiguration('std opt continuation','seq.finite.mutability',caterwaul.precompiled_internal((function (){null;
return (function (gensym_2_gnathvw5_29yeo2){(function (push,slice){return ((function (_){return _.push=(function (){return (function (as){return ((function (_){return this.length=this.l,this})).call(this,(function (gensym_2_gnathvw5_29yeio){for (var gensym_2_gnathvw5_29yeip=gensym_2_gnathvw5_29yeio>=0&&gensym_2_gnathvw5_29yeio>>3,gensym_2_gnathvw5_29yeiq=gensym_2_gnathvw5_29yeio>=0&&gensym_2_gnathvw5_29yeio&7,i=0;
i<gensym_2_gnathvw5_29yeiq;
 ++i)this[this.l++]=as[i];
for (var gensym_2_gnathvw5_29yeir=0;
gensym_2_gnathvw5_29yeir<gensym_2_gnathvw5_29yeip;
 ++gensym_2_gnathvw5_29yeir){this[this.l++]=as[i];
i++;
this[this.l++]=as[i];
i++;
this[this.l++]=as[i];
i++;
this[this.l++]=as[i];
i++;
this[this.l++]=as[i];
i++;
this[this.l++]=as[i];
i++;
this[this.l++]=as[i];
i++;
this[this.l++]=as[i];
i++};
return gensym_2_gnathvw5_29yeio}).call(this,as.length))}).call(this,arguments)}),_.pop=(function (){return ((function (_){return delete this[this.length=this.l],_})).call(this,this[ --this.l])}),_.concat=(function (xs){return ((function (_){return _.push.apply(_,slice.call(xs)),_})).call(this,new this.constructor(this))}),_})).call(this,this.configure('seq.finite.core').seq.finite.prototype)}).call(this,Array.prototype.push,Array.prototype.slice)})})())).tconfiguration('std opt continuation','seq.finite.object',caterwaul.precompiled_internal((function (){null;
return (function (gensym_2_gnathvw5_29yeo3){(function (own){return ((function (_){return _.keys=(function (o,all){return ((function (_){return (function (gensym_2_gnathvw5_29yeo4){for (var k in o)if (all||own.call(o,k))_.push(k)})(),_})).call(this,new _())}),_.values=(function (o,all){return ((function (_){return (function (gensym_2_gnathvw5_29yeo5){for (var k in o)if (all||own.call(o,k))_.push(o[k])})(),_})).call(this,new _())}),_.pairs=(function (o,all){return ((function (_){return (function (gensym_2_gnathvw5_29yeo6){for (var k in o)if (all||own.call(o,k))_.push([k,o[k]])})(),_})).call(this,new _())}),_.prototype.object=(function (o){return ((function (_){return this.each((function (p){return _[p[0]]=p[1]})),_})).call(this,(o||{}))}),_})).call(this,this.configure('seq.finite.core').seq.finite)}).call(this,Object.prototype.hasOwnProperty)})})())).tconfiguration('std opt continuation','seq.finite.traversal',caterwaul.precompiled_internal((function (){null;
return (function (gensym_2_gnathvw5_29yeo7){((function (_){return _.map=(function (f){return ((function (_){return (function (gensym_2_gnathvw5_29yeio){for (var gensym_2_gnathvw5_29yeip=gensym_2_gnathvw5_29yeio>=0&&gensym_2_gnathvw5_29yeio>>3,gensym_2_gnathvw5_29yeiq=gensym_2_gnathvw5_29yeio>=0&&gensym_2_gnathvw5_29yeio&7,i=0;
i<gensym_2_gnathvw5_29yeiq;
 ++i)_.push(f.call(this,this[i],i));
for (var gensym_2_gnathvw5_29yeir=0;
gensym_2_gnathvw5_29yeir<gensym_2_gnathvw5_29yeip;
 ++gensym_2_gnathvw5_29yeir){_.push(f.call(this,this[i],i));
i++;
_.push(f.call(this,this[i],i));
i++;
_.push(f.call(this,this[i],i));
i++;
_.push(f.call(this,this[i],i));
i++;
_.push(f.call(this,this[i],i));
i++;
_.push(f.call(this,this[i],i));
i++;
_.push(f.call(this,this[i],i));
i++;
_.push(f.call(this,this[i],i));
i++};
return gensym_2_gnathvw5_29yeio}).call(this,this.l),_})).call(this,new this.constructor())}),_.filter=(function (f){return ((function (_){return (function (gensym_2_gnathvw5_29yeio){for (var gensym_2_gnathvw5_29yeip=gensym_2_gnathvw5_29yeio>=0&&gensym_2_gnathvw5_29yeio>>3,gensym_2_gnathvw5_29yeiq=gensym_2_gnathvw5_29yeio>=0&&gensym_2_gnathvw5_29yeio&7,i=0;
i<gensym_2_gnathvw5_29yeiq;
 ++i)(f.call(this,this[i],i))&&(_.push(this[i]));
for (var gensym_2_gnathvw5_29yeir=0;
gensym_2_gnathvw5_29yeir<gensym_2_gnathvw5_29yeip;
 ++gensym_2_gnathvw5_29yeir){(f.call(this,this[i],i))&&(_.push(this[i]));
i++;
(f.call(this,this[i],i))&&(_.push(this[i]));
i++;
(f.call(this,this[i],i))&&(_.push(this[i]));
i++;
(f.call(this,this[i],i))&&(_.push(this[i]));
i++;
(f.call(this,this[i],i))&&(_.push(this[i]));
i++;
(f.call(this,this[i],i))&&(_.push(this[i]));
i++;
(f.call(this,this[i],i))&&(_.push(this[i]));
i++;
(f.call(this,this[i],i))&&(_.push(this[i]));
i++};
return gensym_2_gnathvw5_29yeio}).call(this,this.l),_})).call(this,new this.constructor())}),_.each=(function (f){return ((function (_){return (function (gensym_2_gnathvw5_29yeio){for (var gensym_2_gnathvw5_29yeip=gensym_2_gnathvw5_29yeio>=0&&gensym_2_gnathvw5_29yeio>>3,gensym_2_gnathvw5_29yeiq=gensym_2_gnathvw5_29yeio>=0&&gensym_2_gnathvw5_29yeio&7,i=0;
i<gensym_2_gnathvw5_29yeiq;
 ++i)f.call(_,_[i],i);
for (var gensym_2_gnathvw5_29yeir=0;
gensym_2_gnathvw5_29yeir<gensym_2_gnathvw5_29yeip;
 ++gensym_2_gnathvw5_29yeir){f.call(_,_[i],i);
i++;
f.call(_,_[i],i);
i++;
f.call(_,_[i],i);
i++;
f.call(_,_[i],i);
i++;
f.call(_,_[i],i);
i++;
f.call(_,_[i],i);
i++;
f.call(_,_[i],i);
i++;
f.call(_,_[i],i);
i++};
return gensym_2_gnathvw5_29yeio}).call(this,_.l),_})).call(this,this)}),_.reversed=(function (){return ((function (_){return (function (l){return (function (gensym_2_gnathvw5_29yeio){for (var gensym_2_gnathvw5_29yeip=gensym_2_gnathvw5_29yeio>=0&&gensym_2_gnathvw5_29yeio>>3,gensym_2_gnathvw5_29yeiq=gensym_2_gnathvw5_29yeio>=0&&gensym_2_gnathvw5_29yeio&7,i=0;
i<gensym_2_gnathvw5_29yeiq;
 ++i)_.push(this[l-i-1]);
for (var gensym_2_gnathvw5_29yeir=0;
gensym_2_gnathvw5_29yeir<gensym_2_gnathvw5_29yeip;
 ++gensym_2_gnathvw5_29yeir){_.push(this[l-i-1]);
i++;
_.push(this[l-i-1]);
i++;
_.push(this[l-i-1]);
i++;
_.push(this[l-i-1]);
i++;
_.push(this[l-i-1]);
i++;
_.push(this[l-i-1]);
i++;
_.push(this[l-i-1]);
i++;
_.push(this[l-i-1]);
i++};
return gensym_2_gnathvw5_29yeio}).call(this,l)}).call(this,this.l),_})).call(this,new this.constructor())}),_.flat_map=(function (f){return ((function (_){return this.each((function (x,xi){return (((function (xs){return xs.each?xs:new this.constructor(xs)})).call(this,f.call(this,x,xi))).each((function (x){return _.push(x)}))})),_})).call(this,new this.constructor())}),_.foldl=(function (f,x){return (function (x,xi){return (this.l>=xi)&&((function (gensym_2_gnathvw5_29yeio){for (var gensym_2_gnathvw5_29yeip=gensym_2_gnathvw5_29yeio>=0&&gensym_2_gnathvw5_29yeio>>3,gensym_2_gnathvw5_29yeiq=gensym_2_gnathvw5_29yeio>=0&&gensym_2_gnathvw5_29yeio&7,i=0;
i<gensym_2_gnathvw5_29yeiq;
 ++i)x=f.call(this,x,this[i+xi],i+xi);
for (var gensym_2_gnathvw5_29yeir=0;
gensym_2_gnathvw5_29yeir<gensym_2_gnathvw5_29yeip;
 ++gensym_2_gnathvw5_29yeir){x=f.call(this,x,this[i+xi],i+xi);
i++;
x=f.call(this,x,this[i+xi],i+xi);
i++;
x=f.call(this,x,this[i+xi],i+xi);
i++;
x=f.call(this,x,this[i+xi],i+xi);
i++;
x=f.call(this,x,this[i+xi],i+xi);
i++;
x=f.call(this,x,this[i+xi],i+xi);
i++;
x=f.call(this,x,this[i+xi],i+xi);
i++;
x=f.call(this,x,this[i+xi],i+xi);
i++};
return gensym_2_gnathvw5_29yeio}).call(this,this.l-xi),x)}).call(this,arguments.length>1?x:this[0],2-arguments.length)}),_.foldr=(function (f,x){return (function (x,xi,l){return (l>=xi-1)&&((function (gensym_2_gnathvw5_29yeio){for (var gensym_2_gnathvw5_29yeip=gensym_2_gnathvw5_29yeio>=0&&gensym_2_gnathvw5_29yeio>>3,gensym_2_gnathvw5_29yeiq=gensym_2_gnathvw5_29yeio>=0&&gensym_2_gnathvw5_29yeio&7,i=0;
i<gensym_2_gnathvw5_29yeiq;
 ++i)x=f.call(this,this[l-(i+xi)],x,l-(i+xi));
for (var gensym_2_gnathvw5_29yeir=0;
gensym_2_gnathvw5_29yeir<gensym_2_gnathvw5_29yeip;
 ++gensym_2_gnathvw5_29yeir){x=f.call(this,this[l-(i+xi)],x,l-(i+xi));
i++;
x=f.call(this,this[l-(i+xi)],x,l-(i+xi));
i++;
x=f.call(this,this[l-(i+xi)],x,l-(i+xi));
i++;
x=f.call(this,this[l-(i+xi)],x,l-(i+xi));
i++;
x=f.call(this,this[l-(i+xi)],x,l-(i+xi));
i++;
x=f.call(this,this[l-(i+xi)],x,l-(i+xi));
i++;
x=f.call(this,this[l-(i+xi)],x,l-(i+xi));
i++;
x=f.call(this,this[l-(i+xi)],x,l-(i+xi));
i++};
return gensym_2_gnathvw5_29yeio}).call(this,l-(xi-1)),x)}).call(this,arguments.length>1?x:this[this.l-1],3-arguments.length,this.l)}),_})).call(this,this.configure('seq.finite.core seq.finite.mutability').seq.finite.prototype)})})())).tconfiguration('std opt continuation','seq.finite.zip',caterwaul.precompiled_internal((function (){var gensym_2_gnathvw5_29yeoo=caterwaul.clone('std.qs std.qg std.bind std.lvalue std.cond std.fn std.obj std.ref std.string std opt.unroll opt continuation.core continuation.unwind continuation.cps continuation.delimited continuation');
return (function (gensym_2_gnathvw5_29yeo8){((function (_){return (function (seq,slice){return _.prototype.zip=(function (){return (function (as,options){return (as[as.size()-1].constructor===Object)&&(gensym_2_gnathvw5_29yeoo.util.merge(options,as.pop())),(function (l,f){return ((function (_){return (function (gensym_2_gnathvw5_29yeio){for (var gensym_2_gnathvw5_29yeip=gensym_2_gnathvw5_29yeio>=0&&gensym_2_gnathvw5_29yeio>>3,gensym_2_gnathvw5_29yeiq=gensym_2_gnathvw5_29yeio>=0&&gensym_2_gnathvw5_29yeio&7,i=0;
i<gensym_2_gnathvw5_29yeiq;
 ++i)_.push(f.apply({i:i},as.map((function (x){return x[i]})).slice()));
for (var gensym_2_gnathvw5_29yeir=0;
gensym_2_gnathvw5_29yeir<gensym_2_gnathvw5_29yeip;
 ++gensym_2_gnathvw5_29yeir){_.push(f.apply({i:i},as.map((function (x){return x[i]})).slice()));
i++;
_.push(f.apply({i:i},as.map((function (x){return x[i]})).slice()));
i++;
_.push(f.apply({i:i},as.map((function (x){return x[i]})).slice()));
i++;
_.push(f.apply({i:i},as.map((function (x){return x[i]})).slice()));
i++;
_.push(f.apply({i:i},as.map((function (x){return x[i]})).slice()));
i++;
_.push(f.apply({i:i},as.map((function (x){return x[i]})).slice()));
i++;
_.push(f.apply({i:i},as.map((function (x){return x[i]})).slice()));
i++;
_.push(f.apply({i:i},as.map((function (x){return x[i]})).slice()));
i++};
return gensym_2_gnathvw5_29yeio}).call(this,l),_})).call(this,new this.constructor())}).call(this,as.map((function (x){return x.size?x.size():x.length})).foldl(options.outer?(function (x,y){return Math.max(x,y)}):(function (x,y){return Math.min(x,y)})),options.f)}).call(this,new seq([this].concat(slice.call(arguments))),{f:(function (){return new seq(arguments)}),outer:false})})}).call(this,_,Array.prototype.slice),_})).call(this,this.configure('seq.finite.traversal').seq.finite)})})())).tconfiguration('std opt continuation','seq.finite.quantification',caterwaul.precompiled_internal((function (){var gensym_2_gnathvw5_29yeoq=caterwaul.clone('std.qs std.qg std.bind std.lvalue std.cond std.fn std.obj std.ref std.string std opt.unroll opt continuation.core continuation.unwind continuation.cps continuation.delimited continuation');
return (function (gensym_2_gnathvw5_29yeo9){((function (_){return _.exists=(function (f){return (gensym_2_gnathvw5_29yeoq.continuation.call_cc.call(this,(function (gensym_2_gnathvw5_29yeor){return (function (){return (function (cc){return (function (gensym_2_gnathvw5_29yeio){for (var gensym_2_gnathvw5_29yeip=gensym_2_gnathvw5_29yeio>=0&&gensym_2_gnathvw5_29yeio>>3,gensym_2_gnathvw5_29yeiq=gensym_2_gnathvw5_29yeio>=0&&gensym_2_gnathvw5_29yeio&7,i=0;
i<gensym_2_gnathvw5_29yeiq;
 ++i)((function (_){return _&&cc(_)})).call(this,f.call(this,this[i],i));
for (var gensym_2_gnathvw5_29yeir=0;
gensym_2_gnathvw5_29yeir<gensym_2_gnathvw5_29yeip;
 ++gensym_2_gnathvw5_29yeir){((function (_){return _&&cc(_)})).call(this,f.call(this,this[i],i));
i++;
((function (_){return _&&cc(_)})).call(this,f.call(this,this[i],i));
i++;
((function (_){return _&&cc(_)})).call(this,f.call(this,this[i],i));
i++;
((function (_){return _&&cc(_)})).call(this,f.call(this,this[i],i));
i++;
((function (_){return _&&cc(_)})).call(this,f.call(this,this[i],i));
i++;
((function (_){return _&&cc(_)})).call(this,f.call(this,this[i],i));
i++;
((function (_){return _&&cc(_)})).call(this,f.call(this,this[i],i));
i++;
((function (_){return _&&cc(_)})).call(this,f.call(this,this[i],i));
i++};
return gensym_2_gnathvw5_29yeio}).call(this,this.l),false}).apply(gensym_2_gnathvw5_29yeor,arguments)})})(this)))}),_.forall=(function (f){return  !this.exists((function (){return  !f.apply(this,arguments)}))}),_})).call(this,this.configure('seq.finite.core').seq.finite.prototype)})})())).tconfiguration('std opt continuation','seq.infinite.core',caterwaul.precompiled_internal((function (){null;
return (function (gensym_2_gnathvw5_29yeoa){this.configure('seq.core').seq.infinite=((function (_){return (function (i){return _.def=(function (name,ctor,h,t){return i[name]=((function (_){return _.prototype=((function (_){return _.h=h,_.t=t,_.constructor=ctor,_})).call(this,new i()),_})).call(this,ctor)})}).call(this,_),_.def('cons',(function (h,t){return this._h=h,this._t=t}),(function (){return this._h}),(function (){return this._t})),_.def('k',(function (x){return this._x=x}),(function (){return this._x}),(function (){return this})),_})).call(this,((function (_){return (function (ctor){return _.prototype=((function (_){return _.constructor=ctor,_})).call(this,new this.seq.core())}).call(this,_),_})).call(this,(function (){return null})))})})())).tconfiguration('std opt continuation','seq.infinite.y',caterwaul.precompiled_internal((function (){null;
return (function (gensym_2_gnathvw5_29yeob){this.configure('seq.infinite.core').seq.infinite.def('y',((function (f,x){return this._f=f,this._x=x,undefined})),(function (){return this._x}),(function (){return new this.constructor(this._f,this._f(this._x))}))})})())).tconfiguration('std opt continuation','seq.infinite.transform',caterwaul.precompiled_internal((function (){var gensym_2_gnathvw5_29yeov=caterwaul.clone('std.qs std.qg std.bind std.lvalue std.cond std.fn std.obj std.ref std.string std opt.unroll opt continuation.core continuation.unwind continuation.cps continuation.delimited continuation');
var gensym_2_gnathvw5_29yeow=gensym_2_gnathvw5_29yeov;
return (function (gensym_2_gnathvw5_29yeoc){((function (_){return _.prototype.map=(function (f){return new _.map(f,this)}),_.def('map',((function (f,xs){return this._f=f,this._xs=xs,undefined})),(function (){return this._f(this._xs.h())}),(function (){return new this.constructor(this._f,this._xs.t())})),_.prototype.filter=(function (f){return new _.filter(f,this)}),_.def('filter',((function (f,xs){return this._f=f,this._xs=(function (){var next=(function (s){return (function (cc){return f(s.h())?cc(s):(gensym_2_gnathvw5_29yeov.continuation.call_tail.call(next(s.t()),cc))})});
return (gensym_2_gnathvw5_29yeow.continuation.call_cc.call(this,next(xs)))}).call(this),undefined})),(function (){return this._xs.h()}),(function (){return new this.constructor(this._f,this._xs.t())})),_})).call(this,this.configure('seq.infinite.core').seq.infinite)})})())).tconfiguration('std opt continuation','seq.infinite.traversal',caterwaul.precompiled_internal((function (){var gensym_2_gnathvw5_29yeoy=caterwaul.clone('std.qs std.qg std.bind std.lvalue std.cond std.fn std.obj std.ref std.string std opt.unroll opt continuation.core continuation.unwind continuation.cps continuation.delimited continuation');
var gensym_2_gnathvw5_29yeoz=gensym_2_gnathvw5_29yeoy;
var gensym_2_gnathvw5_29yep0=gensym_2_gnathvw5_29yeoy;
var gensym_2_gnathvw5_29yep1=gensym_2_gnathvw5_29yeoy;
return (function (gensym_2_gnathvw5_29yeod){(function (finite){return ((function (_){return _.drop=(function (f){return (function (){var next=(function (s){return (function (cc){return f(s.h())?(gensym_2_gnathvw5_29yeoy.continuation.call_tail.call(next(s.t()),cc)):cc(s)})});
return (gensym_2_gnathvw5_29yeoz.continuation.call_cc.call(this,next(this)))}).call(this)}),_.take=(function (f){return (function (){var xs=new finite(),next=(function (s){return (function (cc){return (function (h){return f(h)?(xs.push(h),(gensym_2_gnathvw5_29yep0.continuation.call_tail.call(next(s.t()),cc))):cc(xs)}).call(this,s.h())})});
return (gensym_2_gnathvw5_29yep1.continuation.call_cc.call(this,next(this)))}).call(this)}),_})).call(this,this.configure('seq.infinite.core').seq.infinite.prototype)}).call(this,this.configure('seq.finite.core seq.finite.mutability').seq.finite)})})())).tconfiguration('std opt continuation','seq.numeric',caterwaul.precompiled_internal((function (){null;
return (function (gensym_2_gnathvw5_29yeoe){((function (_){return _.naturals_from=(function (x){return new _.infinite.y((function (n){return n+1}),x)}),_.naturals=_.naturals_from(0),_.n=(function (l,u,s){return (function (lower,upper){return (function (step){return new _.infinite.y((function (n){return n+step}),lower).take((function (x){return (upper-lower)*(upper-x)>0}))}).call(this,Math.abs(s||1)*(lower<upper?1: -1))}).call(this,arguments.length>1?l:0,arguments.length>1?u:l)}),_})).call(this,this.configure('seq.infinite.core seq.infinite.y seq.finite.core').seq)})})())).tconfiguration('std opt continuation','seq.dsl',caterwaul.precompiled_internal((function (){var gensym_2_gnathvw5_29yep5=caterwaul.parse(' -x');
var gensym_2_gnathvw5_29yep6=caterwaul.parse('[_]');
var gensym_2_gnathvw5_29yep7=caterwaul.parse('_[_]');
var gensym_2_gnathvw5_29yep8=caterwaul.parse(' +_');
var gensym_2_gnathvw5_29yep9=caterwaul.parse('_+x');
var gensym_2_gnathvw5_29yepa=caterwaul.clone('std.qs std.qg std.bind std.lvalue std.cond std.fn std.obj std.ref std.string std opt.unroll opt continuation.core continuation.unwind continuation.cps continuation.delimited continuation');
var gensym_2_gnathvw5_29yepb=caterwaul.parse('qg[fn[f][fn_[ !f.apply(this,arguments)]]]');
var gensym_2_gnathvw5_29yepc=caterwaul.parse('fn[xs][y]');
var gensym_2_gnathvw5_29yepd=caterwaul.parse('fb');
var gensym_2_gnathvw5_29yepe=caterwaul.parse('fn');
var gensym_2_gnathvw5_29yepf=caterwaul.parse('_x.filter(_y)');
var gensym_2_gnathvw5_29yepg=caterwaul.parse('_,_i');
var gensym_2_gnathvw5_29yeph=caterwaul.parse('_x.map(_y)');
var gensym_2_gnathvw5_29yepi=caterwaul.parse('_,_i');
var gensym_2_gnathvw5_29yepj=caterwaul.parse('_x.foldl(_y)');
var gensym_2_gnathvw5_29yepk=caterwaul.parse('_,_0,_i');
var gensym_2_gnathvw5_29yepl=caterwaul.parse('_x.filter(c(_y))');
var gensym_2_gnathvw5_29yepm=caterwaul.parse('_,_i');
var gensym_2_gnathvw5_29yepn=caterwaul.parse('_x.each(_y)');
var gensym_2_gnathvw5_29yepo=caterwaul.parse('_,_i');
var gensym_2_gnathvw5_29yepp=caterwaul.parse('_x.foldr(_y)');
var gensym_2_gnathvw5_29yepq=caterwaul.parse('_,_0,_i');
var gensym_2_gnathvw5_29yepr=caterwaul.parse('_x.forall(_y)');
var gensym_2_gnathvw5_29yeps=caterwaul.parse('_,_i');
var gensym_2_gnathvw5_29yept=caterwaul.parse('_x.exists(_y)');
var gensym_2_gnathvw5_29yepu=caterwaul.parse('_,_i');
var gensym_2_gnathvw5_29yepv=caterwaul.parse('_x.flat_map(_y)');
var gensym_2_gnathvw5_29yepw=caterwaul.parse('_,_i');
var gensym_2_gnathvw5_29yepx=caterwaul.parse('_x.drop(_y)');
var gensym_2_gnathvw5_29yepy=caterwaul.parse('_');
var gensym_2_gnathvw5_29yepz=caterwaul.parse('_x.take(_y)');
var gensym_2_gnathvw5_29yeq0=caterwaul.parse('_');
var gensym_2_gnathvw5_29yeq1=caterwaul.parse('new caterwaul.seq.infinite.y(_y,_x)');
var gensym_2_gnathvw5_29yeq2=caterwaul.parse('_');
var gensym_2_gnathvw5_29yeq3=caterwaul.parse('_+_');
var gensym_2_gnathvw5_29yeq4=caterwaul.parse('qg[_x].size()+qg[_y].size()');
var gensym_2_gnathvw5_29yeq5=caterwaul.parse('_&&_');
var gensym_2_gnathvw5_29yeq6=caterwaul.parse('((function (xp){return xp&&xp.size()?_y:xp}).call(this,_x))');
var gensym_2_gnathvw5_29yeq7=caterwaul.parse('_||_');
var gensym_2_gnathvw5_29yeq8=caterwaul.parse('((function (xp){return xp&&xp.size()?xp:_y}).call(this,_x))');
var gensym_2_gnathvw5_29yeq9=caterwaul.parse('_===_');
var gensym_2_gnathvw5_29yeqa=caterwaul.parse('qg[l[xp=_x,yp=_y][xp===yp||xp.size()===yp.size()&&xp.zip(yp).forall(fn[p][p[0]===p[1]])]]');
var gensym_2_gnathvw5_29yeqb=caterwaul.parse('_!==_');
var gensym_2_gnathvw5_29yeqc=caterwaul.parse('qg[l[xp=_x,yp=_y][xp!==yp&&(xp.size()!==yp.size()||xp.zip(yp).exists(fn[p][p[0]!==p[1]]))]]');
var gensym_2_gnathvw5_29yeqd=caterwaul.parse('_^_');
var gensym_2_gnathvw5_29yeqe=caterwaul.parse('_x.zip(_y)');
var gensym_2_gnathvw5_29yeqf=caterwaul.parse('_+_');
var gensym_2_gnathvw5_29yeqg=caterwaul.parse('_x.concat(_y)');
var gensym_2_gnathvw5_29yeqh=caterwaul.parse(' !_');
var gensym_2_gnathvw5_29yeqi=caterwaul.parse('_x.object()');
var gensym_2_gnathvw5_29yeqj=caterwaul.parse('_,_');
var gensym_2_gnathvw5_29yeqk=caterwaul.parse('_x,_y');
var gensym_2_gnathvw5_29yeql=caterwaul.parse(' ~_');
var gensym_2_gnathvw5_29yeqm=caterwaul.parse('qg[new caterwaul.seq.finite(_x)]');
var gensym_2_gnathvw5_29yeqn=caterwaul.parse('_?_:_');
var gensym_2_gnathvw5_29yeqo=caterwaul.parse('x?y:z');
var gensym_2_gnathvw5_29yeqp=caterwaul.parse('_(_)');
var gensym_2_gnathvw5_29yeqq=caterwaul.parse('_x(_y)');
var gensym_2_gnathvw5_29yeqr=caterwaul.parse('_[_]');
var gensym_2_gnathvw5_29yeqs=caterwaul.parse('_x[_y]');
var gensym_2_gnathvw5_29yeqt=caterwaul.parse('_._');
var gensym_2_gnathvw5_29yequ=caterwaul.parse('_x._y');
var gensym_2_gnathvw5_29yeqv=caterwaul.parse('_');
var gensym_2_gnathvw5_29yeqw=caterwaul.parse('qg[_x]');
var gensym_2_gnathvw5_29yeqx=caterwaul.parse(' +_');
var gensym_2_gnathvw5_29yeqy=caterwaul.parse('N');
var gensym_2_gnathvw5_29yeqz=caterwaul.parse('caterwaul.seq.naturals');
var gensym_2_gnathvw5_29yer0=caterwaul.parse('N[_]');
var gensym_2_gnathvw5_29yer1=caterwaul.parse('caterwaul.seq.naturals_from(x)');
var gensym_2_gnathvw5_29yer2=caterwaul.parse('n[_]');
var gensym_2_gnathvw5_29yer3=caterwaul.parse('caterwaul.seq.n(x)');
var gensym_2_gnathvw5_29yer5=caterwaul.parse('p[_]');
var gensym_2_gnathvw5_29yer6=caterwaul.parse('caterwaul.seq.finite.r(x)');
var gensym_2_gnathvw5_29yer7=caterwaul.parse('seq[_]');
var gensym_2_gnathvw5_29yer8=gensym_2_gnathvw5_29yepa;
return (function (gensym_2_gnathvw5_29yeof){this.configure('seq.core seq.infinite.y seq.finite.core seq.finite.zip seq.finite.traversal seq.finite.mutability').seq.dsl=((function (_){return (function (){var rxy=(function (tree){return (function (x,y){return tree.replace({_x:_.macroexpand(x),_y:y&&_.macroexpand(y)})})}),seq=(function (gensym_2_gnathvw5_29yep4){return (function (){return (function (xs){return new this.seq.finite(xs)}).apply(gensym_2_gnathvw5_29yep4,arguments)})})(this),prepend=(function (operator){return (function (x){return ((function (_){return _.data=operator,_})).call(this,gensym_2_gnathvw5_29yep5.replace({x:x}))})}),tree_forms=(function (){var base=seq([gensym_2_gnathvw5_29yep6,gensym_2_gnathvw5_29yep7]),mod=(function (fs,op){return fs.concat(fs.map(prepend(op)))});
return mod(mod(base,'u-'),'u~').concat(seq([gensym_2_gnathvw5_29yep8]))}).call(this),template=(function (op){return (function (t){return ((function (_){return _.data=op,_})).call(this,gensym_2_gnathvw5_29yep9.replace({x:t}))})}),qw=gensym_2_gnathvw5_29yepa.util.qw,not=gensym_2_gnathvw5_29yepb,trees_for=(function (op){return ((function (_){return _.map(template(op.replace(/!$/,'')))})).call(this,((function (_){return op.charAt(op.length-1)==='!'?_.map(prepend('u!')):_})).call(this,tree_forms))});
return _.prefix_substitute=(function (tree,prefix){return tree.rmap((function (n){return (n.data.charAt(0)==='_')&&(new n.constructor((''+(prefix)+''+(n.data.substring(1))+'')))}))}),_.define_functional=(function (op,expansion,xs){return trees_for(op).map((function (t,i){return _.macro(t,(function (l,v,r){return expansion.replace({_x:_.macroexpand(l),_y:i>=8?v:gensym_2_gnathvw5_29yepc.replace({fn:i&2?gensym_2_gnathvw5_29yepd:gensym_2_gnathvw5_29yepe,xs:_.prefix_substitute(xs,i&1?v.data:'_'),y:(i&4?_.macroexpand:(function (x){return x}))(r||v)})})}))}))}),((function (_){return _('%',gensym_2_gnathvw5_29yepf,gensym_2_gnathvw5_29yepg),_('*',gensym_2_gnathvw5_29yeph,gensym_2_gnathvw5_29yepi),_('/',gensym_2_gnathvw5_29yepj,gensym_2_gnathvw5_29yepk),_('%!',gensym_2_gnathvw5_29yepl.replace({c:not}),gensym_2_gnathvw5_29yepm),_('*!',gensym_2_gnathvw5_29yepn,gensym_2_gnathvw5_29yepo),_('/!',gensym_2_gnathvw5_29yepp,gensym_2_gnathvw5_29yepq),_('&',gensym_2_gnathvw5_29yepr,gensym_2_gnathvw5_29yeps),_('|',gensym_2_gnathvw5_29yept,gensym_2_gnathvw5_29yepu),_('-',gensym_2_gnathvw5_29yepv,gensym_2_gnathvw5_29yepw),_('>>',gensym_2_gnathvw5_29yepx,gensym_2_gnathvw5_29yepy),_('<<',gensym_2_gnathvw5_29yepz,gensym_2_gnathvw5_29yeq0),_('>>>',gensym_2_gnathvw5_29yeq1,gensym_2_gnathvw5_29yeq2),_})).call(this,_.define_functional),seq(qw('> < >= <= == !=')).each((function (op){return _.macro(((function (_){return _.data=op,_})).call(this,gensym_2_gnathvw5_29yeq3.clone()),rxy(((function (_){return _.data=op,_})).call(this,gensym_2_gnathvw5_29yeq4.clone())))})),(function (e){return ((function (_){return _(gensym_2_gnathvw5_29yeq5,rxy(gensym_2_gnathvw5_29yeq6)),_(gensym_2_gnathvw5_29yeq7,rxy(gensym_2_gnathvw5_29yeq8)),_(gensym_2_gnathvw5_29yeq9,rxy(gensym_2_gnathvw5_29yeqa)),_(gensym_2_gnathvw5_29yeqb,rxy(gensym_2_gnathvw5_29yeqc)),_(gensym_2_gnathvw5_29yeqd,rxy(gensym_2_gnathvw5_29yeqe)),_(gensym_2_gnathvw5_29yeqf,rxy(gensym_2_gnathvw5_29yeqg)),_(gensym_2_gnathvw5_29yeqh,rxy(gensym_2_gnathvw5_29yeqi)),_(gensym_2_gnathvw5_29yeqj,rxy(gensym_2_gnathvw5_29yeqk)),_(gensym_2_gnathvw5_29yeql,rxy(gensym_2_gnathvw5_29yeqm)),_(gensym_2_gnathvw5_29yeqn,(function (x,y,z){return gensym_2_gnathvw5_29yeqo.replace({x:e(x),y:e(y),z:e(z)})})),(function (rx){return _(gensym_2_gnathvw5_29yeqp,rx(gensym_2_gnathvw5_29yeqq)),_(gensym_2_gnathvw5_29yeqr,rx(gensym_2_gnathvw5_29yeqs)),_(gensym_2_gnathvw5_29yeqt,rx(gensym_2_gnathvw5_29yequ)),_(gensym_2_gnathvw5_29yeqv.as('('),rx(gensym_2_gnathvw5_29yeqw))}).call(this,(function (t){return (function (x,y){return t.replace({_x:e(x),_y:y})})})),_(gensym_2_gnathvw5_29yeqx,(function (x){return x})),(function (rx){return _(gensym_2_gnathvw5_29yeqy,(function (){return gensym_2_gnathvw5_29yeqz})),_(gensym_2_gnathvw5_29yer0,rx(gensym_2_gnathvw5_29yer1)),_(gensym_2_gnathvw5_29yer2,rx(gensym_2_gnathvw5_29yer3))}).call(this,(function (t){return (function (x){return t.replace({x:x})})})),seq(qw('sk sv sp')).zip(qw('keys values pairs')).each((function (gensym_2_gnathvw5_29yer4){return (function (){return (function (p){return _(gensym_2_gnathvw5_29yer5.replace({p:p[0]}),(function (x){return gensym_2_gnathvw5_29yer6.replace({r:p[1],x:x})}))}).apply(gensym_2_gnathvw5_29yer4,arguments)})})(this)),_})).call(this,_.macro)}).call(this,(function (x){return _.macroexpand(x)})),this.rmacro(gensym_2_gnathvw5_29yer7,_.macroexpand)}).call(this),_})).call(this,gensym_2_gnathvw5_29yer8.global().clone())})})())).configuration('seq',function (gensym_2_gnathvw5_29yeog){this.configure('seq.core seq.finite.core seq.finite.object seq.finite.mutability seq.finite.traversal seq.finite.zip seq.finite.quantification '+'seq.finite.serialization seq.infinite.core seq.infinite.y seq.infinite.transform seq.infinite.traversal '+'seq.numeric seq.dsl')});
