// Caterwaul with all modules (precompiled) | Spencer Tipping
// Licensed under the terms of the MIT source code license

- comment This is the template that produces caterwaul.all.pre.js.

- pinclude core/caterwaul.js
- pinclude modules/caterwaul.std.pre.js
- pinclude modules/caterwaul.macro.pre.js
- pinclude modules/caterwaul.opt.pre.js
- pinclude modules/caterwaul.continuation.pre.js
- pinclude modules/caterwaul.seq.pre.js
- pinclude modules/caterwaul.heap.pre.js
- pinclude modules/caterwaul.memoize.pre.js
- pinclude modules/caterwaul.parser.pre.js
// Generated by SDoc 
