// Tests for iter.n and iter.keys

test(function () {
  var f = caterwaul.clone('std', 'iter')(function (eq) {
    var iterations = 0;
    iter.n[i, 10][++iterations];
    eq(iterations, 10);
    iter.n[i, 8][++iterations];
    eq(iterations, 18);
    iter.n[i, 7][++iterations];
    eq(iterations, 25);
    iter.n[i, 1][++iterations];
    eq(iterations, 26);
    iter.n[i, 24][++iterations];
    eq(iterations, 50);

    var object = {foo: 'bar', bif: 'baz'};
    var s = '';
    iter.keys[k, object][s += k];
    eq(s, 'foobif');
    iter.keys[k, object][s += object[k]];
    eq(s, 'foobifbarbaz');

    var i = 0;
    iter.until[i >= 100][++i];
    eq(i, 100);

    return iterations;
  });

  var iterations = f(eq);
  eq(iterations, 50);
});

// Generated by SDoc 
