// Tests for iter.n and iter.keys

test(function () {
  var f = caterwaul.clone('std', 'iter')(function (eq) {
    var iterations = 0;
    eq(iter.n[i, 10][++iterations], 10);
    eq(iterations, 10);
    eq(iter.n[i, 8][++iterations], 8);
    eq(iterations, 18);
    eq(iter.n[i, 7][++iterations], 7);
    eq(iterations, 25);
    eq(iter.n[i, 1][++iterations], 1);
    eq(iterations, 26);
    eq(iter.n[i, 24][++iterations], 24);
    eq(iterations, 50);

    var object = {foo: 'bar', bif: 'baz'};
    var s = '';
    eq(iter.keys[k, object][s += k], object);
    eq(s, 'foobif');
    eq(iter.keys[k, object][s += object[k]], object);
    eq(s, 'foobifbarbaz');

    var i = 0;
    eq(iter.until[i >= 100][++i], true);
    eq(i, 100);

    return iterations;
  });

  var iterations = f(eq);
  eq(iterations, 50);
});

// Generated by SDoc 
