// Adjective macro forms | Spencer Tipping
// Licensed under the terms of the MIT source code license

// Introduction.
// Unlike adverbs, adjectives generally wrap a value as opposed to modifying a verb. It's a subtle distinction, but adjectives are often more noticeable (they come before the noun in English),
// and they can have a very direct impact on the context of the values they modify.

  caterwaul.macro_form('unary_adjective', 'prefix_binary_adjective', 'postfix_binary_adjective', function (name, def, form) {this.rmacro(form.replace({_adjective: name}, def))});
// Generated by SDoc 
