// Code generation methods | Spencer Tipping
// Licensed under the terms of the MIT source code license

// Introduction.
// These methods provide easy ways to generate common code patterns. Previous to caterwaul 1.0 they were encoded as standard-library macros, which created a lot of module interdependence and
// macroexpansion overhead (especially since most of them weren't used frequently in regular code). Now they're regular methods that take syntax trees as arguments.

// Scope creation.
// Creating a scope is one of the most common patterns. These methods create various kinds of scopes.

  caterwaul.namespace('scope')
// Generated by SDoc 
