// Grammatical construct definitions | Spencer Tipping
// Licensed under the terms of the MIT source code license

// Introduction.
// The only kind of grammar Caterwaul knows about out of the box is the 'modifier', which applies to some expression and transforms it somehow. The exact syntax that triggers such a binding are
// determined by the macro patterns defined in language-specific configurations. sdoc::js::behaviors/core/javascript-forms is one such configuration.

  caterwaul.configuration('core.grammar', function () {
    this.macro_form('modifier', 'parameterized_modifier', function (name, def, form) {this.macro(this.global.ensure_syntax(form).replace({it: name}), def)})});
// Generated by SDoc 
