// Javascript macro forms | Spencer Tipping
// Licensed under the terms of the MIT source code license

// Introduction.
// This module creates macro forms optimized for hand-coded Javascript. They won't work well at all for Coffeescript or other variants that don't support the comma operator.

  caterwaul.unary_adjective_form('_adjective[_]').unary_adjective_form('_ /_adjective');
// Generated by SDoc 
