// Caterwaul UI macros | Spencer Tipping
// Licensed under the terms of the MIT source code license

// DOM libraries.
// Right now I've only got a set of combinators for jQuery.

caterwaul.module( 'ui.jquery' ,function($) { (function( ) {var jq= 'jQuery' ,anon=$.anonymizer( 'J' , 'TS' , 'S' , 'P' , 'PS' ) ,hyphenate=function( /* unary , node */s) {;
return s.replace( /_/g , '-' ) } ,rule=function(p,e) {;
return $.rereplacer(anon(p) ,e.constructor===Function? (function(match) {return e.call(this,match) } ) :anon(e) ) } ,p= (function( ) {var p_pattern=anon( 'P[_thing]' ) ;
return( (function(node) {return p_pattern.replace( {_thing:node} ) } ) ) } ) .call(this) ,jquery_macros= (function( ) {var dom_node_template=anon( ( '' + (jq) + '(TS[_element])' ) ) ,jquery_template=anon( ( '' + (jq) + '("<span>" + (_element) + "</span>")' ) ) ,become_dom_node=function( /* unary , node */match) {;
return dom_node_template.replace(match) } ,wrap_in_jquery=function( /* unary , node */match) {;
return jquery_template.replace(match) } ;
return( [rule( 'J[_element]' , (function(match) {return match._element.is_constant() ||match._element.length?wrap_in_jquery(match) :become_dom_node(match) } ) ) ,rule( 'J[_element._class]' , 'J[_element].addClass(S[_class])' ) ,rule( 'J[_element *_attr(_val)]' , 'J[_element].attr(S[_attr], _val)' ) ,rule( 'J[_element *!_name(_val)]' , 'J[_element].data(S[_name], _val)' ) ,rule( 'J[_element /_method(_args)]' , 'J[_element]._method(_args)' ) ,rule( 'J[_element /!_event(_args)]' , 'J[_element].bind(S[_event], _args)' ) ,rule( 'J[_element %_function]' , '_function(J[_element])' ) ,rule( 'J[_element(_children)]' , 'J[_element].append(J[_children])' ) ,rule( 'J[_element[_children]]' , 'J[_element].append(_children)' ) ,rule( 'J[_element < _tree]' , 'J[_element].append((_tree).toString())' ) ,rule( 'J[_element > _child]' , 'J[_element].append(J[_child])' ) ,rule( 'J[_element >= _child]' , 'J[_element].append(_child)' ) ,rule( 'J[_element1, _element2]' , 'J[_element1].add(J[_element2])' ) ,rule( 'J[_element1 + _element2]' , 'J[_element1].add(J[_element2])' ) ,rule( 'J[_element >> _pattern]' , 'J[_element].filter(PS[_pattern])' ) ,rule( 'J[_element >>> _pattern]' , 'J[_element].find(PS[_pattern])' ) ,rule( 'J[_element << _pattern]' , 'J[_element].parents(PS[_pattern])' ) ,rule( 'J[(_element)]' , '(J[_element])' ) ,rule( 'J[[_element]]' , '[J[_element]]' ) ,rule( 'J[+_expression]' , '_expression' ) ] ) } ) .call(this) ,string_macros= (function( ) {var string=function( /* unary , node */s) {;
return new $.syntax( '"' +s.replace( /\\/g , '\\\\' ) .replace( /"/g , '\\"' ) + '"' ) } ;
return( [rule( 'TS[_identifier]' , (function(match) {return string( ( '<' + (hyphenate(match._identifier.data) ) + '>' ) ) } ) ) ,rule( 'S[_identifier]' , (function(match) {return string(hyphenate(match._identifier.data) ) } ) ) ,rule( 'PS[_identifier]' , (function(match) {return string(expand(p(match._identifier) ) .data) } ) ) ] ) } ) .call(this) ,search_macros= (function( ) {var interpolated=function( /* unary , node */node) {;
return( '(' + (node.toString() ) + ').replace(/(\\)/g, "$1$1").replace(/(")/g, "\\$1")' ) } ,binary=function( /* unary , node */op) {;
return function( /* unary , node */match) {;
return new $.syntax( ( '' + (expand(p(match._element1) ) .data) + '' + (op) + '' + (expand(p(match._element2) ) .data) + '' ) ) } } ;
return( [rule( 'P[_element]' , (function(match) {return new $.syntax(hyphenate( (function(it) {return(it=== '_' ? '*' :it) } ) .call(this, (match._element.data) ) ) ) } ) ) ,rule( 'P[_element._class]' , (function(match) {return new $.syntax( ( '' + (this(p(match._element) ) .data) + '.' + (hyphenate(match._class.data) ) + '' ) ) } ) ) ,rule( 'P[_element[_attributes]]' , (function(match) {return new $.syntax( ( '' + (this(p(match._element) ) .data) + '[' + (this(p(match._attributes) ) ) + ']' ) ) } ) ) ,rule( 'P[_attribute = _value]' , (function(match) {return new $.syntax( ( '' + (this(p(match._attribute) ) .data) + '="' + '' ) +interpolated(match._value) + '}"' ) } ) ) ,rule( 'P[(_element)]' , 'P[_element]' ) ,rule( 'P[_element1 +   _element2]' ,binary( ', ' ) ) ,rule( 'P[_element1,    _element2]' ,binary( ', ' ) ) ,rule( 'P[_element1 >>  _element2]' ,binary( ' ' ) ) ,rule( 'P[_element1 >>> _element2]' ,binary( ' ' ) ) ,rule( 'P[_element1 >   _element2]' ,binary( ' > ' ) ) ,rule( 'P[_element1(_element2)]' ,binary( ' > ' ) ) ,rule( 'P[_element /_selector]' , (function(match) {return new $.syntax( ( '' + (expand(p(match._element) ) .data) + ':' + (hyphenate(match._selector.data) ) + '' ) ) } ) ) ,rule( 'P[_element /_selector(_value)]' , (function(match) {return new $.syntax( ( '' + (expand(p(match._element) ) .data) + ':' + (hyphenate(match._selector.data) ) + '("#' ) + '{' +interpolated(match._value) + '}")' ) } ) ) ] ) } ) .call(this) ;
return($.jquery=function( /* unary , node */caterwaul_function) {;
return(function( ) {var anon_pattern=anon( 'J[_x]' ) ,jquery_expand=$($.alternatives(jquery_macros.concat(string_macros) .concat(search_macros) ) ) ;
return( (function(it) {return(it.modifiers.jquery=function( /* unary , node */match) {;
return(function(it) {return( ( (it) && (this(it) ) ) ) } ) .call(this, (jquery_expand.call(jquery_expand,anon_pattern.replace( {_x:match._expression} ) ) ) ) } ) ,it} ) .call(this, (caterwaul_function) ) ) } ) .call(this) } ) } ) .call(this) } ) ;


// Generated by SDoc 
