// Client-side unit testing hooks.

log = function (message) {
  var d = document.createElement('div');
  d.appendChild(document.createTextNode(message));
  document.getElementById('log').appendChild(d);
};
// Generated by SDoc 
